### ISSUE TITLE
[Feature] Ethernet rx-tx sensor in k/m

### ISSUE THREAD

**Issue by fezo76** [tomaae/homeassistant-mikrotik_router#10]
Hi!
it works very well. Thanks!
can be Ethernet RX-TX to show the value in kilobytes.
thanks!

**Comment by tomaae** [comment]
I have been thinking of changing that too, just cant decide if kilobytes or megabytes would be a better option.

**Comment by fezo76** [comment]
No matter which format you choose.  only the byte shows a large number and is difficult to read.  Thanks for the job

**Comment by Vandiliz3r** [comment]
Hey Man, 
I think Kbps will be better that the bps, It would be even better cool if you could specify which type of unit of measure you would like eg. Kbps, Mbps, Gbps..

Just a thought, I love this integration thanks for the efforts.

Regards

**Comment by tomaae** [comment]
that would be best, but I'm not sure if its possible to calculate while displaying a value

**Comment by Vandiliz3r** [comment]
Any idea when it will be possible to change this to KB?

**Comment by tomaae** [comment]
When my life calms down a bit. It has been high speed since new year for me and all my personal projects had to go on hold.
Hopefully I will be able to get back to this integration soon.

**Comment by fezo76** [comment]
Hi!
is a solution
create a sensor template

# Mikrotik MB conversion
     mikrotik_eth1_transmit:
          friendly_name: "MB transmit"
          unit_of_measurement: 'MB/s'
          value_template: "{{ (states('sensor.mikrotik_ether1_tx')|int / 1048576) | round(2) }}"

     mikrotik_eth1_received:
          friendly_name: "MB Received"
          unit_of_measurement: 'MB/s'
          value_template: "{{ (states('sensor.mikrotik_ether1_rx')|int / 1048576) | round(2) }}"

**Comment by tomaae** [comment]
![image](https://user-images.githubusercontent.com/23486452/76471852-227cdd80-63f4-11ea-9fc4-eb6f0863b1b8.png)
Sensor gets split like this after the change. Got to check in 24 hours and see how UI reacts

**Comment by fezo76** [comment]
work
thank you

**Comment by tomaae** [comment]
![image](https://user-images.githubusercontent.com/23486452/76714191-09429c80-6726-11ea-8a48-876d71779f0c.png)
This is what I had in mind. You can now configure units during integration setup and change options on the fly between bps/kbps/mbps.

**Comment by tomaae** [comment]
It will be in next release. I want to test it for a bit first.
If you want to test if, you can use master.
