### ISSUE TITLE
Custom Component's integration does not appear as an addable integration

### ISSUE THREAD

**Issue by ebendl** [tomaae/homeassistant-mikrotik_router#102]
I've added the custom component using HACS - v1.6.1. :

![image](https://user-images.githubusercontent.com/52312239/112223657-e7320300-8c32-11eb-9df1-ace8d817870e.png)

![image](https://user-images.githubusercontent.com/52312239/112223523-b9e55500-8c32-11eb-94da-bb09f646ac92.png)

I'm running HA Core-2021.2.3.

It loads the custom component during Home Assistant's startup as can be seen in the log:
```
Logger: homeassistant.loader
Source: loader.py:516
First occurred: 23:43:27 (2 occurrences)
Last logged: 23:43:36

You are using a custom integration for mikrotik_router which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
```

However, I can't find it inside the list of available integrations. I've removed it using HACS and re-installed it, but no difference. 

Am I doing something wrong?
![image](https://user-images.githubusercontent.com/52312239/112223376-80ace500-8c32-11eb-9d50-9f7f84ae0ad5.png)

**Comment by tomaae** [comment]
it is usually due to browser cache

**Comment by ebendl** [comment]
You were correct indeed. Accessing my HA instance through another browser showed the integration all of a sudden. 

Thanks!
