### ISSUE TITLE
Kid control not working

### ISSUE THREAD

**Issue by RSd108** [tomaae/homeassistant-mikrotik_router#106]
I have multiple Kids set up on mikrotik.
For example Kid1, Kid2, Kid3

I can see them on HA, 

If I toggle Kid1 from HA, then Kid3 gets toggled in Mikrotik
If I toggle Kid2 from HA, then Kid3 gets toggled in Mikrotik
If I toggle Kid3 from HA, then Kid3 gets toggled in Mikrotik

and vice versa, if I toggle from Mikrotik, then it does not reflect correctly in HA

**Comment by RSd108** [comment]
The debug log does not show any details of toggling the switch.  Will it still help?

**Comment by tomaae** [comment]
Did this PR fixed the issue?
