### ISSUE TITLE
[Bug] new feature #92 is great but duplicate names will fail

### ISSUE THREAD

**Issue by hellcry37** [tomaae/homeassistant-mikrotik_router#109]
## Describe the issue

Filters in Mikrotik that are commented the same (basically have same name in integration will not load and as a side effect home assistant will load very very slow, will have to wait for bootstrap time out.

What I am saying is if 2 filters are commented with same comment in mikrotik router (same name in integration) will not work.

Eventually this times out and HA loads and the only downside is the 2 rules with same name will not work.

## Expected behavior

an append of 1, 2, 3 etc to the duplicate filter names

## Software versions

 - Home Assistant version:  core-2021.4.3
 - Mikrotik Router integration version:  1.7
 - Mikrotik Hardware:  MikroTik RB4011IGS+RM
 - RouterOS version:  6.48.1

## Additional context

However if you have all comments unique or rename filters in mikrotik router everything works great.

Thanks again for this addition.

**Comment by tomaae** [comment]
Not sure I understand. Can you export those filters for me, so I can test it?

**Comment by hellcry37** [comment]
```
add action=drop chain=input comment="Drop all DNS requests from internet" connection-state=new dst-port=53 in-interface=ether1-wan protocol=udp
add action=drop chain=input comment="Drop all DNS requests from internet" connection-state=new dst-port=53 in-interface=ether1-wan protocol=tcp
```

and i renamed them to:
```
add action=drop chain=input comment="Drop all DNS requests from internet UDP" connection-state=new dst-port=53 in-interface=ether1-wan protocol=udp
add action=drop chain=input comment="Drop all DNS requests from internet TCP" connection-state=new dst-port=53 in-interface=ether1-wan protocol=tcp
```

**Comment by tomaae** [comment]
No, there is no slowdown at all
```
2021-04-12 16:57:36 DEBUG (MainThread) [custom_components.mikrotik_router.switch] New switch Mikrotik (filter bogon,drop,any,any,any:any:any-any:224.0.0.0/3:any)
2021-04-12 16:57:36 DEBUG (MainThread) [custom_components.mikrotik_router.switch] New switch Mikrotik (filter input,drop,udp,any,ether1-gateway:any:any-any:any:53)
2021-04-12 16:57:36 DEBUG (MainThread) [custom_components.mikrotik_router.switch] New switch Mikrotik (filter input,drop,tcp,any,ether1-gateway:any:any-any:any:53)
2021-04-12 16:57:36 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 1.13s
2021-04-12 16:57:36 INFO (MainThread) [homeassistant.core] Starting Home Assistant
```

![image](https://user-images.githubusercontent.com/23486452/114416043-8f8f1380-9bb0-11eb-9f0d-a365851268ef.png)
![image](https://user-images.githubusercontent.com/23486452/114416063-96b62180-9bb0-11eb-8ca9-155fc3710717.png)

I dont see any issue

**Comment by hellcry37** [comment]
maybe i miss something, close it for now i guess this will be reported if happens again, for me this what happen.

Thanks again!
