### ISSUE TITLE
program freezes 

### ISSUE THREAD

**Issue by fezo76** [tomaae/homeassistant-mikrotik_router#113]
## Describe the issue
Why the program freezes 
A clear and concise description of what the issue is.
Why does the program freeze if I use CAPsMAN 

## How to reproduce the issue
If I turn on the CAPsMAN 
3. See error
Once I wrote to freezes the program. If I use Capsman, microtik log "API logged in 192.168.88.1 - API Logged Out from 192.168.88.1 writes continuously.
The last 1.5.10 version was still good.
## Software versions

 - Home Assistant version: 
 - Mikrotik Router integration version: 
 - Mikrotik Hardware: 
 - RouterOS version:

**Comment by tomaae** [comment]
what freezes?

**Comment by fezo76** [comment]
![2021-04-29_175232](https://user-images.githubusercontent.com/58605935/116580493-b620ae80-a913-11eb-982f-63888bf081ca.jpg)
![2021-04-29_175214](https://user-images.githubusercontent.com/58605935/116580520-bc168f80-a913-11eb-90b9-2e648068c00b.jpg)
I use microtik capsmant.
If the Capsman is active, your program freezes and writes these to the mikrotik Log 
If the Capsman is not active, your program works completely well

**Comment by tomaae** [comment]
can you check debug log?
