### ISSUE TITLE
How to remove a Mikrotik device ?

### ISSUE THREAD

**Issue by Akkor70** [tomaae/homeassistant-mikrotik_router#117]
Hi I have two mikrotik router
I'm trying to remove one of them from the user interface nothing happend and the device remains
I'm on supervisor installation
How to solve ?

**Comment by Akkor70** [comment]
> whats is your ha and integration version?

I have this problem with all integrations, so I don't think it's depends from this specific
I'm trying to understand

**Comment by tomaae** [comment]
If you have such issues with all integrations, try HA forums. Maybe someone there knows how to fix it.

**Comment by Akkor70** [comment]
Ok thank You
