### ISSUE TITLE
[Bug] Device Classes are not showing propertly

### ISSUE THREAD

**Issue by sermayoral** [tomaae/homeassistant-mikrotik_router#119]
## Describe the issue

Device Classes are not showing propertly.

## Screenshots

![image](https://user-images.githubusercontent.com/30116095/118118765-a3b37400-b3ed-11eb-9baa-5de57e5734ba.png)

**Comment by tomaae** [comment]
nice, thanks.
no need to create issue for PR btw, its just extra work for you. PR is enough :)

**Comment by sermayoral** [comment]
Ok @tomaae, I'll remember that for next time 

Thanks for merging it :)
