### ISSUE TITLE
[Feature] Add support for virtual wlan interfaces

### ISSUE THREAD

**Issue by loony82361** [tomaae/homeassistant-mikrotik_router#12]
Hi! Can you add support for virlual wlan switches? I want to turn on and off my guest wifi network :)

**Comment by tomaae** [comment]
Can you give me more info about it? I dont use mikrotik wifi at all.
I have one of wifi devices by mikrotik somewhere, so I will be able to test. But I never used guest network on any system so I have no idea how to even set it up.

**Comment by loony82361** [comment]
To create a guest wifi network, I use virtual ap. I found only one video and a bunch of instructions in Russian on how to create a guest wifi network (virtual ap). I would like to manage virtual ap as well as the rest of the router interfaces.

https://www.youtube.com/watch?v=F4EKvLiLo70
https://weblance.com.ua/226-guest-wi-fi-sozdanie-gostevoy-seti-wi-fi-s-ogranicheniem-skorosti-na-primere-marshrutizatorov-mikrotik-pod-upravleniem-routeros.html

**Comment by tomaae** [comment]
I just had a look at it, but virtual interfaces are missing key. They may be possible workaround for it, but at the moment I have no idea.

**Comment by loony82361** [comment]
At the moment, I manage virtual interfaces using scripts created on the router, but I don’t have feedback

**Comment by tomaae** [comment]
yes, I understand what are you trying to do. I will try to think of some workaround how to make it work. It can certainly be useful.

**Comment by tomaae** [comment]
Implemented in v1.5.3
