### ISSUE TITLE
[Bug] All NAT rules are missing

### ISSUE THREAD

**Issue by LordBoos** [tomaae/homeassistant-mikrotik_router#125]
## Describe the issue
All NAT rules are missing from HA.

## How to reproduce the issue
Set up integration
See that no NAT rules were added

## Expected behavior
I expect that all my NAT rules are added to HA as switches.

## Screenshots
![image](https://user-images.githubusercontent.com/939813/118276548-13962d00-b4c8-11eb-9fbd-a79c79ff92e0.png)
![image](https://user-images.githubusercontent.com/939813/118276587-1ee95880-b4c8-11eb-8e48-fdec5388cb19.png)
![image](https://user-images.githubusercontent.com/939813/118276702-37f20980-b4c8-11eb-85f6-7759ac5b4ce9.png)

## Software versions

 - Home Assistant version: core-2021.5.3
 - Mikrotik Router integration version: 1.7.2
 - Mikrotik Hardware: RBD52G-5HacD2HnD
 - RouterOS version: v6.47.1

## Traceback/Error logs
No errors in log

## Additional context
Few versions back, all worked but not anymore. I had my NAT rules in lovelace (mainly for turning RDP NAT rules on/off). But someday it stoped working leaving me only with Entity not available: switch.mikrotik_nat_tcp_3389 and Entity not available: switch.mikrotik_nat_udp_3389.
Unfortunately I don't know which version broke it for me.
I tried to remove the integration, restart HA and add the integration back - it didn't resolve the issue.

**Comment by tomaae** [comment]
Check NAT group in integration for that router.
UIDs were changed few version back, so its probably in with different name.
If there is nothing, you will need to run it in debug.

**Comment by LordBoos** [comment]
There is no NAT group.
![image](https://user-images.githubusercontent.com/939813/118359444-d0998f80-b583-11eb-9f70-2dca987f2fdf.png)
How do I run it in debug?

**Comment by tomaae** [comment]
https://github.com/tomaae/homeassistant-mikrotik_router#enabling-debug

Btw, did you enable NAT in configuration?

**Comment by LordBoos** [comment]
Ok my fault. I did not have it enabled. But for my defense, it was not required to manually enable it in older versions. 
Thanks for the help.
