### ISSUE TITLE
[Bug] Integration does not show up after adding repo

### ISSUE THREAD

**Issue by gnudiff** [tomaae/homeassistant-mikrotik_router#126]
## Describe the issue

I have succesfully added "Mikrotik Router" via HACS, no errors.

However, it does not show up in the list of available Integrations, when doing the next step of Configuration -> Integrations -> Add Integration; only the default Core Mikrotik integration shows up:

## Screenshots
![image](https://user-images.githubusercontent.com/19990504/118708747-c8ac4a80-b824-11eb-9b44-f6907c025723.png)
![image](https://user-images.githubusercontent.com/19990504/118708767-cea22b80-b824-11eb-8903-ce4cd8fb9e8f.png)

## Software versions
 - Home Assistant version: Home Assistant 2021.3.4 Core on Ubuntu 20.04.2 LTS/X86_64
 - Mikrotik Router integration version: 1.7.2
 - Mikrotik Hardware: 951G-2HnD
 - RouterOS version: 6.44.2

## Additional context

I have had set up the default UPnP Mikrotik integration, which showed data rates only, and tried to use the default Mikrotik integration from core as well, because I couldn't find "Mikrotik Router" in integrations list.  I deleted them both and reinstalled "Mikrotik Router" via HACS, but no luck. 
When I had Core Mikrotik integration, it connected to api OK,  but displayed only device_tracker.* entities.

**Comment by tomaae** [comment]
This is unrelated to the integration. Just delete your browser cache.
