### ISSUE TITLE
[Bug] Some devices have manufacturername "detect"

### ISSUE THREAD

**Issue by mvdwetering** [tomaae/homeassistant-mikrotik_router#127]
## Describe the issue

A number of devices have the manufacturername "detect" instead of  `<unknown>` or a real name.

## How to reproduce the issue

Not sure, they just seem to appear sometimes for some devices.
What they all seem to have in common is that they are devices that are regularly powered off for a while or otherwise not always available (e.g. mobile devices).

## Expected behavior

A real manufacturer name or `<unknown>` (`<unknown>` is how it appear in HA devices UI, might be something like None in code).

## Screenshots

![image](https://user-images.githubusercontent.com/732514/119237952-f1dc1c00-bb3f-11eb-9dad-5550ff7a420a.png)

## Software versions

 - Home Assistant version: 2021.5.5
 - Mikrotik Router integration version: 1.7.2
 - Mikrotik Hardware: RB4011iGS+5HacQ2HnD
 - RouterOS version: v6.47.1

## Traceback/Error logs

No errors

## Additional context

I had a look at the code and searched for "detect" and noticed in `mikrotik_controller.py` the following code:
```
# Resolve manufacturer
if vals["manufacturer"] == "detect" and vals["address"] != "unknown":
    try:
        self.data["host"][uid][
            "manufacturer"
        ] = await self.async_mac_lookup.lookup(vals["mac-address"])
    except:
        self.data["host"][uid]["manufacturer"] = ""
```
I think the check in the `if` might need to be for "mac-address" instead of "address" as "mac-address" is the one that is used later in the `try`. If "address" is for an IP address that might explain why it would occur for devices that are not always available as their IP lease might run out resulting in "address" being unknown and skipping the lookup.
But this is speculation as I am not sure how the API works.

**Comment by tomaae** [comment]
hmm, that looks like a mistake, but I think your issue is different.
best is to clear manufacturer in edge cases.

**Comment by tomaae** [comment]
Can you test master?

**Comment by mvdwetering** [comment]
Just checked with master. 

From 11 entries with "detect" before I now have 2 "detect" left. 
The other 9 now have either real manufacturername or <unknown>.

Not sure why the 2 entries are still displaying as "detect". 
One of those entries is the 2.4 GHz of my Pixel phone which uses a randomized macaddress, so the mac lookup will fail. Strangely enough the 5GHz from that same phone shows as <unknown>. Only difference I see in the DHCP server is that 5GHz has an active lease, while 2.4GHz does not.

The other entry showing "detect" I can not find back in the router, so I don't know what device it is. 

Actually looking into it a bit more these 2 macaddresses have the U/L bit set so these are locally administred mac addresses and can't be looked up. Maybe that causes an issue somewhere? 
Hmmm, but still it did work for the 5GHz mac which also has the U/L bit set...
Anyway... just putting down some thoughts, not an expert on the topic. I just read https://en.wikipedia.org/wiki/MAC_address :)

**Comment by tomaae** [comment]
are those 2 left no longer available in mikrotik device? thats would explain it.
Anything that is on mikrotik should not show "detect", because it is now cleared.
Best to check what is on router directly in this case

**Comment by mvdwetering** [comment]
One of these I can not find anywhere. 
The other one is still in the DHCP server lease list., see output below. Not sure if there are other places to look.

```
[username@MikroTik Main] /ip dhcp-server lease> print
...other devices here...
19   ;;; Pixel
     192.168.178.69                    36:C3:46:xx:xx:xx Pixel                defconf                                       bound   1m48s
...more devices here...
```

**Comment by tomaae** [comment]
could you try to remove integration and readd  it? I think its set up not to change already defined values in HA

**Comment by mvdwetering** [comment]
Removing and adding it again fixed it.

**Comment by tomaae** [comment]
yes, its so devices and their names already added by different integration are not overwritten.
it was causing issues in the past for some people, I dont remember the issue number anymore tho.

**Comment by mvdwetering** [comment]
It might have been #57 which I also happened to submit.

That should be avoidable nowadays when setting "default_name" and "default_manufacturer" instead of "name" and "manufacturer" when adding devices to the deviceregistry. That way information provided by the native integrations (that use "name"and "manufacturer") will override the default_* ones.

See https://github.com/home-assistant/architecture/issues/420 for more info.

**Comment by tomaae** [comment]
yea, thats right. and since it was already set wrongly to "detect", it was not changed.

**Comment by mvdwetering** [comment]
I noticed this got marked as stale.

Is there anything still needed from my side?
The fix has been working fine since I installed master around May 23rd.

**Comment by tomaae** [comment]
if its working fine, you should close the issue ;) I'm not sure if you wanted to add anything else because of your last answer.

**Comment by mvdwetering** [comment]
Nah, it is working fine. We were drifting off into a different topic.
Lets close it.
