### ISSUE TITLE
[Bug] mikrotik_router.sensor issue

### ISSUE THREAD

**Issue by Korol-Yurii** [tomaae/homeassistant-mikrotik_router#128]
## Describe the issue

I don't get info from any sensor from Mikrotik Router
Home Assistant outputs alert:
_**The following integrations and platforms could not be set up:
mikrotik_router.sensor
Please check your config.**_

## Software versions

 - Home Assistant version: HA v0.115.2
 - Mikrotik Router integration version: v1.7.2
 - Mikrotik Hardware: HAP AC2
 - RouterOS version:  v6.48.3 

## Traceback/Error logs

 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform mikrotik_router.sensor: Platform not found (cannot import name 'SensorEntity' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)).

**Comment by tomaae** [comment]
HA v0.115 is too old, you will need recent HA version or use old version of this integration.

**Comment by Korol-Yurii** [comment]
Thanks 👍
Everything works fine after upgrade.
