### ISSUE TITLE
[Question] - Unable to get Simple Queue Attributes

### ISSUE THREAD

**Issue by Recallza** [tomaae/homeassistant-mikrotik_router#129]
Hi,

I'm trying to get the Attributes from a Simple Queue I've configured, but all the attributes are displaying as 0 EG. Download/Upload.

The Switch is working  100%

![image](https://user-images.githubusercontent.com/87154606/125073830-d52e8000-e0bc-11eb-8f6d-8860b837db30.png)

![image](https://user-images.githubusercontent.com/87154606/125073878-e4153280-e0bc-11eb-8267-d7228025622d.png)

Please assist

Thank you.

**Comment by ondras12345** [comment]
I guess this would be because 2 Mb/s is 0.25 MB/s, which gets rounded down to 0. Try changing your units to Mbps or something like that.

**Comment by Recallza** [comment]
My stupidity :/

Working 100's now.. Thanks guys.
