### ISSUE TITLE
[Question] Device tracker entity naming

### ISSUE THREAD

**Issue by clau-bucur** [tomaae/homeassistant-mikrotik_router#130]
I had to remove and readd the integration because of some stale devices which I cound not remove otherwise.
And now the device tracker entities (I mainly use this integration for it's device tracking feature) have totally different IDs even though the data in the router is unchanged (still have DHCP comments, and DNS records from which the integration could extract the correct names).

This is an example of the newly generated entity ID:
![image](https://user-images.githubusercontent.com/47672949/129474146-a506f62b-f680-4325-9b7c-42fabd123569.png)

The question would be: has anything changed in the way the naming is generated ? So I can adjust my setup.
Thank you!

**Comment by tomaae** [comment]
Some unique ID were changed over time as needed, but not recently.

**Comment by clau-bucur** [comment]
Yeah, I remember we talked about that in the past and it was working just as expected.
But I don't understand why are these names generated now...

**Comment by clau-bucur** [comment]
@tomaae I have enabled debug logs for the component and from what I see the relevant info about the devices is there.
Can you help tracking down this problem?

**Comment by clau-bucur** [comment]
Here's HA log with `custom_components.mikrotik_router: debug`
One entity to investigate would be `mac-address': '84:F3:EB:EC:75:8D`:
`2021-08-20 14:44:43 DEBUG (SyncWorker_5) [custom_components.mikrotik_router.helper] Processing entry {'.id': '*13', 'address': '192.168.1.31', 'mac-address': '84:F3:EB:EC:75:8D', 'address-lists': '', 'server': 'dhcp-LAN', 'dhcp-option': '', 'status': 'bound', 'expires-after': '20h11m33s', 'last-seen': '3h48m27s', 'active-address': '192.168.1.31', 'active-mac-address': '84:F3:EB:EC:75:8D', 'active-server': 'dhcp-LAN', 'host-name': 'irbedroom', 'radius': False, 'dynamic': False, 'blocked': False, 'disabled': False, 'comment': 'IR Bedroom'}
`
[home-assistant.zip](https://github.com/tomaae/homeassistant-mikrotik_router/files/7021327/home-assistant.zip)

Thank you!

**Comment by tomaae** [comment]
What I'm noticing right away, there are no DNS data. Could be that you just didnt include them, not sure.
They run only at start and then every 30 minutes afterwards.
Can you get debugs of initial data gathering, when integration starts right after HA reboot?

**Comment by clau-bucur** [comment]
@tomaae did you had any chance to take a look at the logs? Thanks.

**Comment by tomaae** [comment]
Sorry, I forgot about this. It was because you had hash as first character in DNS comment, making it an "empty" string.
Should be fixed now in master.

**Comment by clau-bucur** [comment]
Wait a second :)
That hash was by design and we talked about that in another thread where we discussed the device tracker.
See here: https://github.com/tomaae/homeassistant-mikrotik_router/issues/86#issuecomment-760900956

Now, because the DNS comment should be ignored, the next place it should take it's data from is the [DHCP comment](https://github.com/tomaae/homeassistant-mikrotik_router/issues/86#issuecomment-760815928), which is properly set in my setup:
![image](https://user-images.githubusercontent.com/47672949/134762518-ae3ed77c-77de-432a-9692-d6da0e8087db.png)

**Comment by tomaae** [comment]
it is not ignored, it will be recognized as empty properly
you can test it by installing master

**Comment by clau-bucur** [comment]
Great. Tested with master and it works just as you said.
Thank you again.

**Comment by tomaae** [comment]
np, thanks for testing.

**Comment by clau-bucur** [comment]
@tomaae do you have some idea when this fix will be released into a new version? Thanks!

**Comment by tomaae** [comment]
not sure right now. there is a lot to do on this integration and I'm kept too busy by my job right now.
most likely over Christmas holidays, if I manage to catch up.
