### ISSUE TITLE
[Question]The component conflicts with SmartIR

### ISSUE THREAD

**Issue by kukudemajia** [tomaae/homeassistant-mikrotik_router#132]
After setup this integration for my Mikrotik device in Home Assistant via Configuration -> Integrations -> Add -> Mikrotik Router.
SmartIR component(https://github.com/smartHomeHub/SmartIR) always is down.

**Comment by tomaae** [comment]
I dont see how that could happen.
But in any case, I'm not able to debug startir integration.
