### ISSUE TITLE
Device_class for firmware update binary sensor

### ISSUE THREAD

**Issue by skynetua** [tomaae/homeassistant-mikrotik_router#137]
Add device_class = update for  system_fwupdate binary sensor

**Comment by skynetua** [comment]
Attribute device_class is still absent after the latest update.

**Comment by tomaae** [comment]
oh right. can you try master now?

**Comment by skynetua** [comment]
It's working now. Thanks.

**Comment by tomaae** [comment]
there will be release with this soon, I just pushed previous one fast because of HA change requirements.
