### ISSUE TITLE
[Feature] Disable arp device trackers

### ISSUE THREAD

**Issue by skynetua** [tomaae/homeassistant-mikrotik_router#139]
## Is your feature request related to a problem? Please describe.
I would like to have option to exclude device trackers with source arp  from reporting to HA.

**Comment by skynetua** [comment]
> > @tomaae could you please add option to not report to HA device trackers with source 'arp' at all? I have a lot of stale devices from my ISP.
> 
> can you give me examples from routeros?
> also please open new issue for it, we dont want to mix it with this.

I'm not sure what exactly you asking. 
In arp table they looks like:
```
 #    ADDRESS         MAC-ADDRESS       INTERFACE     
...                                                                                                                                                                          
 6 DC 194.31.170.1    00:00:5E:00:01:0E ether1 
...
12 DC 194.31.171.254  4C:5E:0C:02:7E:40 ether1
```

And the same data in HA:
![Screenshot from 2021-09-15 14-06-00](https://user-images.githubusercontent.com/3670941/133423266-11d1b7ab-52ac-4465-95d2-34561e0cbb52.png)

**Comment by tomaae** [comment]
I see, so devices on provides side show up on your gateway port. That is really strange setup.
I dont think disabling ARP is an ideal solution here. Best would be to detect which is gateway port and ignore anything that shows up on it.

Can you give me output of following command? You can mask IP's if you want, just make it obvious which is your local network ip range and which is provider's
`/ip route print terse`

**Comment by skynetua** [comment]
Yep, here it is:
```
 0 ADS  dst-address=0.0.0.0/0 gateway=194.31.170.1 gateway-status=194.31.170.1 reachable via  ether1 distance=1 scope=30 target-scope=10 vrf-interface=ether1  
 1 ADC  dst-address=172.16.1.0/24 pref-src=172.16.1.1 gateway=WLAN gateway-status=WLAN reachable distance=0 scope=10 
 2 ADC  dst-address=192.168.88.0/23 pref-src=192.168.88.1 gateway=bridge gateway-status=bridge reachable distance=0 scope=10 
 3 ADC  dst-address=194.31.170.0/23 pref-src=194.31.170.75 gateway=ether1 gateway-status=ether1 reachable distance=0 scope=10
```

**Comment by tomaae** [comment]
Thanks so far, I will have to look deeper into how to properly detect outside connection

**Comment by billygr** [comment]
Hi,

I am experience the same (if we could call it issue) since it is only one additional device on ether1 and that is my VDSL modem. 
Which is ok because it's just one (at least for now). A simple ignore this interface (or what is beeing defined as WAN interface) could be enough

**Comment by tomaae** [comment]
I know its not really an issue. But it makes sense to find a way to ignore it automatically.
