### ISSUE TITLE
[Bug]Mikrotik xxxxxxxxxx error while path unknown

### ISSUE THREAD

**Issue by mvinkarklins** [tomaae/homeassistant-mikrotik_router#14]
** the bug**
Log Details (ERROR)
Logger: custom_components.mikrotik_router.mikrotikapi
First occured: 2:37:34 PM (1368 occurences)
Last logged: 3:13:35 PM

Mikrotik 192.168.XXX.XXX error while path unknown
**To Reproduce**
1. Go to developer tools
2. Logs

**Software (please complete the following information):**
 - Hass.io / Home Assistant version:  Home Assistant 0.106.6
 - HA Mikrotik Router integration version:  v1.3.1
 - Mikrotik Hardware: 951G-2HnD
--

 - Mikrotik Software version: [e.g. v6.42]

**Comment by mvinkarklins** [comment]
RouterOS update fixed the issue.

**Comment by tomaae** [comment]
1368 occurrences? are there any other messages?

**Comment by tomaae** [comment]
ah right, old token api
