### ISSUE TITLE
[Feature] UPS Monitor

### ISSUE THREAD

**Issue by Joelshowkats** [tomaae/homeassistant-mikrotik_router#144]
## Proposal
I think that will be fantastic to add UPS on Mikrotik Router Integration. Adding this function on mikrotik router integration will allow to control any Offline USB UPS using a routerOS (without nut servers and clients), and will give data too to Dude Server. Maybe it's possible to use each item on UPS list as Entity, and all the possible parameters showed as Attributes. 

## System/UPS Package Basic Info
UPS is an extra package, that offers the possibility to connect a UPS via usbhid or serial to get info about Battery Charge, Voltage, Load, etc... By the documentation, works with APC UPS that support "smart" signalling, but any UPS I tried (differents brands as CyberPower or Eaton) works, at least showing the basic necessary info. 

 ## Mikrotik Terminal
That's what Mikrotik shows with my Salicru UPS (Phoenix):

[user@identity] > system ups monitor numbers=0
 - on-line: yes
 - runtime-left: 1h32m11s
 - battery-charge: 100%
 - output-voltage: 230V
 - load: 3%
 - frequency: 50Hz
 - hid-self-test: no-test-initiated

## Links
Winbox UPS Screenshot: https://drive.google.com/file/d/1BGRCQd2z-hKqPQxszSXf1yMD8f9ElC0C/view?usp=sharing
Mikrotik UPS Wiki: https://wiki.mikrotik.com/wiki/Manual:System/UPS
Mikrotik UPS confluence: https://help.mikrotik.com/docs/display/RKB/Monitoring+UPS

**Comment by tomaae** [comment]
I got new UPS, but I just realized that non of my mikrotik devices have an usb port.

**Comment by ondras12345** [comment]
You should be able to install RouterOS in a virtual machine (https://mikrotik.com/download ; CD image) and test it for 24 hours without buying a license. Maybe you'd be able to test the UPS support that way.

**Comment by tomaae** [comment]
I have routeros instance installed in virtualbox, since I was adding support for non-mikrotik hardware.
I can give it a try on monday, not sure if I can route usb properly into VM tho. we see.

**Comment by tomaae** [comment]
No, virtualbox wont detect any usb on my PC. Even filter wont work.

**Comment by ondras12345** [comment]
Are you using GNU/Linux? If so, you need to be a member of the `vboxusers` group to be able to access USB ports.

**Comment by tomaae** [comment]
no, I'm using windows

**Comment by tomaae** [comment]
so I will be able to get RB2011 for a weekend next month. Hopefully that works.
Tho I wont be able to upgrade it or modify configuration, so it may get awkward.

**Comment by stuartwishart** [comment]
I was just about to request the same feature before I saw this open issue.

I'm happy to help with the testing or implementation (but would need some guidance)

**Comment by tomaae** [comment]
> I was just about to request the same feature before I saw this open issue.
> 
> I'm happy to help with the testing or implementation (but would need some guidance)

Thanks, output of these 2 commands would be helpful:
`/system/ups/print terse`
`/system/ups/monitor 0 once`

**Comment by stuartwishart** [comment]
**Output when on mains power:**
`/system/ups/print terse`
0    name=ups1 port=usbhid1 offline-time=10m min-runtime=5m alarm-setting=immediate model=Back-UPS XS 700U   FW:924.Z5 .I USB FW:Z5 serial=3B2037X63560 manufacture-date=2020-09-08 load=11% on-line=yes nominal-battery-voltage=12V 

`/system/ups/monitor 0 once`
on-line: yes
on-battery: no
rtc-running: no
runtime-left: 48m32s
battery-charge: 100%
battery-voltage: 13.6V
line-voltage: 240V
load: 10%
replace-battery: no
smart-boost: no
smart-trim: no
overload: no
low-battery: no
hid-self-test: no-test-initiated

**Output on battery back-up**
`/system/ups/print terse`
0    name=ups1 port=usbhid1 offline-time=10m min-runtime=5m alarm-setting=immediate model=Back-UPS XS 700U   FW:924.Z5 .I USB FW:Z5 serial=3B2037X63560 manufacture-date=2020-09-08 load=9% on-line=no nominal-battery-voltage=12V offline-after=8m57s 

`/system/ups/monitor 0 once`
on-line: no
on-battery: yes
rtc-running: no
runtime-left: 52m52s
offline-after: 8m54s
battery-charge: 96%
battery-voltage: 13.6V
line-voltage: 0V
load: 9%
replace-battery: no
smart-boost: no
smart-trim: no
overload: no
low-battery: no
hid-self-test: no-test-initiated

**Output on mains restoration:**
`/system/ups/monitor 0 once`
on-line: yes
on-battery: no
rtc-running: no
runtime-left: 46m36s
battery-charge: 96%
battery-voltage: 13.6V
line-voltage: 234V
load: 10%
replace-battery: no
smart-boost: no
smart-trim: no
overload: no
low-battery: no
hid-self-test: no-test-initiated

**Comment by tomaae** [comment]
this is perfect, thank you.

**Comment by ondras12345** [comment]
I just got my hands on a Windows 10 machine with an APC UPS connected by USB and installed virtualbox. I was able to select the UPS in the devices menu and pass it through to the VM. From there, I had to add it via `/system ups add name=apc-usb-test port=usbhid1`. I did not need to change anything in Windows aside from enabling virtualization in BIOS.
![image](https://user-images.githubusercontent.com/44524735/159327055-5532abfc-3c33-4958-b300-43449a557e9d.png)
So there must be something weird going on with your Windows machine if your USB devices menu is empty.
Please note that nothing appears in routeros automatically. No messages in log, nothing. You need to add the UPS manually once you've passed it through to the VM.

Output of the two commands looks just like stuartwishart's, so I don't think I need to post mine.

I know from experience that it is very helpful to have a working test environment at hand, so I hope you'll be able to fix your Windows / virtualbox setup.

**Comment by tomaae** [comment]
![image](https://user-images.githubusercontent.com/23486452/159330782-58ccf4e0-a143-420a-bd1b-621ca90a44f5.png)
Unfortunatly, nothing is shown there for me. It is difficult to say what is causing it.
But since I was promissed that RB2011 for a bit, I dont worry about it too much.

**Comment by tomaae** [comment]
![image](https://user-images.githubusercontent.com/23486452/176268070-3fc0dca2-2054-4255-9878-ae23cce6ab0c.png)
