### ISSUE TITLE
[Bug] None of the connected devices is listed as home on a RB4011iGS+RM

### ISSUE THREAD

**Issue by strasharo** [tomaae/homeassistant-mikrotik_router#148]
## Describe the issue
I’m running the integration on two HASS instances against two different models of the router. The one hooked against a RB952Ui-5ac2nD (HAP AC Lite) works fine, however the other which I attached to a RB4011iGS+RM router fails to detect which devices are currently online an lists all of them as not_home and have the disconnected icon, while at least ten of them are currently connected and have “bound” status in the DHCP leases page. What is the criteria the integration uses to determine if a device is at home or not, is the DHCP status sufficient or there’s something else used?

## How to reproduce the issue
1) Have an up to date version of HASS
2) Add the Mikrotik router integration via HACS
3) Configure it against a RB4011iGS+RM.
4) Observe the list of connected devices present by the integration.

## Expected behavior
Devices which are currently connected to the router should be shown as connected/home

## Screenshots
![image](https://user-images.githubusercontent.com/3337997/142471912-f9b0f7b1-27f4-4cc2-a11c-bb815d6a8949.png)

![image](https://user-images.githubusercontent.com/3337997/142471860-c5f13f0d-8c90-4b1f-8104-f41c228f115a.png)

![image](https://user-images.githubusercontent.com/3337997/142472069-d8327a07-a546-47e5-aec2-3df38b452304.png)

## Software versions
 - Home Assistant version:  2021.11.4
 - Mikrotik Router integration version: 1.7.2
 - Mikrotik Hardware: RB4011IGS+RM
 - RouterOS version: 6.49.1

## Traceback/Error logs
None

## Additional context
I have the same setup against RB952Ui-5ac2nD with the same software and it works fine there.

**Comment by tomaae** [comment]
its not related to router itself, I have same one without wifi.

anything in HA log? if not, you will have to run debug and see whats going on.

**Comment by strasharo** [comment]
Ah, my fault. Looks like I had a rather restrictive drop ICMP rule on input, which was causing the pings to fail:
![Screenshot at 2021-11-18 22-22-53](https://user-images.githubusercontent.com/3337997/142491091-70c673c3-3972-48ef-856e-c99a2569a57a.png)
Didn't know the integration was trying to ping them, thought it was relying on the DHCP presense. Bumping the logging level revealed the ping failures. Thanks a lot and sorry for the spam. :)

**Comment by tomaae** [comment]
No worries, it happens.
If does not rely on DHCP presence. DHCP is just one way of device discovery. it would not be very responsive and reliable way for presence :)
