### ISSUE TITLE
[Bug / Issue] Can't add integration after installation

### ISSUE THREAD

**Issue by DaaaDave** [tomaae/homeassistant-mikrotik_router#149]
## Describe the issue
After installing the integration through HACS I'm not able to add it under /config/integrations.
Only the HA integration ("Mikrotik") is listed.

I first tried version 1.7.2 and it did not work as described in this bug report.
The i tought i give version 1.7 a try and it did work.
Maybe the issue is just related with freshly installing the newest version?

## How to reproduce the issue
1. Installed the integration (version 1.7.2) through HACS
2. Restarted HA instance
2. Go To Settings -> Integrations
3. Click "Add Integration"
4. Search for "Mikrotik" or "Mikrotik Router"
5. don't find it .....

## Expected behavior

should pop up in the list i guess

## Screenshots

Installation

![image](https://user-images.githubusercontent.com/94188366/142662010-34ee19a7-2d56-49e0-a1bc-23c23f2b7aaf.png)

Searching for it

![image](https://user-images.githubusercontent.com/94188366/142661793-d983a6b5-f87a-4332-ab4a-9755de16d66a.png)

## Software versions

 - Home Assistant version: 2021.11.3
 - Mikrotik Router integration version: 1.7.2
 - Mikrotik Hardware: wAP 60G (2x)
 - RouterOS version: 6.49

## Additional context

I also tried to remove it and reinstall it, did not work either.

**Comment by DaaaDave** [comment]
Whilst installing version 1.7 made me able to configure it, it was not able to connect to my APs.

After updating to 1.7.2 the connection is working and all entities have been generated:

![image](https://user-images.githubusercontent.com/94188366/142664095-49655278-af1a-48e2-9375-433350516c2b.png)

**Comment by tomaae** [comment]
thats normal. you need to clear browser cache sometimes after installing any integration from HACS.

**Comment by DaaaDave** [comment]
damn it. thanks anyways.

maybe you can add it as note to the installation procedure

**Comment by tomaae** [comment]
yea, good idea
