### ISSUE TITLE
[Feature] Ability to track bandwidth usage with Kid Control in RouterOS 7+

### ISSUE THREAD

**Issue by ivanpavlina** [tomaae/homeassistant-mikrotik_router#155]
## Is your feature request related to a problem? Please describe.
 I'm always frustrated when [...] Mikrotik removes a feature that i use :P 

## Describe the solution you'd like
Accounting could theoreticaly be replaced with Kid Control, suggested by Mikrotik staff here - https://forum.mikrotik.com/viewtopic.php?t=177606
I looked a bit into new NetFlow feature but it seems like a huge overkill for simple bandwidth tracking.

## Additional context
This issue references #73, here I will track changes in upcoming Pull request for this feature.
I didn't start the developement yet, I finally got some breathing room from work so I am planning to start today with this feautre.

Initial testing through RouterOS CLI is promising, after adding a dummy "Kid" 
`/ip kid-control
add name=Monitor mon=0s-1d tue=0s-1d wed=0s-1d thu=0s-1d fri=0s-1d sat=0s-1d sun=0s-1d`

all devices are dynamically added and Mikrotik is starting to track Rate Up/Down, Bytes Up/Down.
```
[admin@MikroTikMain] /ip kid-control device> print detail
Flags: X - disabled, D - dynamic, B - blocked, L - limited, I - inactive 
 0 D  name="" mac-address=FF:FF:FF:FF:FF:FF user="" ip-address=192.168.88.254 activity="" rate-down=0bps rate-up=0bps bytes-down=12.6KiB bytes-up=0 idle-time=14s 

 1 D  name="test1" mac-address=AA:BB:CC:DD:EE:FF user="" ip-address=192.168.88.1 activity="xyz.org" rate-down=0bps rate-up=0bps bytes-down=478.1KiB 
      bytes-up=572.4KiB idle-time=2s 

 2 D  name="test2" mac-address=FF:EE:DD:CC:BB:AA user="" ip-address=192.168.88.2 activity="org,xyz" rate-down=0bps rate-up=0bps 
      bytes-down=13.8KiB bytes-up=10.3KiB idle-time=8s

...
```

Rate Up/Down is not viable, because it changes every second and shows only currenty used bandwidth, while this component polls data every 30 seconds by default (i think, I have set it to 15 seconds)
Bytes Up/Down tracks sum of bandwidth used so simple diff between previous and current values could be used.
We will lose packet count which was present in accounting but I belive that wasn't usefull to anyone.

**Comment by tomaae** [comment]
Adding label, so bots wont touch this issue.
I still have to test everything under last 7.1.1 release. Glad its finally out.

**Comment by ivanpavlina** [comment]
Draft pull request created, when you have the time check it out, everything works fine from my side on 6.9 and 7.1.1 (I needed to restart homeassistant after 7.1.1 upgrade because component still had the info that I am running 6.9)
Still need to write the docs, I will get on it.

And I wish you all the best in the new year :)

**Comment by tomaae** [comment]
Good point, we need to rerun async_hwinfo_update when router reboot is detected.
Moving get_system_resource as first query in async_update and adding a test should do it I think?

**Comment by tomaae** [comment]
@ivanpavlina do you think it would be possible to do the same for per interface traffic? right now it takes value at pool time.
Ideal would be avarage bandwidth since last pool. At least I think that is how you implemented device traffic.

**Comment by ivanpavlina** [comment]
Yeah, I just went through interface-traffic logic and I don't belive we get correct values there, `/interface/monitor-traffic` is called once, but that just returns interface traffic in that point of time, not aggregated.

Here's one idea - We could run blocking command on mikrotik which will spit out results after couple of seconds. Heres a little snippet

```
import librouteros
host = '192.168.88.1'
user = 'test'
password = 'test'
connection = librouteros.connect(host, user, password)

path = connection.path('/interface')
run = path("monitor-traffic", **{"interface": "lan", "duration": 5})
# <-   blocks 5 seconds   ->
print(tuple(run))
```
OUTPUT
```
({'name': 'lan', 'rx-packets-per-second': 53, 'rx-bits-per-second': 45096, 'fp-rx-packets-per-second': 0, 'fp-rx-bits-per-second': 0, 'rx-drops-per-second': 0, 'rx-errors-per-second': 0, 'tx-packets-per-second': 50, 'tx-bits-per-second': 239064, 'fp-tx-packets-per-second': 0, 'fp-tx-bits-per-second': 0, 'tx-drops-per-second': 0, 'tx-queue-drops-per-second': 0, 'tx-errors-per-second': 0, '.section': 0},
 {'name': 'lan', 'rx-packets-per-second': 253, 'rx-bits-per-second': 380632, 'fp-rx-packets-per-second': 0, 'fp-rx-bits-per-second': 0, 'rx-drops-per-second': 0, 'rx-errors-per-second': 0, 'tx-packets-per-second': 259, 'tx-bits-per-second': 589976, 'fp-tx-packets-per-second': 0, 'fp-tx-bits-per-second': 0, 'tx-drops-per-second': 0, 'tx-queue-drops-per-second': 0, 'tx-errors-per-second': 0, '.section': 1},
 {'name': 'lan', 'rx-packets-per-second': 109, 'rx-bits-per-second': 74808, 'fp-rx-packets-per-second': 0, 'fp-rx-bits-per-second': 0, 'rx-drops-per-second': 0, 'rx-errors-per-second': 0, 'tx-packets-per-second': 208, 'tx-bits-per-second': 521368, 'fp-tx-packets-per-second': 0, 'fp-tx-bits-per-second': 0, 'tx-drops-per-second': 0, 'tx-queue-drops-per-second': 0, 'tx-errors-per-second': 0, '.section': 2},
 {'name': 'lan', 'rx-packets-per-second': 15, 'rx-bits-per-second': 21176, 'fp-rx-packets-per-second': 0, 'fp-rx-bits-per-second': 0, 'rx-drops-per-second': 0, 'rx-errors-per-second': 0, 'tx-packets-per-second': 35, 'tx-bits-per-second': 94200, 'fp-tx-packets-per-second': 0, 'fp-tx-bits-per-second': 0, 'tx-drops-per-second': 0, 'tx-queue-drops-per-second': 0, 'tx-errors-per-second': 0, '.section': 3},
 {'name': 'lan', 'rx-packets-per-second': 54, 'rx-bits-per-second': 52504, 'fp-rx-packets-per-second': 0, 'fp-rx-bits-per-second': 0, 'rx-drops-per-second': 0, 'rx-errors-per-second': 0, 'tx-packets-per-second': 42, 'tx-bits-per-second': 232112, 'fp-tx-packets-per-second': 0, 'fp-tx-bits-per-second': 0, 'tx-drops-per-second': 0, 'tx-queue-drops-per-second': 0, 'tx-errors-per-second': 0, '.section': 4})
```

This could run asynchronously independant of actual integration logic to not block anything. From this we get current rx/tx for interface captured every second by mikrotik.



But... here's a simpler one, we could retrieve `tx-byte` and `rx-byte` from `/interface` , it contains sum of byte traffic on interface (I think it resets on reboot, not sure tho) and do the same logic as in `kid-control-devices` - keep last value, on next run just do subtraction of new value and old value and you get pretty acurate bandwidth tracking.

```
[admin@MikroTikMain] > /interface/print stats
Flags: D - DYNAMIC; R - RUNNING; S - SLAVE
Columns: NAME, RX-BYTE, TX-BYTE, RX-PACKET, TX-PACKET, RX-DROP, TX-DROP, TX-QUEUE-DROP, RX-ERROR, TX-ERROR
 #     NAME                             RX-BYTE            TX-BYTE      RX-PACKET      TX-PACKET  RX-DROP  TX-DROP  TX-QUEUE-DROP  RX-ERROR  TX-ERROR
...
14  R  lan                       54 994 074 636    468 259 100 207    221 666 368    393 023 923        0        0              0         0         0
```
after few seconds:
```
[admin@MikroTikMain] > /interface/print stats
Flags: D - DYNAMIC; R - RUNNING; S - SLAVE
Columns: NAME, RX-BYTE, TX-BYTE, RX-PACKET, TX-PACKET, RX-DROP, TX-DROP, TX-QUEUE-DROP, RX-ERROR, TX-ERROR
 #     NAME                             RX-BYTE            TX-BYTE      RX-PACKET      TX-PACKET  RX-DROP  TX-DROP  TX-QUEUE-DROP  RX-ERROR  TX-ERROR
...
14  R  lan                       54 994 402 569    468 264 542 460    221 669 375    393 029 455        0        0              0         0         0
```

**Comment by tomaae** [comment]
```
But... here's a simpler one, we could retrieve tx-byte and rx-byte from /interface , it contains sum of byte traffic on interface (I think it resets on reboot, not sure tho) and do the same logic as in kid-control-devices - keep last value, on next run just do subtraction of new value and old value and you get pretty acurate bandwidth tracking.
```
yea, I had in mind something like this. if someone resets it, its easy to detect and it would just mess up one reading which is no big deal.

**Comment by tomaae** [comment]
Didnt knew its possible to create issues from comments like this. so we can close this one as done.
It works great, I have been testing it today as I was redoing all sensors. 15 hours of work and still not completely done there, scared of starting switches :)

**Comment by tomaae** [comment]
I just realized its reporting everything as WAN devices, which is hardcoded. 
Was it intentional? if so, what was an idea behind it?

**Comment by ivanpavlina** [comment]
I didn't find a way to differentiate between lan and wan traffic with kid-control-devices, I don't think it is possible unfortunately. Did you have some issues with traffic monitoring because of this?

**Comment by tomaae** [comment]
No, no technical issues. But having WAN in name is confusing, since its not WAN traffic. 
If we cannot differentiate, no need to append LAN/WAN to sensor anymore. I will remove it before next release if you dont see any better way.
