### ISSUE TITLE
[Feature] Sensor Voltage

### ISSUE THREAD

**Issue by javilopezalarcon** [tomaae/homeassistant-mikrotik_router#156]
## Is your feature request related to a problem? Please describe.

I would like to be able to see the voltage with which mikrotik feeds

## Describe the solution you'd like

sensor.mikrotik_voltage

## Describe alternatives you've considered

I would like, as is the temperature sensor (/system/health) (which in routeros 7 still does not appear in home assistant) that the input voltage sensor appears

## Additional context

I have a mini-ups with which I feed the mikrotik router and with this in turn by poe, I feed an ap ubiquiti, I would like to monitor the voltage that mikrotik receives at all times to be able to automate its shutdown for example or detect failures in the ups

**Comment by javilopezalarcon** [comment]
v6.x: [/system health get voltage]
v7.x: [/system health get [find name=voltage] value]

making a script for voltage monitoring, I can get the voltage sensor, but it is not updated with each change I think ... I'll leave it here in case it would be useful as info to how the addon should work, I hope it helps you

:global "voltstatus"
:global "voltlaststatus"
:global "systemvolt" [/system health get [find name=voltage] value]
:local DeviceName [/system identity get name]

**Comment by tomaae** [comment]
Should be easy to add without additional queries even.
But in this case, isnt it better to monitor your UPS directly? I have been using NUT plugin for HA until my APC died recently. You will get much more useful data that way.

**Comment by javilopezalarcon** [comment]
> Should be easy to add without additional queries even.
> But in this case, isnt it better to monitor your UPS directly? I have been using NUT plugin for HA until my APC died recently. You will get much more useful data that way.

there is no "easy" integration, it is an ups with 18650 batteries that feeds the pi with 5vdc, router and ont at 12vdc and ubiquiti by poe at 48vdc I found it interesting to be able to have that data in the mikrotik integration…

the other option would be a voltage control at the ups output and monitor it with esphome

**Comment by tomaae** [comment]
Home made ups? interesting.
Well, I can add it in any case, there is no downside to this sensor.
Interesting that you managed to power unifi using mikrotik poe. I wanted to do that myself, but was not able to have unifi start up.

**Comment by javilopezalarcon** [comment]
> Home made ups? interesting.
> Well, I can add it in any case, there is no downside to this sensor.
> Interesting that you managed to power unifi using mikrotik poe. I wanted to do that myself, but was not able to have unifi start up.

Thnks!! 
It is not homemade because I needed a poe diet and it was difficult for me to do it, they sell it like that, already done (amazon) I have the mikrotik hex s, it has a poe output, I feed mikrotik with 24vdc from the ups and I use the poe output it has for a uap ac lr. the output poe of the ups, is at 48vdc, with that food a u6 lite

**Comment by tomaae** [comment]
added voltage sensor. its in diagnostic section.
