### ISSUE TITLE
[Feature]RouterOS 7 Stable support request + bugfix

### ISSUE THREAD

**Issue by feel2006** [tomaae/homeassistant-mikrotik_router#158]
Hello!
I use integration in HA.
I have 2 MikroTik devices. (RB3011 and WapAC)
While ROS was 6.49.2, I saw:
- CPU load
- Memory usage
- temperature
- uptime
- etc.

ROS 7.1 Stable came out 1 month ago, since then I only see the interface list, nothing else.

Please update!
Thanks

**Comment by tomaae** [comment]
can you try master?

**Comment by j0hnby** [comment]
Going to comment on this as are interested - master works with no logged errors - however, wan status and external IP show as unavailable, and when capturing port traffic info they show as "0"....

that might be user error (I have already granted the user being used to connect full access) - apologies if so!

**Comment by tomaae** [comment]
> Going to comment on this as are interested - master works with no logged errors - however, wan status and external IP show as unavailable, and when capturing port traffic info they show as "0"....
> 
> that might be user error (I have already granted the user being used to connect full access) - apologies if so!

That is not related to 7.1 compatibility. I can see IP on my external interface, so its most likely something specific. 
Open a new issue for this with as much info as possible and we can have a look.

**Comment by tomaae** [comment]
RB3011 system sensors confirmed working fine
