### ISSUE TITLE
[Bug] No Temperature Sensor (RB3011)

### ISSUE THREAD

**Issue by jjmuriel** [tomaae/homeassistant-mikrotik_router#160]
Hi,
After update a RB3011 from 6.49.X to 7.1 the Mikrotik Router lost the temperature sensor. There is a way to recover this sensor and add the voltage sensor @tomaae? Thanks.

## System Health

version | core-2021.12.10
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.0-10-amd64
arch | x86_64
timezone | America/Bogota

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.19.3
Stage | running
Available Repositories | 938
Downloaded Repositories | 30

</details>

```
[admin@MikroTik-RB3011] > /system health print
Columns: NAME, VALUE, TYPE
#  NAME         VALUE  TYPE
0  voltage      23.5   V   
1  temperature  37     C
```

**Comment by tomaae** [comment]
yes, I'm aware that health does not work on rb3011. just upgraded mine to 7.1 recently
just having issues with my dev env and didnt had time to look into it.
Currently I have no idea why, since routeros output looks the same as on 450g where I developed 7.1 compatibility originally.

**Comment by tomaae** [comment]
Turns out it was just some HACS hiccup. Once I reinstalled master, both temp and voltage sensors are working.

**Comment by jjmuriel** [comment]
Thank you @tomaae. I Reinstalled the integration and it's working fine.
