### ISSUE TITLE
Manual install

### ISSUE THREAD

**Issue by Szesi111** [tomaae/homeassistant-mikrotik_router#162]
How to install without HACS?

I downloaded it to a subdirectory in custom_components directory as usual.
HA does not recover the package after restarting HA.

thx

**Comment by tomaae** [comment]
thats all you need to do, no additional steps are needed

**Comment by ondras12345** [comment]
I too installed it manually and it works for me. Please show a listing of your `custom_components` directory with something like `tree`. Use `ls -l` to make sure the permission bits are set correctly.
