### ISSUE TITLE
RouterOS 7.1.1 - No traffic data on ports

### ISSUE THREAD

**Issue by j0hnby** [tomaae/homeassistant-mikrotik_router#163]
## Describe the issue
Port Traffic Sensors are turned on, ports are visible, but no traffic numbers are visible.

## How to reproduce the issue
No steps

## Expected behaviour
Some sort of traffic visible

## Screenshots
![image](https://user-images.githubusercontent.com/18377483/150572494-38a93e4e-1e8c-4f2a-9890-0ac07bc867f5.png)

## Software versions
 - Home Assistant version: 2021.12.10
 - Mikrotik Router integration version: 1.7.3
 - Mikrotik Hardware: CRS326-24G-2S+
 - RouterOS version: 7.1.1

## Traceback/Error logs
No errors reports in either HASS or RouterOS

**Comment by tomaae** [comment]
make sure you can see ether23 port in routeros. integration is not getting any information about it.
if you have all ports showing unavailable, integration is most likely not set up or cant connect. but you should see an error is HA log for this.

**Comment by j0hnby** [comment]
port visible in RoS
![image](https://user-images.githubusercontent.com/18377483/150577549-67669e72-efab-40f5-8c8d-054a17b633cf.png)
There are no errors for this integration in the log

**Comment by tomaae** [comment]
ok, run it in debug then. not sure what is happening.
also make sure that user you use have correct access rights.

**Comment by j0hnby** [comment]
Run in debug - since it contains sensitive data, where can I upload it it won't be public?

**Comment by tomaae** [comment]
You can mask them if you want. Otherwise, you can find my twitter in the profile. should be possible to send file using dm.
I dont really want to post my email here, because web crawlers will find it.

**Comment by j0hnby** [comment]
Sorry - please ignore this report.  Looking at the logs the data is there, it just doesn't sample the data frequently enough to catch the little peaks I see in WinBox where things don't download large amounts of data and fall in the 30 second refresh rate it misses it - I'll fiddle with the sampling rate/refresh rate to see if I can get it to show more.  Thanks for your responses though.

**Comment by j0hnby** [comment]
Closing as per previous comment

**Comment by tomaae** [comment]
I dont think thats the problem. Screenshot you posted is missing data that should be there and entity is restored. I dont think it is connecting to routeros at all.

**Comment by j0hnby** [comment]
OK - happy to reopen - attached are the logs[](url
[home-assistant.log](https://github.com/tomaae/homeassistant-mikrotik_router/files/7920561/home-assistant.log)
)

**Comment by tomaae** [comment]
Oh my. Its enough to set up debug as described in docu. No need to have full HA debug :) It just makes it difficult to go through.
Is it still not working tho? I dont see anything wrong.
What about other sensors? like system sensors. Also, which sensors do you have enabled?

**Comment by tomaae** [comment]
You should see these all the time:
![image](https://user-images.githubusercontent.com/23486452/150842105-740479a7-5d4d-44ca-980b-0abb3a0d6342.png)
Do they work?

**Comment by j0hnby** [comment]
Hey - Yeah, I see all of those, and I am now seeing traffic too, just not much of it compared to what I see in WinBox - would that be because it's sampling the traffic all the time in Winbox and here it's only 30 seconds?

![image](https://user-images.githubusercontent.com/18377483/150942459-8c5e5d32-22ef-449c-a962-24b93797562b.png)

I did have it on mbps, so changed it to kbps to show the smaller traffic amounts

Also, you mentioned having external IP earlier - I can't see that anywhere....

**Comment by tomaae** [comment]
Ok, I finally understand whats going on there. Those FRACTAL and Ubi interfaces are actually disabled, so they should be responding as disconnected. I just dont understand why it didnt showed attributes on interface.

Yes, its sampling every 30 seconds by default. you can increase it if you want, but dont go overboard.
To test if it works for you, just open a twitch stream or two and watch internet traffic. It should show several Mbps per stream.
Maybe it could be possible to show speed based on total interface transfer div by time since last check. Still, that would be still only average over sampling time duration.

You can see IP assigned on port in port attributes. You can use it in automations and templates.

**Comment by tomaae** [comment]
For traffic sampling, it should be possible. I opened #166 for it
