### ISSUE TITLE
[Feature] Ability to monitor/measure IPSEC tunnels

### ISSUE THREAD

**Issue by NordloSydost-Pajje** [tomaae/homeassistant-mikrotik_router#164]
## Is your feature request related to a problem? Please describe.
It would be nice to be able to monitor/measure the IPSEC tunnels one have on the Mikrotik

## Describe the solution you'd like
A similar solution to a standard nic monitoring/measure

**Comment by tomaae** [comment]
is it the same as #111 ?

**Comment by NordloSydost-Pajje** [comment]
it's simmilar but the S2S tunnels via IPSEC does not apperar as an interface.

**Comment by NordloSydost-Pajje** [comment]
Sure i can. What do tou need?

Mvh

Per-Åke Moberg, Nordlo Sydost

OBS: Detta mail är skickat från min telefon, därav kan enklare språk och felstavningar förekomma.

________________________________

**Comment by tomaae** [comment]
I know nothing about that module. So anything you have under ipsec setup, how clients are shown and such. Just mask your secret keys.
It will also help me set it up on my development devices for testing.

**Comment by NordloSydost-Pajje** [comment]
I will be home tomorrow after a business trip. Will check then

Mvh

Per-Åke Moberg, Nordlo Sydost

OBS: Detta mail är skickat från min telefon, därav kan enklare språk och felstavningar förekomma.

________________________________

**Comment by tomaae** [comment]
no rush, I'm currently entity parts of the integration to take advantage of all new HA features. it will take me some time before I get to new features.
