### ISSUE TITLE
[Feature] wifiwave2 support

### ISSUE THREAD

**Issue by ondrejbaranek** [tomaae/homeassistant-mikrotik_router#165]
## Is your feature request related to a problem? Please describe.

Mikrotik integration doesn't work for wifiwave2 interface that is optional replacement of wireless interface

## Describe the solution you'd like

Integration is able to monitor devices connected over wifiwave2 interface

## Describe alternatives you've considered

No alternative if using wifiwave2 interface

## Additional context

https://help.mikrotik.com/docs/display/ROS/WifiWave2

**Comment by tomaae** [comment]
Unfortunately, I dont own any of supported devices.
Only 3 devices are supported so far and non of them are too cheap or old enough for 2nd hand market to get just for development.

**Comment by tomaae** [comment]
Being worked on as part of #170

**Comment by tomaae** [comment]
Can you test current master?

**Comment by ondrejbaranek** [comment]
Looks good so far, i did just few quick tests, I will be able to test more next week.

**Comment by tomaae** [comment]
there is not much to it, you just should see wifi devices with wireless source.
it should work fine, but who knows.
