### ISSUE TITLE
Kids control buy Lan ip

### ISSUE THREAD

**Issue by Filipsons-K** [tomaae/homeassistant-mikrotik_router#168]
Hello, kids' control by mac address is a joke. You can generate a new mac address and use the internet.  How to use time limitations on router LAN ports to access the internet like kids control by mac address?

**Comment by tomaae** [comment]
This is not really related to integration.
But still, kid control is the correct answer. You can always use port security to lock down the interface to specific mac address.
If you have CRS, you can use standard mac learning and limiting. With other devices, there is always mac server and setting port in arp reply-only mode.
