### ISSUE TITLE
[Feature] Accounting information from Mikrotik

### ISSUE THREAD

**Issue by ivanpavlina** [tomaae/homeassistant-mikrotik_router#17]
Hey, I could start working on retrieving accounting information (/ip accounting) from Mikrotik and calculate TX/RX throughput per host for given interval.

I have something like that in my custom component [link](https://github.com/ivanpavlina/homeassistant-integration-routerboard).

Now, I created the component that it need predefined local networks (ex. 10.0.0.0/24) so it can know which IP address is considered local, so it can differentiate between local->wan (upload), wan->local (download) and local->local (local) traffic. This could be fixed with retrieving local addresses from (/ip address).

I have in mind creating a device called "Traffic" (?) and dynamically creating sensor as the local host is found in accounting information. This could enable monitoring real traffic per host. I know you have created traffic monitoring per interface, but I am working with small RB450G which is connected to a switch, so everything is connected on one Mikrotik interface :).

Also, this would be optional feature, in homeassistant integration page there would be check box to enable/disable this feature.

If you see this as notable feature I can start working on it, if not I think about creating AppDaemon app which would replace this (maybe the AppDaemon is the right path for this functionality, I'm not really sure tbh).

**Comment by tomaae** [comment]
It could be useful for sure. That way it should be possible to monitor devices connected over wifi or switches.
Is it only IP based or is it possible to base it on MAC address? MAC address would be best of course because of DHCP.

For this we would probably also need a small guide how to set it up in routeros.
We should probably call this device "Accounting" instead of "Traffic" internally and in the integration (device_info > name), so its clearly separated from per port traffic.

**Comment by ivanpavlina** [comment]
Device name "Accounting" would be smarter, i agree.

Yeah, accounting is IP based, it is returning Src. Address, Dst. Address, Packets (counter) and Bytes (counter)
MAC address for local hosts (which would be generated for sensors) could be retrieved from ARP List, every host should be present there and reference by IP address could be made.

**Comment by tomaae** [comment]
ah right, its easy to access arp and dhcp server for mikrotik.
yes, with that it should work great. it should also be possible to combine in mikrotik dns server entries for user friendly sensor names (this should be only accessed if the name is unknown to reduce queries).

**Comment by tomaae** [comment]
I got many good ideas for improvement from working with you on this, looks like I will be busy :)

Btw, was it easy to work with my code? Any suggestions for improvement to make it easier work work with it in future?

**Comment by tomaae** [comment]
Actually, hold on with changes. I just got some really good idea how to handle hosts.
I will commit them to master during the day. Also I will create data points I mentioned above, so you dont have to.

I will let you know here once its done :)

**Comment by ivanpavlina** [comment]
Wow sorry, totally missed this update :)

That nice to hear, I really want something to integrate my Mikrotiks in HA as much as possible ^^

As for the code, its nicely structured, don't know what I could suggest because it is written well and I got up and running really fast. Hope I can contribute some more in the future :)

**Comment by tomaae** [comment]
Thanks, I look forward to work with you on more improvements :)

**Comment by tomaae** [comment]
could you redo the accounting screenshot and save it as png when you have time? that jpg has artifacts.

**Comment by ivanpavlina** [comment]
#27 PR open

**Comment by tomaae** [comment]
thank you, now they look perfect side by side :)

**Comment by tomaae** [comment]
could you update to latest master and check if accounting is now grouped under hostnames and queues are together under "Queues" group?
I had to do some major changes in groups to have HA pair everything with other integrations.

**Comment by ivanpavlina** [comment]
Accounting sensors definitions in SENSOR_TYPES are missing definition for path
`ATTR_PATH: "accounting"`
so they get broken. I fixed that in my instance, but there are more problems.

Accounting sensors are ungrouped 
![accounting_ungrouped](https://user-images.githubusercontent.com/10489654/78979287-d53b7b00-7b1b-11ea-9851-fcd09ac3b0ea.PNG)

Device trackers show state "Unavailable" but the icon for connected/disconnected is okay
![msi](https://user-images.githubusercontent.com/10489654/78979309-e5ebf100-7b1b-11ea-9997-35146da9baca.PNG)

In integration groups I got new group for each connected host (Mikrotik {hostname}) , which only contain device tracker entity for that host.
![Capture](https://user-images.githubusercontent.com/10489654/78979361-01ef9280-7b1c-11ea-9a3f-0782701c2661.PNG)

And system, queues, NAT groups are renamed to Mikrotik system, Mikrotik queues, Mikrotik NAT..
Group Accounting is not present anymore.

**Comment by tomaae** [comment]
oh, I removed wrong attribute by mistake. 
try master now, they should be grouped under host name. if that device has both accounting and is tracked, you should see both tracker and accounting sensor grouped under it.

you have to enable device tracking in integration options. I added it yesterday.

**Comment by ivanpavlina** [comment]
Looks good now!

**Comment by tomaae** [comment]
I have now removed integration name prefix from tracked hosts and accounting sensors. That did not made much sense.
Now it should be in its final form.

**Comment by tomaae** [comment]
I have tried enabling accounting on my router, but it does not show correct values:
![image](https://user-images.githubusercontent.com/23486452/79078320-ee088400-7d07-11ea-93b6-6838c1273ac2.png)
WAN TX seems to be accurate, but RX is way off. I did not see anything obvious in code.

**Comment by ivanpavlina** [comment]
Hmm, I'll check it out, don't know if I'll manage to look at this until weekend tho. Will post findings here..

**Comment by tomaae** [comment]
thats fine, no worries about how long it takes. this is not a paid job you know :)

**Comment by ivanpavlina** [comment]
Sorry that this took so long.

So, i tested this from my side and accounting calculates everything right, i got real approximate TX and RX values for all devices. 
Now, there could be problem with set threshold in Mikrotik, this number sets maximum number of accounting entries that can are saved in Mikrotik's memory. If that number is too low and update interval is too high some packets wont be saved in accounting snapshot, which would lead to broken calculations.

Can you try to test it with mentioned PR and check if you get any warnings about accounting in logs?
Thanks

**Comment by tomaae** [comment]
No worries, I will try to test it later today.
I have it set to 8192 with 30 sec query time, so not sure. I dont think I have that much traffic, but we will see.

**Comment by ivanpavlina** [comment]
Hmm, yeah, thats the same configuration as mine.. If it isn't the threshold problem i don't have any idea why the calculations arent correct :/

**Comment by tomaae** [comment]
I figured it out, it is due to FastTrack.

```
FastTracked packets bypass firewall, connection tracking, simple queues, queue tree with parent=global, ip traffic-flow(restriction removed in 6.33), IP accounting, IPSec, hotspot universal client, VRF assignment, so it is up to administrator to make sure FastTrack does not interfere with other configuration;
```

**Comment by ivanpavlina** [comment]
Great :)

**Comment by tomaae** [comment]
I have updated the documentation so nobody gets confused.
Btw, I also made another integration recently which you may be interested in ;)

**Comment by ivanpavlina** [comment]
Are you talking about OMV integration? Yeah, i saw it, I was using OMV until a month ago but i switched to virtualized env and plain ubuntu servers. Good luck with it :)

**Comment by tomaae** [comment]
ah okey, I just seen that you had something with OMV :)
I have been using it for a long time as an easy to use debian solution.
Next integration will be for monitoring my linux based backup solution, but that will take some time to get to.
