### ISSUE TITLE
[Bug] RX/TX Usage Discrepancy

### ISSUE THREAD

**Issue by maretodoric** [tomaae/homeassistant-mikrotik_router#173]
## Describe the issue
When checking at data in home assistant for - example RX (Download) usage, i see discrepancy since nothing appears to be logged between 12AM and 8AM even though i have SpeedTest running on hourly basis and it's returning good values.
On the other hand, server that is performing the SpeedTest is in a bond interface, when checking it's values too , it's also not logged that that speed is being used on that port. My internet connection speed goes up to 120, in test results it goes up to 115 and yet Integration does not appear to show above 90Mbps for uplink port and not above 30 for bond0 itself.

## How to reproduce the issue
1. Run speedtest on a different machine
2. Speedtest json results pushed to Elasticsearch
3. Grafana returns ElasticSearch results and displays
4. Results displayed from Grafana differs from RX bandwidth usage displayed by MikroTik Integration

## Expected behavior
Same or similar result should be visible by MikroTik integration

## Screenshots
Screenshot showing usage for uplink port, mostly idle between 12AM to 8AM
![image](https://user-images.githubusercontent.com/65895223/152781526-b52f7b96-68a0-408e-ae65-8f153e772b49.png)

Screenshot below showing speedtest results on an hourly bases between same time period, i don't have any other uplinks so all had to go through the one above
![image](https://user-images.githubusercontent.com/65895223/152781875-e7c931c1-875f-4aaf-8d4c-e54a8ac57281.png)

bond0 interface where server performing speedtest is connected to
![image](https://user-images.githubusercontent.com/65895223/152784699-3546a43a-2f3e-4796-8ed0-f810e7c7bb5a.png)

## Software versions

 - Home Assistant version: core-2022.2.2
 - Mikrotik Router integration version: v1.8
 - Mikrotik Hardware: RBD52G-5HacD2HnD
 - RouterOS version: v6.49

## Traceback/Error logs
None

**Comment by tomaae** [comment]
Integration takes a state at time of a query (every 30 sec by default), so it depends on a transfer speed at that moment.
This will be changed to average between queries in the future #166

**Comment by maretodoric** [comment]
Awesome, thank you!
