### ISSUE TITLE
[Lokalise] Add new translations language

### ISSUE THREAD

**Issue by LeandroIssa** [tomaae/homeassistant-mikrotik_router#174]
I would like to ask you to add the Brazilian Portuguese translation in lokalise. Thanks.

**Comment by tomaae** [comment]
Hi,
I have added the language

**Comment by tomaae** [comment]
![image](https://user-images.githubusercontent.com/23486452/153453007-2bb9863a-f914-4442-887b-16aba247b47a.png)
It is there. Maybe you selected individual languages at the beginning and you need to show it?
Not sure how its done tho, I only have owner view which always shows everything.

**Comment by LeandroIssa** [comment]
Thanks for the feedback, how do I log out of the project and log back in? I believe that this is how Brazilian Portuguese can appear. In another project that I asked to add Brazilian Portuguese, the creator commented that he had to manually add me to the project. Is there an option for you?

**Comment by tomaae** [comment]
Found it and added it to you. Thanks :)

**Comment by LeandroIssa** [comment]
> Found it and added it to you. Thanks :)

Thank you so much, I already translated!
Brazilians thank you!

**Comment by tomaae** [comment]
thank you

**Comment by tomaae** [comment]
> > Found it and added it to you. Thanks :)
> 
> Thank you so much, I already translated! Brazilians thank you!

Could you please update the translation? I made few title and description changes to make configuration process more clear.
Thanks

**Comment by tomaae** [comment]
thanks :)
