### ISSUE TITLE
[Bug] No state_class: measurement on device rx/tx sensors

### ISSUE THREAD

**Issue by mvdwetering** [tomaae/homeassistant-mikrotik_router#175]
## Describe the issue

The rx/tx sensors for devices do not have a `state_class: measurement` assigned. This is the case for sensors for the ports like `ether1`

## How to reproduce the issue

Use the developer tools to look at the sensors. E.g. see attributes for my server

```
attribution: Data provided by Mikrotik
Address: 192.168.178.4
Mac address: 12:34:56:78:90:AB
Host name: MICHEL-SERVER
unit_of_measurement: Kbps
icon: mdi:download-network
friendly_name: MICHEL-SERVER LAN RX
```

## Expected behavior

A `state_class: measurement` assigned to the sensor like for the ports

```
state_class: measurement
attribution: Data provided by Mikrotik
unit_of_measurement: Kbps
icon: mdi:download-network-outline
friendly_name: RB4011iGS ether1 RX
```

## Screenshots

Not applicable

## Software versions
 - Home Assistant version: 2022.2.6
 - Mikrotik Router integration version: 1.8
 - Mikrotik Hardware: RB4011iGS+5HacQ2HnD
 - RouterOS version: 6.48.3 (stable)

## Traceback/Error logs

No errors

## Additional context

I was trying to get some insight into bandwith usage in my netowrk over time and wanted to use longterm statistics, but device rx/tx sensors are not showing up. I believe this is due to the missing stateclass on those sensors.

**Comment by tomaae** [comment]
Already implemented in 74b46ed5622d08abb7efad8881088ac1fac97d78
I dont recommend using master at this point tho.
