### ISSUE TITLE
install without HACS?

### ISSUE THREAD

**Issue by martinhanes** [tomaae/homeassistant-mikrotik_router#179]
Hi Tomaae, this HA integration looks awesome! It has tons of features, and I'd love to try and use it.

Is there a way how to install it without HACS?

I tried to copy the contents of custom_components into custom_components folder, found the integration in HA, but it coldn't be inited.

I got this error in the log:

`2022-02-28 17:50:41 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration mikrotik_router: No module named 'homeassistant.components.diagnostics'.`

I think it's HACS related, so I raised this ticket with hope you or anybody could help.

Thanks in advance and thanks for awesome work!

Martin

**Comment by tomaae** [comment]
No, you have old HA version. Master requires 2022.2
You can get older version and check hacs.json to confirm you meet requirements.

**Comment by martinhanes** [comment]
Thanks a lot! That did it. I've updated HA image to latest and the integration started working.

Thank you for your help.

Martin
