### ISSUE TITLE
[Bug] Comments containing only number causing split to fail

### ISSUE THREAD

**Issue by artpcpl** [tomaae/homeassistant-mikrotik_router#180]
## Describe the issue
Home assistant log is full of repeated messages:

<
Logger: homeassistant.config_entries
Source: custom_components/mikrotik_router/mikrotik_controller.py:1919
Integration: Mikrotik Router ([documentation](https://github.com/tomaae/homeassistant-mikrotik_router), [issues](https://github.com/tomaae/homeassistant-mikrotik_router/issues))
First occurred: 00:25:36 (1 occurrences)
Last logged: 00:25:36

Error setting up entry Mikrotik for mikrotik_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mikrotik_router/__init__.py", line 47, in async_setup_entry
    await controller.async_update()
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 614, in async_update
    await self.async_process_host()
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 1919, in async_process_host
    and self.data["dhcp"][uid]["comment"].split("#", 1)[0] != ""
AttributeError: 'int' object has no attribute 'split'

## How to reproduce the issue
1. Instal new version call me Setup error

## Software versions

 - Home Assistant version:  HA v2022.3.13 
 - Mikrotik Router integration version:   v2.0 
 - Mikrotik Hardware:  RB2011UiAS-2HnD 
 - RouterOS version:  e.g. v6.48.6

**Comment by tomaae** [comment]
What do you have in your DHCP server leases comments? Just a number?

**Comment by artpcpl** [comment]
![Screenshot - 05 03 2022 , 03_37_57](https://user-images.githubusercontent.com/51026569/156864707-b0478cff-4ca1-485b-bb1e-eac0f87fb074.png)
![Screenshot - 05 03 2022 , 03_37_28](https://user-images.githubusercontent.com/51026569/156864708-2b0381b9-0a17-4516-acff-ddbe32f021a8.png)
![Screenshot - 05 03 2022 , 03_37_06](https://user-images.githubusercontent.com/51026569/156864709-2081f355-7a3c-410c-8cd3-902f123e48cc.png)

**Comment by artpcpl** [comment]
Thanks for the tip, I simply removed the disabled IP addresses and blocked one. Now everything works. Greetings

**Comment by tomaae** [comment]
what exactly was causing it?

**Comment by artpcpl** [comment]
I think I turned off my IP address or I had "1" in my comment

**Comment by artpcpl** [comment]
![Screenshot - 05 03 2022 , 04_31_50](https://user-images.githubusercontent.com/51026569/156866111-20521d66-1a88-4839-9814-e4bb046dab15.png)
Now is OK

**Comment by tomaae** [comment]
empty comment is fine. if you just had "1" in comment, I see how it could happen. I will need to add sanitation for comments so this wont happen.

**Comment by artpcpl** [comment]
Good idea ```added the planned```
Anyway thanks
