### ISSUE TITLE
Cannot connect to Mikrotik.[Question]

### ISSUE THREAD

**Issue by gysos** [tomaae/homeassistant-mikrotik_router#182]
<img width="474" alt="image" src="https://user-images.githubusercontent.com/19389075/158026815-c16502c3-cd7d-47f8-8613-4fcf2ccdabf4.png">
<img width="333" alt="image" src="https://user-images.githubusercontent.com/19389075/158026849-6c35858c-9cf3-4ec4-8d9b-fd642ed39929.png">

why?

**Comment by tomaae** [comment]
Most likely API cannot be accessed.

**Comment by gysos** [comment]
> Most likely API cannot be accessed.

could u tell me how to fix it ? thx a lot!

**Comment by gysos** [comment]
> Most likely API cannot be accessed.

find it in Service configuration, thx

**Comment by tomaae** [comment]
can be pretty much anything. from disabled api to firewall/filters
