### ISSUE TITLE
[Bug] Hang with huge route table on ROS 7.1.3

### ISSUE THREAD

**Issue by bdn76** [tomaae/homeassistant-mikrotik_router#183]
## Describe the issue

Plugin hang on update route table with huge of entries (10000+). Work fine after:

```
        if self.api.connected():
            await self.hass.async_add_executor_job(self.get_system_health)

        #if self.api.connected():
        #    await self.hass.async_add_executor_job(self.get_route)

        if self.api.connected():
            await self.hass.async_add_executor_job(self.get_interface)
```

Consider move route table upload to config options.

## How to reproduce the issue

Connect plugin to ROS 7.1.3+ with huge routing table (BGP for example).

## Expected behavior

Do not sync routing table or make optional switch for route table load.

## Screenshots

I'm found large CPU consumption on tik device:

![image](https://user-images.githubusercontent.com/17513453/158056434-38170d3f-606c-44f7-8f4e-b94f64f54752.png)

After comment route table loading CPU utilization went down to normal.

## Software versions

All fields in this sections are required.
 - Home Assistant version: 2022.3.3
 - Mikrotik Router integration version: 2.0
 - Mikrotik Hardware: RBD52G-5HacD2HnD
 - RouterOS version: 7.1.3

**Comment by tomaae** [comment]
10000+ entries? I dont have an environment where I have something like that to test.
Did it really hang, or just took long?

**Comment by bdn76** [comment]
Yes.

![image](https://user-images.githubusercontent.com/17513453/158063759-6622b7f3-90a0-4fdd-9935-bc44fdb8c663.png)

Took long about 5-6 minutes.

**Comment by tomaae** [comment]
I'm not authorized to use BGP, so not sure how to test and workaround this issue at the moment.

**Comment by bdn76** [comment]
What about option for route load like this:

![image](https://user-images.githubusercontent.com/17513453/158065189-4a1c36e4-0196-44e8-8114-93d244c1c308.png)

?

**Comment by tomaae** [comment]
Not in this case, because of a way it is used. I may be able to find a way, since I only need to find an interface for default route. There may be more efficient way to do that.

**Comment by tomaae** [comment]
what will you get when you type this in cli?
` /ip route print terse where dst-address=0.0.0.0/0`

**Comment by bdn76** [comment]
```
[admin@router] > /ip route print terse where dst-address=0.0.0.0/0
   DAv   dst-address=0.0.0.0/0 routing-table=main pref-src="" gateway=pppoe-out1 immediate-gw=pppoe-out1 distance=10 scope=30 target-scope=10 suppress-hw-offload=no 
   D d   dst-address=0.0.0.0/0 routing-table=main pref-src="" gateway=192.168.8.1 immediate-gw=192.168.8.1%lte1 distance=20 scope=30 target-scope=10 vrf-interface=lte1 suppress-hw-offload=no 

[admin@router] > 
```

**Comment by tomaae** [comment]
Assuming lte1 is your default internet gateway, this works.
Was there any noticable load on router side with your setup?

This should show only default gateway interface.
`/ip route print terse where dst-address=0.0.0.0/0 and vrf-interface`

**Comment by bdn76** [comment]
> Assuming lte1 is your default internet gateway, this works. Was there any noticable load on router side with your setup?

No, default gw is pppoe (letter "A" in "DAv") - lte1 is backup (no letter "A" in "D d". CPU utilization without route table loading is around 1-2%.

> This should show only default gateway interface. `/ip route print terse where dst-address=0.0.0.0/0 and vrf-interface`

```
[admin@router] > /ip route print terse where dst-address=0.0.0.0/0 and vrf-interface
   D d   dst-address=0.0.0.0/0 routing-table=main pref-src="" gateway=192.168.8.1 immediate-gw=192.168.8.1%lte1 distance=20 scope=30 target-scope=10 vrf-interface=lte1 suppress-hw-offload=no
```

Incorrect.

**Comment by tomaae** [comment]
Hmm, this is tricky, since pppoe does not show interface.
I will have to research this further, since this is obviously correct way to approach gateway detection without causing high CPU load in cases such as yours.
I also have close to none experience with pppoe, which is a problem as well.

**Comment by tomaae** [comment]
hmm, but does it detect any devices behind pppoe interface? if not, this will be no-issue.

**Comment by bdn76** [comment]
This one:

```
[admin@router] > /interface print where name=pppoe-out1
Flags: R - RUNNING
Columns: NAME, TYPE, ACTUAL-MTU
 #   NAME        TYPE       ACTUAL-MTU
13 R pppoe-out1  pppoe-out        1492
[admin@router] > 
```

**Comment by tomaae** [comment]
what I mean is route output. 
but I just found this in different [documentation](https://help.mikrotik.com/docs/pages/viewpage.action?pageId=59965493)
<html>
<body>


immediate-gw (string) | Shows actual (resolved) gateway and interface that will be used for packet forwarding. Displayed in format [ip%interface].
-- | --



</body>
</html>
while not strictly true, since ip% is not present in your case, it could be useful. I just wish I had more complex setups to get this output from so I can be sure.

**Comment by tomaae** [comment]
it may actually not be possible. API library still accesses whole table even when limiting selection.
Not sure what to do here, I cant find any other way to find default gateway.
