### ISSUE TITLE
[Question] Show PPP IP address form PPP server (SSTP vpn)

### ISSUE THREAD

**Issue by iNaiks** [tomaae/homeassistant-mikrotik_router#184]
Hi, I've installed the addon and I can`t find the option to show the ip address given by the server to a sstp client.
Now i can se the "caller ID" (wan address) and other info, but I'm interested to see the "ip address" of the vpn.
![Addon INFO](https://user-images.githubusercontent.com/72868890/158334024-47ada0ff-3065-4b81-ac55-50258bb3e447.png)
![Mikrotik INFO](https://user-images.githubusercontent.com/72868890/158334030-375423b0-af11-482b-8d86-7b8ed8b0fa4d.png)

**Comment by tomaae** [comment]
can you give me one such output line from `/ppp active print terse`?

**Comment by iNaiks** [comment]
name=Casa XXXXX service=sstp caller-id=XXXXX address=10.1.1.111 uptime=3h19m4s encoding=AES256-CBC session-id=XXXXXX limit-bytes-in=0 limit-bytes-out=0

**Comment by tomaae** [comment]
Give master a try. You should now see local address too.
