### ISSUE TITLE
[Question] "Zone for device tracker" - meaning?

### ISSUE THREAD

**Issue by Scan4u** [tomaae/homeassistant-mikrotik_router#193]
Please advise the meaning for "Zone for device tracker" located in Settings - Basic config? Thank U!
<img width="684" alt="snap081" src="https://user-images.githubusercontent.com/16424225/163679707-edb06950-872f-4712-a00a-4d3af2e9954a.png">
.

**Comment by tomaae** [comment]
here you go: https://www.home-assistant.io/integrations/zone/

**Comment by Scan4u** [comment]
Understand, thank U! :) I looked for something totally different :) Will try to explain the issue in the separate post shortly.
