### ISSUE TITLE
[Bug] Device tracker on 2 sites having issues when devices moves between them

### ISSUE THREAD

**Issue by Scan4u** [tomaae/homeassistant-mikrotik_router#194]
## Describe the issue
I have two Mikrotik's in the different appartments, located far away one from another. They have different ISP's, both WAN's are white listed. Here is a simple diagram of my network:
<img width="878" alt="snap087" src="https://user-images.githubusercontent.com/16424225/163686861-845be7c4-82f0-4683-9d7b-a231b42f1b8f.png">
Also I have Synology NAS with Home Assistant (Docker) connected to Mikrotik №1 

The idea is to use your **homeassistant-mikrotik_router 2.0** integration to control wi-fi devices in both locations from one HomeAssistant server.

## How to reproduce the issue
The problem start when the person with **same phone** visited both locations. 
For example, the phone with android name "Vasyl" and Mikrotik friendly name "OnePlus6_24g" get the **device_tracker.vasyl_oneplus6_24g**  from the first Mikrotik №1. But, unfortunately, from the second Mikrotik №2 it get this error:
`**2022-04-16 20:56:55 ERROR (MainThread) [homeassistant.components.device_tracker] Platform mikrotik_router does not generate unique IDs. ID 11:22:33:44:55:66 already exists - ignoring device_tracker.vasyl_oneplus6_24g**`
Tha same situation is with other devices, which are used in both locations:
![snap086](https://user-images.githubusercontent.com/16424225/163687307-86791bb7-abcb-4fd4-bbc3-f1b79bc81eba.png)

## Expected behavior
It will be a good idea to add the prefix field option in the Settings - Basic options. Than, the device tracker for Vasyl from the Mikrotik №1 could look like "device_tracker.**mikrotik1**_vasyl_oneplus6_24g" and from the Mikrotik №2 - "device_tracker.**mikrotik2**_vasyl_oneplus6_24g". So there will be two different IDs for the same phone in the HomeAssistant, one for each appartment. 

Is it possible to fix this issue? Thank U!

## Software versions

 - Home Assistant version: 2022.4.4
 - Mikrotik Router integration version: 2.0
 - Mikrotik Hardware: 951G-2HnD
 - RouterOS version: 6.49.6

**Comment by tomaae** [comment]
I dont know right now. I have reached out to Frenck, maybe this is already solved elsewhere.

Adding instance name to tracker would just duplicate trackers, that is not a good solution.

**Comment by Scan4u** [comment]
> Adding instance name to tracker would just duplicate trackers, that is not a good solution

It seems that the number of the trackers should stay the same - they can just get the unique id-prefix in the name. 
This will help to avoid the mentioned error with non-unique IDs from few different Mikrotik's registered in one Home Assistant.

**Comment by tomaae** [comment]
I understand what you mean. I'm just looking for the best possible way to do it.
Already talking about it with Frenck (Home Assistant developer). Seems like other integrations may have same issue, we have just been looking at unifi integration.
So we may end up solving this issue globally or standardizing a solution for device trackers across Home Assistant.
Either way, its a win-win for everyone.
