### ISSUE TITLE
[Bug] Handle duplicate NAT entries

### ISSUE THREAD

**Issue by tomaae** [tomaae/homeassistant-mikrotik_router#20]
Check for duplicate NAT entries and disable them.

Check for a way to make entries more unique since there is no permanent unique ID available for NAT entry.

**Comment by tomeeka** [comment]
I have more rules for the same destination port from different interfaces and they are not showing up in the integration.

**Comment by tomaae** [comment]
yes, thats the correct behavior. all entities have to be unique, otherwise integration will crash

**Comment by tomeeka** [comment]
can you add comment from mikrotik or something to the name so the entity could be uniqe? or make an option for it?

![image](https://user-images.githubusercontent.com/41842441/79928875-755ea180-8444-11ea-8748-5bc05045c753.png)

**Comment by tomaae** [comment]
No, comment would not work. It’s something that have to be present during unit and it has to be universal. Also, it should be something that is unlikely to be changed by the user. 
Problem is that nat does not have any permanent unique id and there are so many options for nat.

**Comment by tomaae** [comment]
Btw, maybe you could go around it by specifying all protocols for port on one of those rules. If it is possible in your environment.

**Comment by tomeeka** [comment]
I understand your concerns, but I think this is a very special case. Maybe some flag or tag in the comments that your integration can use. For example: 

> [ha_id=natrule_x] This is a NAT rule for x interface only.
to specify the id manually...

Or

> [ha_hide]
to hide a rule from your integration...
Manipulating unique internal HA ids are not for average users, but I think average users will not use multiple nat rules or even mikrotik routers. ;)
This is just my idea, maybe this is the wrong way, but I do not see any better one. But I will accept if you do not agree with me. :)

**Comment by tomaae** [comment]
that could be a workable idea for nat exceptions. probably not easy to implement with current logic , I will have to think about it.
