### ISSUE TITLE
[Question] trigger on dhcp leases

### ISSUE THREAD

**Issue by SamJongenelen** [tomaae/homeassistant-mikrotik_router#201]
Hey, using this component has been great!

Now, I would like to know when a device connects to my network. Ideally i want to create a notification for any new device (once per mac) what IP it has received and hostname, etc. This could be a blueprint or something, i dont know yet.

Also, kind of seperate but related, i would like to be able to see all dhcp leases IP, mac, leased time etc. So i can have a nice overview.

Is one of these options possible? Currently my HA devices do not have IPs (or i cant find it). How would i go about it

**Comment by tomaae** [comment]
All tracked devices have address attribute, which is IP address. You can use that if needed.
You can filter by source attribute "dhcp" if you only want those.
You could use new "for" type for automations here to go through all tracked devices and filter active DHCP ones.
Everything except lease time is available via integration.

**Comment by SamJongenelen** [comment]
Yeah, I think the for solution could work, however i was hoping this addon could help me do it. I was surprised noone has made this feature already :) 
Unfortunately im not able to code it, but maybe i can make a blueprint. 

Thanks!

**Comment by SamJongenelen** [comment]
So I ended up using an HA automation, with the following action:


`service: notify.mobile_app_sm_g973f
data:
  title: 'devie added to network: {{state_attr(trigger.event.data.entity_id,"host_name")}}'
  message: 'HOST: {{state_attr(trigger.event.data.entity_id,"host_name")}} with IP {{state_attr(trigger.event.data.entity_id,"ip")}} was added to the network'
`

**Comment by tomaae** [comment]
good work, that should work with all device trackers
