### ISSUE TITLE
[Feature] Improve device_tracker.last_seen attribute to be easier on the DB

### ISSUE THREAD

**Issue by clau-bucur** [tomaae/homeassistant-mikrotik_router#203]
## Is your feature request related to a problem? Please describe.

The current implementation of the "**last seen**" attribute generates alot of unnecessary events, and, if the device_tracker is included in the recorder (stored to DB) this will generate huge data, even for devices that have 0 activity.
This because the "**last seen**" attribute is dynamic and changes every second, even if the device does not change state.
This change leads to recorder storing the changed attributes.

## Describe the solution you'd like

I have made a small change to **device_tracker.extra_state_attributes** so that last_seen will show the last date an unavailable device was seen. _This attrbute would be omitted for available devices._
This approach drastically reduces the state changes of device_trackers, thus the impact on the recorder.

```
def extra_state_attributes(self) -> Dict[str, Any]:
        """Return the state attributes."""
        attributes = super().extra_state_attributes

        last_seen_key = format_attribute("last-seen")
        if not self.is_connected:
            if self._data["last-seen"]:
                attributes[last_seen_key] = self._data["last-seen"] #get_age(self._data["last-seen"])
            else:
                attributes[last_seen_key] = "unknown"
        elif last_seen_key in attributes:
            del attributes[last_seen_key]

        return attributes
```

## Additional context

Here is some data for my device trackers with the original implementation, for a 1 day span:
![device_tracker_original_1DAY](https://user-images.githubusercontent.com/47672949/169296608-5b407b6c-0315-4541-b824-7b2e7fa3704b.jpg)

Here is some data for my device trackers with my implementation, for a 5 day span:
![device_tracker_changed_5DAYS](https://user-images.githubusercontent.com/47672949/169296753-92eceeb9-da3c-4d7e-8fad-2740d2b76290.jpg)

All devices are very stable and do not get disconnected. Only overnight some are powered down, otherwise all are stable. The environment was the same for both above cases.

Another info, actually which lead me to find this out:
My DB size was at abou 6.6GB so I investigated the reason. I found out that the bulk of the state changes were due to device_trackers.
I then proceeded and purged device_tracker domain which lead to a 3-time decrease in size, to 2,1.GB.
This is huge!

I can create a PR if you'd like me to.
Thank you!

**Comment by clau-bucur** [comment]
Another recommandation would be related to the formatting of some of the device_tracker attributes, like: Interface, Source, and Last seen.
They don't follow the Snake Case formatting of the vast majority of sensors I've seen in HA.
Not sure if this is a requirement though, I've not seen any spec on it.

**Comment by tomaae** [comment]
can you check description to those 2 screenshots? it does not add up, so I guess its wrong.

If it is behaving like that, changing it is a good idea. But more is required there, just removing get_age should not give you correct time.

extra attributes are not formatted, they are directly from mikrotik. Formatting them would give us wrong information after all.

**Comment by clau-bucur** [comment]
> can you check description to those 2 screenshots? it does not add up, so I guess its wrong.
Yeah! I made a mistake on the second screenshot description, I rectified it now.
Second screenshot is with my proposed change.

> 
> If it is behaving like that, changing it is a good idea. But more is required there, just removing get_age should not give you correct time.
The change is more than just removing the "get_age".
It's actually adding an "last seen" attribute only for device_tracker entities which are not reachable (not home).
That way the "last seen" attribute is only set once at the moment the entity becomes unavailable and for the duration of unavailability this attribute would not change.

Once the device_tracker becomes available again, the "last seen" attribute is deleted (no need to know last seen for online devices) and will not trigger any updates as long as the device remains online.

Here's a diff of the function
![image](https://user-images.githubusercontent.com/47672949/169369289-f700b857-534f-44ef-b4d5-a75d55e65a3d.png)

> 
> extra attributes are not formatted, they are directly from mikrotik. Formatting them would give us wrong information after all.
Actually you are formatting them, as far as I understand the code:

```
if self._data["last-seen"]:
    attributes[format_attribute("last-seen")] = get_age(self._data["last-seen"])
else:
    attributes[format_attribute("last-seen")] = "unknown"

"""Helper functions for Mikrotik Router."""
# ---------------------------
#   format_attribute
# ---------------------------
def format_attribute(attr):
    res = attr.replace("-", " ")
    res = res.capitalize()
    res = res.replace(" ip ", " IP ")
    res = res.replace(" mac ", " MAC ")
    res = res.replace(" mtu", " MTU")
    res = res.replace("Sfp", "SFP")
    res = res.replace("Poe", "POE")
    res = res.replace(" tx", " TX")
    res = res.replace(" rx", " RX")
    return res

```

**Comment by tomaae** [comment]
Ok, now it makes sense and really should be changed.
Implementation needs to be different, but I will take care about it. I know what to do here.

We dont want to delete attribute, that will just cause issue for people who template it. I'm talking really bad HA log spam. Changing it to a word "Now" or "Available makes more sense.

I went through my home HA and you are right. snake case makes sense since there it auto capitalization. I hate to lose proper casing for abbreviations, but I rather go with "not documented standard".

**Comment by tomaae** [comment]
splitting these up, since they are not related. dont want to miss it

**Comment by tomaae** [comment]
should be done. could you test how this impacts DB size?

**Comment by clau-bucur** [comment]
Thanks! Will use master release and get back in a few days with the stats from DB.

**Comment by tomaae** [comment]
thanks

**Comment by clau-bucur** [comment]
All good. After more than a day of operation the results are as expected:
![image](https://user-images.githubusercontent.com/47672949/170689070-cee172db-ad64-48a4-b6fd-bae85429e64d.png)

Thank you @tomaae

**Comment by tomaae** [comment]
thank you for detailed analysis and testing, been a pleasure :)
