### ISSUE TITLE
HA 2022.6.0 warning

### ISSUE THREAD

**Issue by sagitt** [tomaae/homeassistant-mikrotik_router#209]
## Describe the issue
Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for mikrotik_router using this method at custom_components/mikrotik_router/mikrotik_controller.py, line 443: registry = await self.hass.helpers.entity_registry.async_get_registry()

I hope this help you :)

**Comment by MackoMici** [comment]
+1

**Comment by jjmuriel** [comment]
same here

**Comment by tomaae** [comment]
everyone will have it. I have not yet updated to new version, since I always wait for .1
this warning is nothing to worry about, everything should work like it was for now.

**Comment by hellcry37** [comment]
```txt
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 11 June 2022 at 22:39:55 (1 occurrences)
Last logged: 11 June 2022 at 22:39:55

Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for mikrotik_router using this method at custom_components/mikrotik_router/mikrotik_controller.py, line 443: registry = await self.hass.helpers.entity_registry.async_get_registry()
```
Same for me
