### ISSUE TITLE
[Feature] Add sensors for total tx/rx bytes

### ISSUE THREAD

**Issue by mvdwetering** [tomaae/homeassistant-mikrotik_router#210]
## Is your feature request related to a problem? Please describe.

No, not a problem. I am trying to setup a dashboard in HA to monitor my internet usage data per day/month/year.

## Describe the solution you'd like

Add sensors like the current ones for rx/tx rate, but then for the total amount of bytes with the 'total_increasing' setting so it works with statistics. The values from line "Tx/Rx Bytes" in Webfig screenshot.

![image](https://user-images.githubusercontent.com/732514/172048944-b1b5dfd7-f72a-47e7-a2dc-35245fd433bc.png)

## Describe alternatives you've considered

I looked around a bit, but did not find anything that seemed relatively simple and could integrate with HA in some way. Most solutions seemed aimed at big corporate networks, I am just monitoring my home network.
If I missed something or if there are easier ways to do it let me know.

## Additional context

Nothing more to add.

**Comment by tomaae** [comment]
I have to check if this is possible, since total in mikrotik is can be reset any time by user and not sure if it resets on its own.

**Comment by mvdwetering** [comment]
Thanks for looking into it.

I think resetting should not be an issue if the sensor is marked as "total_increasing". Then the statistics processing in HA can figure it out. 

At least that is how I understand that works from https://developers.home-assistant.io/docs/core/entity/sensor#entities-representing-a-total-amount .  The examples are focused on Energy but I see no reason why it would not work for other types of values.

**Comment by tomaae** [comment]
true, it should work like that.
no problem then
