### ISSUE TITLE
[Bug] kilo prefix should be lower case

### ISSUE THREAD

**Issue by mvdwetering** [tomaae/homeassistant-mikrotik_router#211]
## Describe the issue

The units that have the kiloprefix should be in lowercase "k" instead of uppercase "K".

## How to reproduce the issue

In the integration configuration settings or values of sensors, there is "Kbps" or "KB/s" instead of "kbps" or "kB/s"

## Expected behavior

Lowercase "k" instead of uppercase "K"

## Software versions

 - Home Assistant version: HA 2022.5.5
 - Mikrotik Router integration version: master 817ecaa8c119c53873db87020dc862f0ea356eb7 which has the fix for #199
 - Mikrotik Hardware: RB4011iGS+5HacQ2HnD
 - RouterOS version: 7.2.1

## Traceback/Error logs

No errors

**Comment by tomaae** [comment]
Thats actually a good point worth researching.
Not sure if mikrotik returns binary or decimal using API.
k = binary kilobyte
K = decimal kilobyte

decimal is normally used to measure bandwidth, so uppercase should be correct. But in case of API, not sure.

**Comment by mvdwetering** [comment]
Ah, I did not know about the big "K", I only knew "k" and "Ki"

Looking into it a bit more and what I gather from Wikipedia [kilo](https://en.wikipedia.org/wiki/Kilo-) and [binary prefix](https://en.wikipedia.org/wiki/Binary_prefix)

k = decimal
Ki (for kibi) = binary (apparently K was used in the past as it is mentioned as Legacy, guess it was renamed to avoid confusion like I had :) )

Home Assistant seems to use/prefer(?) the "Ki" variant as there is a `DATA_KIBIBYTES: Final = "KiB"` and `DATA_RATE_KIBIBYTES_PER_SECOND: Final = "KiB/s"`

**Comment by tomaae** [comment]
yea, decimal is still used in bandwidth. but storage is more commonly in binary now.
winbox uses lowercase for rate, uppercase for total. so something is wrong there.
