### ISSUE TITLE
[Bug] Detected integration that uses deprecated `async_get_registry`

### ISSUE THREAD

**Issue by piio** [tomaae/homeassistant-mikrotik_router#216]
## Describe the issue
Hi,

In newest version of Home Assistant async_get_registry is deprecated (I guess from 2022.6.0)

Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for mikrotik_router using this method at custom_components/mikrotik_router/mikrotik_controller.py, line 443: registry = await self.hass.helpers.entity_registry.async_get_registry()

## How to reproduce the issue

1. Go to Upgrade HA to 2022.6.0+
2. Check in logs that HA is warning about deprecation of async_get_registry

## Expected behavior
No warning in log

## Software versions
 - Home Assistant version: 2022.7.0
 - Mikrotik Router integration version: 2.0

## Traceback/Error logs
Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for mikrotik_router using this method at custom_components/mikrotik_router/mikrotik_controller.py, line 443: registry = await self.hass.helpers.entity_registry.async_get_registry()

**Comment by tomaae** [comment]
already solved in master
