### ISSUE TITLE
[Feature] Sensor for Route List

### ISSUE THREAD

**Issue by GregoryKowalik** [tomaae/homeassistant-mikrotik_router#218]
## Is your feature request related to a problem? Please describe.
Not really, I don't see any problems related to this feature

## Describe the solution you'd like
It would be great to have additional sensors for each Routing in Route list to see whether specific route is active, static, dynamic, connected and if it's enabled or disabled.

## Describe alternatives you've considered
No alternatives considered.

## Additional context
My case it that I would like to check through which route/gateway my internet connection is routed which means for me whether I'm on primary internet connection or backup.

Many thanks
Greg

**Comment by tomaae** [comment]
Roadmap is to move away from touching routes completely.
In your use case, there should be better ways to determine which route is in use. In worst case, you can always use script end environment values.

**Comment by GregoryKowalik** [comment]
Thanks for quick response. I'd love to know other ways. Thanks for your hint. I will give it a try. In the meantime I'm using simple command traceroute (not related to Mikrotik integration) in HA and based on the output I determine the route but it's not so elegant and fast as it could be.

Thanks
Greg
