### ISSUE TITLE
[Bug]Detected integration that uses deprecated `async_get_registry` to access entity registry

### ISSUE THREAD

**Issue by khaisilk1910** [tomaae/homeassistant-mikrotik_router#221]
Plesase fix that.
Many thank!

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 3:10:19 PM (1 occurrences)
Last logged: 3:10:19 PM

Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for mikrotik_router using this method at custom_components/mikrotik_router/mikrotik_controller.py, line 443: registry = await self.hass.helpers.entity_registry.async_get_registry()

**Comment by tomaae** [comment]
already fixed in #209
