### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by M0DDer** [tomaae/homeassistant-mikrotik_router#222]
## Describe the issue

Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for mikrotik_router using this method at custom_components/mikrotik_router/mikrotik_controller.py, line 443: registry = await self.hass.helpers.entity_registry.async_get_registry()

## Software versions

 - Home Assistant version: HA 2022.7.3

**Comment by tomaae** [comment]
already fixed in master
