### ISSUE TITLE
[Bug]`Detected integration that uses deprecated `async_get_registry`

### ISSUE THREAD

**Issue by khaisilk1910** [tomaae/homeassistant-mikrotik_router#223]
Please fix error bellow:
`Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for mikrotik_router using this method at custom_components/mikrotik_router/mikrotik_controller.py, line 443: registry = await self.hass.helpers.entity_registry.async_get_registry()`

**
> Home Assistant 2022.7.5
> Supervisor 2022.07.0
> Operating System 8.2
> Frontend 20220707.1 - latest**

**Comment by tomaae** [comment]
already fixed in master
