### ISSUE TITLE
[Feature] Use update entity for firmware updates

### ISSUE THREAD

**Issue by icecom-dg** [tomaae/homeassistant-mikrotik_router#229]
Home Assistant 2022.4 introduced [update entities](https://developers.home-assistant.io/docs/core/entity/update/). It would be nice to use them instead of a binary sensor and to allow triggering an upgrade from Home Assistant.

A bit later I can develop the feature myself and create a PR if you'd like.

**Comment by tomaae** [comment]
yea, I actually only noticed it on friday when my unifi update showed up there. I guess its not commonly implemented in integrations.
I certainly want this to be part of all my integrations.

**Comment by icecom-dg** [comment]
There should be two update entities, actually: one for RouterOS and another one for RouterBOARD firmware upgrade.

Also there's the question of how to handle rebooting. I propose rebooting automatically for the upgrade by default, but allowing to disable reboots when configuring the integration. It would be nice to have a service that reboots the router.

**Comment by tomaae** [comment]
without reboot, you wont get router updated. so that does not make sense. also everywhere I seen this, it will reboot/reload device to apply the firmware

**Comment by tomaae** [comment]
There we go
![image](https://user-images.githubusercontent.com/23486452/184118099-cee81be8-1be3-484b-94a7-8c99544fa409.png)

**Comment by tomaae** [comment]
that should cover it :)

**Comment by Xitro01** [comment]
This is awesome, but the binary sensor stopped working that was showing if there was an update or not. It now shows up as unavailable.

**Comment by tomaae** [comment]
> This is awesome, but the binary sensor stopped working that was showing if there was an update or not. It now shows up as unavailable.

Can you reword it please?

**Comment by Xitro01** [comment]
> > This is awesome, but the binary sensor stopped working that was showing if there was an update or not. It now shows up as unavailable.
> 
> Can you reword it please?
> 
> Also, check if there is any error in HA log.

The binary_sensor.mikrotik_firmware_update is now unavailable since you added the 2 update sensors. I used this in my dashboard logic to show if there was a firmware update or not.

I don’t see any messages regarding this in my logs.

**Comment by tomaae** [comment]
ah, you mean old binary sensor. yea, that has been replaced by new update sensor.
you can use new update sensors in dashboard too, but they show up as alerts, so its not really necessery. thats up to you.

**Comment by Xitro01** [comment]
> ah, you mean old binary sensor. yea, that has been replaced by new update sensor.
> you can use new update sensors in dashboard too, but they show up as alerts, so its not really necessery. thats up to you.

My main use of this, is to show a “1” in a red circle to show that there is an update on my dashboard (which I show on my tablet without the menu’s). But I will just remove the old entity and use these instead. Thanks!
