### ISSUE TITLE
[Bug] uses deprecated `async_get_registry`

### ISSUE THREAD

**Issue by gelokatil** [tomaae/homeassistant-mikrotik_router#231]
## Describe the issue

Home-Assistant gives the following warning when loading the component

Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom integration author for mikrotik_router using this method at custom_components/mikrotik_router/mikrotik_controller.py, line 443: registry = await self.hass.helpers.entity_registry.async_get_registry()

## How to reproduce the issue

Initial load the component

## Software versions

 - Home Assistant version:  2022.8.4
 - Mikrotik Router integration version:  v2.0.0 (latest) 
 - Mikrotik Hardware: < RBcAPGi-5acD2nD (cAP ac)  
 - RouterOS version:  7.2 (stable)

**Comment by tomaae** [comment]
already solved in master

**Comment by gelokatil** [comment]
thanks
