### ISSUE TITLE
[Question] Not all mangle rules are seen

### ISSUE THREAD

**Issue by dvoijen** [tomaae/homeassistant-mikrotik_router#232]
I use a "mark routing" mangle rule, this is not shown.

**Comment by tomaae** [comment]
Only jump and dynamic mangle rules are skipped. So most likely unique id conflict. Did you looked into your HA log?

**Comment by dvoijen** [comment]
Tomaae, no no duplicate but i think i know what the issue is.
I have 2 mangle rules that are the almost same.
The only difference is the acrion and the comment.
![Knipsel](https://user-images.githubusercontent.com/28559228/184511111-e4e7a0e3-2286-47ac-a1a9-1c51d6816f8b.PNG)
See the att.
The next att is what i see in HA:
![Knipsel2](https://user-images.githubusercontent.com/28559228/184511164-08ea19bb-bc3a-4304-89d4-ece9df65215b.PNG)

**Comment by tomaae** [comment]
not necessery. if you dont see any message in ha log, I will need to see debugs

**Comment by dvoijen** [comment]
As soon as i change one of them and set as destination 0.0.0.0/0 it works, it sees them both.
If i than set the other also to 0.0.0.0/0 as destination theb oth are gone (greyed out).

**Comment by tomaae** [comment]
then you certainly have duplicate warning in HA log

**Comment by dvoijen** [comment]
Yes only 1: 2022-08-13 22:49:39.370 ERROR (SyncWorker_3) [custom_components.mikrotik_router.mikrotik_controller] Mikrotik <IP DEDACTED> duplicate Mangle rule mark-routing,any:any, entity will be unavailable.
But that was a test rule i deleted this moring.

**Comment by dvoijen** [comment]
Tomaae, you are right..... sorry!!!
When i set them to the same i indeed see this error.
Now i have distinguished them by setting one of the with a destination of 0.0.0.0/0 and the other blank, works for me.

**Comment by tomaae** [comment]
yes, sometimes its necessery to add dummy rules to it to make them unique
