### ISSUE TITLE
[Bug] Wrong RouterOS Version detected

### ISSUE THREAD

**Issue by benedikt-bartscher** [tomaae/homeassistant-mikrotik_router#234]
Hey there, i just updated to v2.1 and got notifications for every switch:
![image](https://user-images.githubusercontent.com/31854409/184732750-5f979520-7ebf-4d87-8c2b-d5b1091e8c0b.png)
However they are all on 7.4.1 already.

**Comment by tomaae** [comment]
Thats not RouterOS, but RouterBOARD firmware. Its different thing.
See System>RouterBoard
![image](https://user-images.githubusercontent.com/23486452/184733745-2e0290c5-b0f5-4523-992d-0611756d488f.png)

**Comment by benedikt-bartscher** [comment]
i am sorry, it was too late for me yesterday. Thanks for clarifying!
