### ISSUE TITLE
[Question] Maybe add renaming of attributes to breaking changes?

### ISSUE THREAD

**Issue by mvdwetering** [tomaae/homeassistant-mikrotik_router#238]
Hi, 

I just installed the 2.1.1 update and read the release notes for 2.1 and 2.1.1 (as I was coming from 2.0)

After the update I noticed some cards did not show correctly anymore. It took me a while to figure out and it turns out this is due to the `snake_casing` of attributes (which is a nice change). 

While this change is mentioned in the release notes I think it is a breaking change (it breaks stuff that referenced those attributes) and it would be nice if it could be in the breaking changes section of the 2.1 release.

**Comment by tomaae** [comment]
good point. I have added it
