### ISSUE TITLE
Update to 2.1.1 mikrotik logfile full of api connect/disconnect messages started [Bug]

### ISSUE THREAD

**Issue by BluThunder2k** [tomaae/homeassistant-mikrotik_router#239]
## Describe the issue
I updated to the latest of the HACS Mikrotik add on 2.1.1 and now my router log is flooded with API user logged in and logged out messages every time it polls the router.

## How to reproduce the issue
Watch logfile on device being monitored by the add on.      Tried adding a switch as well, same behaviour.

## Expected behavior
Previous behavior of just one connection per starting of HA.
![Capture](https://user-images.githubusercontent.com/104277923/185810708-34a451ee-8d30-459b-9b83-69a0a5dce032.PNG)

## Software versions

 - Home Assistant version: HA 2022.8.6
 - Mikrotik Router integration version: 2.1.1 
 - Mikrotik Hardware: CCR1009-7G-1C 
 - RouterOS version: v7.4.1

**Comment by tomaae** [comment]
look into ha log to see why it is happening

**Comment by BluThunder2k** [comment]
Ah ha.

This error originated from a custom integration.

Logger: custom_components.mikrotik_router.mikrotikapi
Source: custom_components/mikrotik_router/mikrotikapi.py:299
Integration: Mikrotik Router (documentation, issues)
First occurred: 4:55:00 PM (153 occurrences)
Last logged: 5:02:51 PM

Mikrotik 192.168.0.2 error while execute : not enough permissions (9)



Sent from my iPhone.  Sorry for any typos!

On Aug 21, 2022, at 5:08 PM, Tomaae ***@***.***> wrote:

﻿

look into ha log to see why it is happening

**Comment by tomaae** [comment]
ok, you dont have sufficient access rights for the user you are using.
if it is a mistake, fix it based on docu. in case you want to have lower access right and dont mind limited functionality, you can install master.
