### ISSUE TITLE
[Feature] Host device tracking

### ISSUE THREAD

**Issue by tjorim** [tomaae/homeassistant-mikrotik_router#24]
I'm always frustrated when connection errors happen, this is mostly because of the library (librouteros) used. This integration does a fine job managing its own version of the library. However, the component in HA itself (which provides device tracking) does not. It would be awesome if your integration can handle this as well. 

**Describe the solution you'd like**
The custom mikrotik router integration can do device tracking. 

**Describe alternatives you've considered**
Try to fix the official mikrotik integration. 

**Additional context**
There is currently an issue with entities disappearing when devices are offline on HA restart, instead of being marked away.

**Comment by tomaae** [comment]
What would you want to track exactly? I'm always for expanding the functionality.

entities are disappearing? I seen them go to "unavailable" status when I restarted or disconnected routers during my testing. This issue could warrant opening new bug issue and describe how and when they disappear for you.

**Comment by tjorim** [comment]
I want to track which network devices are currently connected to the (MikroTik) network. This is actually the only platform the official integration supports but doesn't handle everything that well.

Regarding the 'unavailable' entities, I meant with the official integration: https://github.com/home-assistant/core/issues/31757

**Comment by tomaae** [comment]
We could use arp table and arp ping for network connection tracking. Not sure you had something like that in mind.
It is already partially implemented, integration can detect ip and mac addresses connected to each port, including bridges. It displays "multiple" when there is switch or ap is connected to a port, but thats only because a long list would mess up UI looks. All data are already there.
We could have separate category for client tracking in the integration and possibly resolve DNS entries and mikrotik comments for name, tracking them based on mac address, so DHCP would not mess up things.
Is that what you would find useful?

Hmm, I guess official integration have disconnection problems and crashes.

**Comment by tjorim** [comment]
Yeah, partly what I want but wireless devices as well. With that I could track smartphones and tablets from people to know if they're home or not (but again, currently just using official for now).

**Comment by tomaae** [comment]
I use Unifi for wifi since mikrotik was never reliable for me. But yeah, I can see my phone and all devices connected to wifi in mikrotik arp list. So it is possible to track all devices in network independently on what wifi you are using.
I like the idea, should not be too difficult to implement.

**Comment by tomaae** [comment]
![image](https://user-images.githubusercontent.com/23486452/78621291-9212ab00-7882-11ea-9578-8453557b4b06.png)
I have added preliminary support for host tracking based on DHCP leases. We may want to add more sources tho.
I have noticed my phone flip flops, but other devices like ESP are always as "Home". We may have to add some kind of grace period or different workaround.
I checked how it looks device does not respond to ping every time when it is in "sleep mode" (locked and display is off).

If you want to help testing it, you can update to master.

**Comment by tomaae** [comment]
I did a major update for host tracking:
* all devices from arp are now tracked (as a side effect, it can track gateway device, such as modem :) )
* hostnames are now resolved in this order (DNS, DHCP mikrotik comment(useful for reserved DHCP addresses), DHCP hostname, MAC address)
* entities no longer have integration name appended at the beginning
* last seen now shows time since last detection instead of last DHCP query

I did not touched availability timeout yet

**Comment by tomaae** [comment]
host device tracker will no longer change to unavailable.
also, IP and interface automatically will now update in case it changes.

there is still lot of work left on this feature.

**Comment by vampywiz17** [comment]
Hello @tomaae 

I use Mikrotik only AP, not router. It possible to use CAPsMAN to discover connected wifi devices?

use `/caps-man registration-table print` command. 

Now i use built-in Mikrotik integration on HA, but it bugged (the disconnected devices will be unknown, if restart HA)

**Comment by tomaae** [comment]
> 
> 
> Hello @tomaae
> 
> I use Mikrotik only AP, not router. It possible to use CAPsMAN to discover connected wifi devices?
> 
> use `/caps-man registration-table print` command.
> 
> Now i use built-in Mikrotik integration on HA, but it bugged (the disconnected devices will be unknown, if restart HA)

wont they show up with this integration?
I own cAP ac, but I never got it to work reliably. I mostly use it now for development and testing.
If you can send me output from `/caps-man registration-table print detail` I can have a look. You can mask mac addresses and IP's
Keep in mind that host device tracking is only available in master and it is not finished yet.

**Comment by vampywiz17** [comment]
@tomaae 

Sure i send a output.

![image](https://user-images.githubusercontent.com/14281430/78929140-20b14300-7aa2-11ea-92d1-65c180b4166b.png)


I think, with presence detection, the registration-table is better, with ARP. With ARP, sometime need 5-10 min, to recognise the disconnection. With above command, it happen almost same time.

**Comment by tomaae** [comment]
oh certainly. I already mark the source, so they can be handled differently.
does `/interface wireless registration-table print detail` work for you? I could use that output as well

**Comment by vampywiz17** [comment]
@tomaae 

Yes, it work well, but it add empty lines, that the CAPsMAN is enabled. (it normal) Now i can not disable CAPsMAN (it is a production enviroment). but the output look similar.

**Comment by tomaae** [comment]
if capsman part of wireless package now?

**Comment by tomaae** [comment]
implemented both caps-man and wireless.
I just went by data you provided and documentation, unfortunately I have no way of testing it.

**Comment by vampywiz17** [comment]
i installed the latest master repo, but it not parse the clients, only the interfaces script and system.

**Comment by tomaae** [comment]
did you enabled tracking for network devices?

**Comment by vampywiz17** [comment]
@tomaae 

Yes it is the problem, i forget it... Now i see the devices in "devices" menu, but i can not able to pair it to a person.

**Comment by tomaae** [comment]
I'm not sure what you mean

**Comment by vampywiz17** [comment]
Yes. I see the devices on device list:

![image](https://user-images.githubusercontent.com/14281430/78947282-38e68980-7ac5-11ea-9790-a5051944fd11.png)


But not in person:

![image](https://user-images.githubusercontent.com/14281430/78947216-148aad00-7ac5-11ea-9be8-4ecab3ee1e0f.png)

**Comment by vampywiz17** [comment]
Some log errors:

```
2020-04-10 00:38:51 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up mikrotik_router platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/mikrotik_router/device_tracker.py", line 99, in async_setup_entry
    update_controller()
  File "/config/custom_components/mikrotik_router/device_tracker.py", line 91, in update_controller
    update_items(inst, config_entry, mikrotik_controller, async_add_entities, tracked)
  File "/config/custom_components/mikrotik_router/device_tracker.py", line 124, in update_items
    tracked[item_id].async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 447, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 290, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity 98:D8:63:0D:4A:CA: home>
2020-04-10 00:39:14 ERROR (MainThread) [homeassistant.util.logging] Exception in update_controller when dispatching 'mikrotik_router-update-Mikrotik': ()
Traceback (most recent call last):
  File "/config/custom_components/mikrotik_router/device_tracker.py", line 91, in update_controller
    update_items(inst, config_entry, mikrotik_controller, async_add_entities, tracked)
  File "/config/custom_components/mikrotik_router/device_tracker.py", line 124, in update_items
    tracked[item_id].async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 447, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 290, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity Mikrotik ether1: home>
```

**Comment by tomaae** [comment]
hmm @tjorim reported this error earlier too. I dont have it tho.
can you run it in debug?

**Comment by vampywiz17** [comment]
```
2020-04-10 01:05:05 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up mikrotik_router platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/mikrotik_router/device_tracker.py", line 99, in async_setup_entry
    update_controller()
  File "/config/custom_components/mikrotik_router/device_tracker.py", line 91, in update_controller
    update_items(inst, config_entry, mikrotik_controller, async_add_entities, tracked)
  File "/config/custom_components/mikrotik_router/device_tracker.py", line 124, in update_items
    tracked[item_id].async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 447, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 290, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity 98:D8:63:0D:4A:CA: home>
```

```
2020-04-10 01:06:29 ERROR (MainThread) [homeassistant.util.logging] Exception in update_controller when dispatching 'mikrotik_router-update-Mikrotik': ()
Traceback (most recent call last):
  File "/config/custom_components/mikrotik_router/device_tracker.py", line 91, in update_controller
    update_items(inst, config_entry, mikrotik_controller, async_add_entities, tracked)
  File "/config/custom_components/mikrotik_router/device_tracker.py", line 124, in update_items
    tracked[item_id].async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 447, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 290, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity Mikrotik ether1: home>

```

Thats all i cand found.

**Comment by tomaae** [comment]
I managed to reproduce it. It occurs when there is restored client connected to wifi when HA is restarted

**Comment by tomaae** [comment]
fixed

**Comment by tomaae** [comment]
integration will need to be re-added to make latest changes work correctly.

**Comment by vampywiz17** [comment]
I installed it and seems to be OK! Home/Avay status is working, i see the MACs on "person" tab. I already tested , what will happen if i restart HA if my state is away and it remeber it! 

Great work @tomaae  ! Now your integration work better (the tracking part) that the official one!

(and of cousre your integration do much more, not only tracking!)

**Comment by tomaae** [comment]
I'm glad to hear that. There are still many internal changes needed, specially to reduce number of api queries.
I think host tracking is now feature complete.

**Comment by tjorim** [comment]
Agreed, closing issue! 🚀

**Comment by kuradi** [comment]
guys, as i understand mikrotik tracking only wifi devices? possible to track also wired clients? i have some cameras attached which now showing "not_home" all the time

**Comment by tomaae** [comment]
it does track wired devices. make sure you enabled tracking in integration options

**Comment by kuradi** [comment]
> it does track wired devices. make sure you enabled tracking in integration options

i have tracking enabled. but i found in ha log those lines:

```
2020-04-12 01:19:20 ERROR (SyncWorker_8) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.1.2 error while arp_ping : unknown
2020-04-12 01:19:21 ERROR (SyncWorker_5) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.1.2 error while building list for path : unknown
```
what does it means and how to fix it?

**Comment by tomaae** [comment]
thats some kind of unhandled error while communicating with mikrotik.
make sure you have latest versions (1.5.1), enable debug and capture the issue.
also, please open new issue for it. this one is to add the functionality and is already closed.

**Comment by tjorim** [comment]
First thing that comes to mind is that you didn't give the required permissions. Check that first (it's socument normally) and open a new issue otherwise.
