### ISSUE TITLE
Very frequent checking for updates

### ISSUE THREAD

**Issue by pe1chl** [tomaae/homeassistant-mikrotik_router#241]
I am not a homeassistant user and I have zero details about the actual setup the user uses, but I noticed this behavior elsewhere in the network:
A user with a MikroTik WiFi link monitors his device using this add-on for homeassistant, and now their MikroTik device is contacting the MikroTik update server every 30 seconds to retrieve the latest version and changelog.
I don't know if this 30 seconds is the overall polling interval or is configured in some other way (specific for the update).
However, I think it should not check for new updates more than say every 8 hours.  Probably not even more than once a couple of days.

**Comment by tomaae** [comment]
That is not a normal behavior. Something like this would happen if integration kept being reitialized due to crash or disconnect.

**Comment by pe1chl** [comment]
Ok thank you!  As I said, I have no insight in actual configuration but the user told me they had disabled some things and from then on it stopped.
Maybe when you are working on the code you could add some "last time checked" and minimal interval for re-check...

**Comment by tomaae** [comment]
that already exists. but when there is an issue, it will always reinitialize fully, including check for update.
changelog frequency is out of my hands, but that is something you wont see in router access logs.
Any kind of troubleshooting has to be done by HA instance owner, we cant se whats going on from router side.
