### ISSUE TITLE
[Bug] missing 'test' permission from Setup Integration section

### ISSUE THREAD

**Issue by mvdwetering** [tomaae/homeassistant-mikrotik_router#244]
## Describe the issue

I noticed in the logs it mentioned that the integration was running in limited mode because the user on the router did not have enough permissions.

To fix it I looked at the Setup Integration section and updated the permissions to "read, write, api, reboot, policy" as described.
After rebooting HA I got the following lines in the logs.

>Mikrotik 192.168.178.9 error while arp_ping : not enough permissions (9)

I remembered that I removed the 'test' permission that I had enabled before, so I put that back and after a HA reboot the messages went away.

## How to reproduce the issue

Update HA user permissions on the router to _not_ have 'test'

## Expected behavior

Documentation covers all permissions

## Screenshots

n.a.

## Software versions

 - Home Assistant version: HA 2022.8.7
 - Mikrotik Router integration version: v2.1.2
 - Mikrotik Hardware: RB4011iGS+
 - RouterOS version: v7.4.1

## Traceback/Error logs

This error originated from a custom integration.

Logger: custom_components.mikrotik_router.mikrotikapi
Source: custom_components/mikrotik_router/mikrotikapi.py:375
Integration: Mikrotik Router (documentation, issues)
First occurred: 20:53:02 (19 occurrences)
Last logged: 20:53:02

Mikrotik 192.168.178.9 error while arp_ping : not enough permissions (9)

**Comment by tomaae** [comment]
thanks, I removed if because I could not figure out what it was for. no idea how I missed arp ping
