### ISSUE TITLE
No IP Address for VLAN Interface (WAN ISP)

### ISSUE THREAD

**Issue by anthonws** [tomaae/homeassistant-mikrotik_router#246]
Home Assistant 2022.9.3
Frontend 20220907.1

Mikrotik Integration v2.1.2

**Issue**: No IP Address shown for eth1.12 (VLAN).
**When**: Since I recall using your Mikrotik integration (regardless of ROS version)

![image](https://user-images.githubusercontent.com/181357/190138863-951748e5-edf8-49af-9628-1bcd618ef004.png)

Diagnostic info in attach.
[config_entry-mikrotik_router-85315a00b966715243eb2fd06170c3d5.json.txt](https://github.com/tomaae/homeassistant-mikrotik_router/files/9565735/config_entry-mikrotik_router-85315a00b966715243eb2fd06170c3d5.json.txt)

ARP Address for the Interface exists.
![image](https://user-images.githubusercontent.com/181357/190138634-7ab26119-3216-4b73-b069-08e5146f6051.png)

Thanks!

**Comment by tomaae** [comment]
I will need debugs to see what is going on there.
