### ISSUE TITLE
[Feature] publish library to pypi

### ISSUE THREAD

**Issue by tjorim** [tomaae/homeassistant-mikrotik_router#25]
You do a fine job modifying and tuning the librouteros library. If one day this integration becomes official, it would need to be published to pypi. 

**Describe the solution you'd like**
Either contribute back the improvements to the original librouteros (unlikely because there would be breaking changes AFAIK) or publish your own fork.

**Describe alternatives you've considered**
NA

**Comment by tomaae** [comment]
what do you mean by publishing the library to pypi?

I'm not sure about changes I did to librouteros. That would require newer version and would create a conflict with HA mikrotik wifi integration. I plan to still try to get it work with 3.0.0, but I'm not sure it will work out.

I would like to offer this integration to HA, but first it needs to be perfect. That may take some time.

**Comment by tjorim** [comment]
I meant for you to create a fork of it, change the name (e.g. `aiolibrouteros`) and publish it like that to pypi. Then we have a custom component but the requirement is an other library (name) than the official MikroTik integration.

**Comment by tomaae** [comment]
is it necessary? right now it is not used as a library, but as part of the integration. So there is no conflict with any installed libraries.

**Comment by tjorim** [comment]
Not right now but it will be before it can become official (and who knows, maybe others want to improve the possible new library as well).

**Comment by tomaae** [comment]
I have created pull request for librouteros which fixes that crash on socket recv.
no matter which route we go, they should have that fix :)

**Comment by tomaae** [comment]
Looks like its stable with official library.
Seems like changes we did in api wrapper can now deal with those issues.

**Comment by tjorim** [comment]
Great to hear!
