### ISSUE TITLE
HA 2022.10.0 - user does not have sufficient access rights

### ISSUE THREAD

**Issue by SAOPP** [tomaae/homeassistant-mikrotik_router#250]
Hi there!

After upgrading of HA to 2022.10.0 got this warning:

`Mikrotik user homeassistant does not have sufficient access rights. Integration functionality will be limited.`

...but, I dind't changed anything and have all needed permissions for user from day one.

Here is user and groups of routeros:

![image](https://user-images.githubusercontent.com/5647009/194342018-4e39b00f-32d6-47fc-a01c-c1e5bb4ac537.png)
![image](https://user-images.githubusercontent.com/5647009/194342044-9a931882-c266-425c-b5cc-fde4ffbd0379.png)

Why this warning is pop up?

**Comment by tomaae** [comment]
this is not related to HA upgrade, but integration update.
there is additional functionality that requires additional access rights. you dont have to grant it it you dont want, its up to you.
in your case, I think you just wont see firmware and os update sensors. one more will be missing right now, but thats a bug which will be fixed in next release.

see doc for permission info https://github.com/tomaae/homeassistant-mikrotik_router#setup-integration

**Comment by SAOPP** [comment]
I did't say that this was due to the HA update, I only emphasized that there was no such warning before this update. Regarding the sensors, yes you are right, these sensors have become unavailable now.

Why should I look in the permissions documentation? Has anything changed there lately? I showed the screenshots - they look identical with the necessary.

**Comment by SAOPP** [comment]
Well, before creating a issue, I checked if there were any discrepancies with the recommended rights for the user, and making sure that everything was up to date with me, I decided to ask the question anyway. In general, we are waiting for updates?

**Comment by tomaae** [comment]
Well, you are missing "reboot" rights for full functionality.
If you mean health sensors bug, then yes, that will be in next update. But I dont plan to work on it anytime soon as its a minor thing and it works fine with full permissions.

**Comment by SAOPP** [comment]
God damn it, I swear I didn't see it, damn, oh maaaan :disappointed: Stupid things. Sorry for the issue, can't believe, why I skipped reboot permission, and in during my comparison actually. Weird sh...t. Sorry once again buddy, maybe hard day I don't know...

**Comment by tomaae** [comment]
dont worry about it, such thing happen. and after all, no harm done ;)
