### ISSUE TITLE
[Help] WDS sensors

### ISSUE THREAD

**Issue by daoudeddy** [tomaae/homeassistant-mikrotik_router#251]
Hello, thanks for the amazing Mikrotik integration.

Im using this integration to monitor my Mikrotik remote base stations, but the problem i’m having is that hundreds of WDS devices are being added into the integration automatically.

My question: is there any way to stop adding such devices automatically?

Here’s a screenshot describing what I’m talking about:
![C86D2528-24DB-4E62-B9F7-19CFF71E808B](https://user-images.githubusercontent.com/7020760/194800139-7b44365a-dae4-467b-bc6d-293e2ee656f5.jpeg)

**Comment by tomaae** [comment]
What are those? Do you actually have hundreds of RB912UAG devices?

**Comment by daoudeddy** [comment]
> What are those? Do you actually have hundreds of RB912UAG devices?

I’m monitoring my base stations health, voltage, temp, boot time etc… and there are many clients connected to these base stations.

**Comment by tomaae** [comment]
Yes, but are those wds actually real mikrotik devices?

**Comment by daoudeddy** [comment]
> Yes, but are those wds actually real mikrotik devices?

i really don’t know what specifically are these wds ports

**Comment by tomaae** [comment]
can you upload diagnostics?

**Comment by daoudeddy** [comment]
> can you upload diagnostics?

sure, here you go.
[compressed.zip](https://github.com/tomaae/homeassistant-mikrotik_router/files/9752260/compressed.zip)

**Comment by tomaae** [comment]
I dont see any references to those devices in diagnostics you provided. is it different integration instance?

**Comment by daoudeddy** [comment]
Yes it’s different, i have multiple base stations that i need to monitor, and the one in the screenshot is different from the one i sent you the diagnostics from, but all are doing the same.
For the moment can you at least tell which line of the code is responsible of adding such devices? its causing the integration to lag sometimes, so i can be disabled temporarily.

**Comment by tomaae** [comment]
so they are all devices you added. I dont understand what is the problem then.
you will need to show me your setup in more detail

**Comment by daoudeddy** [comment]
Would you mind if I submitted a pull request with the new added option to enabled or disable interfaces tracking?

**Comment by tomaae** [comment]
That part is kind of essential, so I dont plan to remove those defaults. If you dont want them, you can always disable them in HA.
