### ISSUE TITLE
Update Notifications always on

### ISSUE THREAD

**Issue by khaisilk1910** [tomaae/homeassistant-mikrotik_router#252]
![image](https://user-images.githubusercontent.com/3167468/195738881-715a8e01-3107-4af1-9281-491abe915aa0.png)
![image](https://user-images.githubusercontent.com/3167468/195743533-61c2e453-fc92-40c6-a485-bd4c298ab177.png)

**Comment by tomaae** [comment]
and what is the issue?

**Comment by khaisilk1910** [comment]
> and what is the issue?

Why it always show in Settings?
is that not bug?

**Comment by ndauphin** [comment]
I can confirm, this has been an issue for the past few releases. Home Assistant RB integration reports that a new version of RB firmware is available, when the RB is already on that firmware.

**Comment by ndauphin** [comment]
<img width="311" alt="Screen Shot 2022-10-13 at 11 37 24 PM" src="https://user-images.githubusercontent.com/73488426/195763732-f53cca32-2a9a-4971-8b0d-e1ff67073590.png">
<img width="572" alt="Screen Shot 2022-10-13 at 11 38 21 PM" src="https://user-images.githubusercontent.com/73488426/195763738-2231612f-837b-4097-a2c0-4353790b199b.png">

**Comment by tomaae** [comment]
do not confuse routeros and routerboard firmware. those are different things

**Comment by gumileeev** [comment]
> ![image](https://user-images.githubusercontent.com/3167468/195738881-715a8e01-3107-4af1-9281-491abe915aa0.png) ![image](https://user-images.githubusercontent.com/3167468/195743533-61c2e453-fc92-40c6-a485-bd4c298ab177.png)

Your routerBOARD is not updated, it is updated from another location
![image](https://user-images.githubusercontent.com/39103834/196826936-eb60f30b-d35f-4704-a1f0-5292b08b421a.png)
