### ISSUE TITLE
[Bug] No kid control device found - even though not integrating it, getting error in log

### ISSUE THREAD

**Issue by daman7cz** [tomaae/homeassistant-mikrotik_router#253]
## Describe the issue
Hello, even though I am not integrating Kid Control features (I have the Kid Control switch off at the Inegration Settings - see the first screenshot (sorry it is in local language, but nevertheless it is visible)), I am getting error in the log stating:
2022-10-15 03:10:02.641 ERROR (SyncWorker_3) [custom_components.mikrotik_router.mikrotik_controller] No kid control devices found on your Mikrotik device, make sure kid-control feature is configured (see the second screenshot)

## Expected behavior
When not integrating Kid Control, I would expect it doesn't care if I have it set or not on the Mikrotik device.

## Screenshots
![image](https://user-images.githubusercontent.com/84605450/195962665-5e5982cd-aaaf-4dc7-9811-f007a18780bb.png)
![image](https://user-images.githubusercontent.com/84605450/195962706-ea0d733c-14b5-4f1c-9249-ddc095ea09aa.png)

## Software versions
 - Home Assistant version: 2022.10.3
 - Mikrotik Router integration version: Latest
 - Mikrotik Hardware: RBD52G (hap ac^2)
 - RouterOS version: 7.5

**Comment by tomaae** [comment]
No problem, I'm fluent in czech.
This has nothing to do with kid-control, but client traffic. See documentation https://github.com/tomaae/homeassistant-mikrotik_router#client-traffic-for-routeros-v7
