### ISSUE TITLE
[Bug] Device trackers all disabled

### ISSUE THREAD

**Issue by markturner** [tomaae/homeassistant-mikrotik_router#256]
## Describe the issue
All device tracker entities are "disabled by integration"

## How to reproduce the issue
Go to the entities list and see the entities are all disabled

## Expected behavior
Entities should not be disabled and should update their status accurately

## Screenshots
<img width="593" alt="Screenshot 2022-10-28 at 11 11 57" src="https://user-images.githubusercontent.com/11614/198563657-680d5d0f-8079-4c2a-88d7-0c78090f7a87.png">
<img width="1444" alt="Screenshot 2022-10-28 at 11 11 30" src="https://user-images.githubusercontent.com/11614/198563661-dc4026b9-4b91-4efa-9de5-41e5c2fae683.png">

## Software versions

 - Home Assistant version: 2022.10.5
 - Mikrotik Router integration version: v2.1.2
 - Mikrotik Hardware: RB960PGS
 - RouterOS version: v6.47.9

**Comment by tomaae** [comment]
entities you are refering to are not provided by this integration.

**Comment by markturner** [comment]
Sorry can you explain that a bit more clearly? The interface suggests they are, so where should I be looking?

**Comment by markturner** [comment]
Right, I see there is a core integration also and that’s what I’m using. Apologies, I found the right one and that seems to be working better, thanks.

**Comment by tomaae** [comment]
all good, its understandable mistake
