### ISSUE TITLE
[Question] firewall filter (rules forward)

### ISSUE THREAD

**Issue by frechstv** [tomaae/homeassistant-mikrotik_router#257]
Integration does not add rules in which chain=forward and output. only rules in which chain=input. is this a problem for me or was it so initially?
![image](https://user-images.githubusercontent.com/81463507/202419277-d56ef5e3-cd22-44c1-9088-0352de7efd58.png)

![image](https://user-images.githubusercontent.com/81463507/202419384-d5356ac1-31b3-41f5-ab41-8bcc5acec448.png)

**Comment by tomaae** [comment]
all chains are added in HA, but action must be dst-nat

**Comment by frechstv** [comment]
Thank you!
