### ISSUE TITLE
[Bug] Unit of mesurement on integration setup not honored

### ISSUE THREAD

**Issue by ivanpavlina** [tomaae/homeassistant-mikrotik_router#26]
**Describe the bug**

On integration setup page there is a select option for unit of mesurement. Regardless of what is selected unit is always default Kbps. Only when you go into integration options can you make real changes that are propagated to all sensors.

**To Reproduce**
1. Go to integration configuration
2. Click on unit of mesurement, set any other unit besides default Kbps
3. Check entities for traffic, they have default Kbps unit of mesurement

**Expected behavior**
Selected unit of mesurement is used

**Software (please complete the following information):**
 - Hass.io / Home Assistant version: HA v0.107.7
 - HA Mikrotik Router integration version: *
 - Mikrotik Hardware: *
 - Mikrotik Software version: *

**Additional context**
Mikrotik controller is using config_entry.options variable to pull UNIT_OF_MEASUREMENT, it seems this is not filled with data on integration setup, only when to options are changed. I could be wrong tho, I'm not really expirienced with HA's config flows..

```
@property
def option_traffic_type(self):
  """Config entry option to not track ARP."""
  return self.config_entry.options.get(
    CONF_UNIT_OF_MEASUREMENT, DEFAULT_TRAFFIC_TYPE
  )
```

**Comment by tomaae** [comment]
It seems to work fine for me, where do you see it?
![image](https://user-images.githubusercontent.com/23486452/78798755-a6a58f00-79b9-11ea-969f-352a2e583113.png)
![image](https://user-images.githubusercontent.com/23486452/78798801-b0c78d80-79b9-11ea-9471-4765c24c4db7.png)

**Comment by tomaae** [comment]
ah, I know what you mean now

**Comment by tomaae** [comment]
looks like this issue is not solvable, I have removed the option from integration setup.
both setup and options uses same model, but they save data under different structure.
setup is config_entry.data and options is config_entry.options

at least I refactored whole config flow while I was investigating it.
