### ISSUE TITLE
[Feature] Allow multiple instances

### ISSUE THREAD

**Issue by riddley** [tomaae/homeassistant-mikrotik_router#261]
## Is your feature request related to a problem? Please describe.

I have lots of Mikrotik gear and would love to monitor all of them.

## Describe the solution you'd like

Allowing multiple instances within the integration would allow me to point at Mikrotk switches and APs in addition to my router.

## Describe alternatives you've considered

:)

## Additional context

Thanks very much for this integration! It's great!

**Comment by tomaae** [comment]
This was possible since first release. I have 6 mikrotik instances in my development environment.
