### ISSUE TITLE
[QoL] Initial configuration should suggest default 8728 port instead 0. 

### ISSUE THREAD

**Issue by neworld** [tomaae/homeassistant-mikrotik_router#263]
## Is your feature request related to a problem? Please describe.

Just Quality of Life improvement for a new setup. It is annoying to check the port number. 

## Describe the solution you'd like

Just default to 8728

**Comment by tomaae** [comment]
You dont have to set it up, unless you are using custom port. It will set up port correctly depending if you are using SSL or not.

**Comment by neworld** [comment]
> You dont have to set it up, unless you are using custom port. It will set up port correctly depending if you are using SSL or not.

Do you mean, if I leave 0 (or empty, don't remember input), it will use the default port?

**Comment by tomaae** [comment]
yes. its just for people who use custom ports.

**Comment by neworld** [comment]
> yes. its just for people who use custom ports.

Thanks for info and sorry for bothering you.
