### ISSUE TITLE
[Feature] TX and RX total are shown in bytes regardless of config

### ISSUE THREAD

**Issue by neworld** [tomaae/homeassistant-mikrotik_router#264]
## Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/38703/211940024-2fd589c5-dce6-451b-a882-9fa456c0b1a0.png)

## Describe the solution you'd like

Calculate values according to settings (in my case, it would be in MB. But it would be nice if users could decide on the configuration.

**Comment by tomaae** [comment]
There is no settings to size, just troughput. 
Even troughput conversion will be removed from integration in favor of new HA native unit conversion added in 2023.1 for data rates and data sizes.

**Comment by neworld** [comment]
> Even troughput conversion will be removed from integration in favor of new HA native unit conversion added in 2023.1 for data rates and data sizes.

It is even better. Thanks for letting me know
