### ISSUE TITLE
HA Integration, interrupts Miktrotik device updates when locally on device

### ISSUE THREAD

**Issue by DaveAuld** [tomaae/homeassistant-mikrotik_router#267]
## Describe the issue
I was recently trying to update the RouterOS on one of my devices on the network and had an issue with the Package update being interrupted constantly and would not download the packages. It would start to download, get to a random %, then tell me an update was available.
I couldn't understand why it was doing this, and thought it was maybe an issue with WinBox. I tried to then to the update via the terminal on the device and was seeing the same problem. (system package update download) It would start to download, get to a random %, then tell me an update was available.

Out of curiosity, I shutdown the Home Assistant Raspi that I have the Mikrotik integration on, looking at the RouterBoard and RouterOS firmware status (for 4 mikrotik devices)

The problem immediately stopped and the Mikrotik device would now check firmware version and update the firmware.

I don't know how often the integration is polling the Mikrotik devices, but there appears to be some link here.

## Expected behavior
Performing an update directly on the Mikrotik device, should not be interfered with by external device poll.

## Software versions
 - Home Assistant version: 2023.1.5
 - Mikrotik Router integration version: V2.1.2
 - Mikrotik Hardware:  Cube 60G ac
 - RouterOS version: V6.49.6 (was trying to update to 6.49.7 (success after SD of HA)

Workaround is obviously to shutdown the HA when doing anything locally on the Mikrotik device.

**Comment by tomaae** [comment]
I doubt that has anything to do with integration itself. I updated many times without issues at all.
Integration is using only official mikrotik api, so it cannot really interfere unless there is bug in mikrotik api itself.
Pooling is as often as you set it in config, but that wont interfere with update.

**Comment by DaveAuld** [comment]
As you say probably a bug in the actual API.

**Comment by tomaae** [comment]
I just tried it several times and it always downloaded properly. I'm on V7.6 tho
I no longer have any device with V6
