### ISSUE TITLE
[Question] How to remove not existing elements?

### ISSUE THREAD

**Issue by Saentist** [tomaae/homeassistant-mikrotik_router#268]
Currently I use ROS 7.7, but after some network changes in past, I see some not existing anymore interfaces, 
with show me version of ROS when they existed last time.
I see ROS 7.2.1 7.3.2 etc.

How to mark this not existing entity's and remove them, without reinstall integration?
Is it possible to be marked automatically as invalid?

**Comment by tomaae** [comment]
you can just click on obsolete entity in HA and delete it.

**Comment by Saentist** [comment]
> you can just click on obsolete entity in HA and delete it.

If is 1 or 5 ok but they are lot more then 100+
Need to select one by one to see is it or it isn't invalid.

**Comment by tomaae** [comment]
you can bulk select obsolete entities in HA.
cant imagine how you could end up having 100+ obsolete entities unless its from device tracking

**Comment by Saentist** [comment]
Vlan's, Vpn's they don't disappear from integration when not exist in MT configuration anymore.

**Comment by tomaae** [comment]
yes, they are not automatically removed

**Comment by Saentist** [comment]
Is there a way to mark such objects with software?

**Comment by tomaae** [comment]
what do you mean?

**Comment by Saentist** [comment]
some type of comparison, with will mark/rename unexsiting entities
ex:
vpn156 > "vpn156_not-valid_"

**Comment by tomaae** [comment]
no, because they may be valid later. integration have no way of knowing that.
but if you did large change like that, just restart HA and delete inactive entities
