### ISSUE TITLE
Mikrotik hEX S [Bug]

### ISSUE THREAD

**Issue by Marvicek** [tomaae/homeassistant-mikrotik_router#269]
Hello team
I have in my house optical version of hEX S. I don´t have see any connection clients, any traffic information is not visible.

This is my overview
client on ports not visible after klik on boton.

https://webshare.cz/#/file/8ODSvZ8Z1M/rb-png

Home Assistant 2023.2.2
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

and

Mikrotik Router
v2.1.2

hardware:
https://mikrotik.com/product/hex_s

log:
https://webshare.cz/#/file/tnxwkYukRn/config-entry-mikrotik-router-e7a82ff7eab2df81ec70f8376635da8b-json-txt

**Comment by tomaae** [comment]
you didnt enabled those features. by default only basic information is shown.

**Comment by Marvicek** [comment]
Hi Tomaae
You have true. Second setting card. Sorry for bad request.

Have a nice day
