### ISSUE TITLE
Traffic inside network missing?

### ISSUE THREAD

**Issue by Marvicek** [tomaae/homeassistant-mikrotik_router#270]
Hello Team
Today i try analyze my network traffic. I have problem with client traffic in my network. In grafs only working wan tx and rx. This mean  only internet traffic. 

My network schema:
ISP optical source to MikroTik  hEX S. From MikroTik on port one is traffic connected to the switch Tplink 48 ports. From switch is connected tp link deco mesh system for wifi. Also all wire client are connected to the switch. Here are also connected SAT ip tunners and DVBT2 ip tunners.

Problem description:
On all graphs i see internet traffic - this is ok
But missing internal traffic. For example: My nas and my work pc - here i try transfer data from nas to the pc - not in graf, also data from pc to nas are also not visible. 
I have in my network TVheadend for distribution of the signal. SAT-ip tuners, DVBT2 tunnes also generate traffic to the TVheadend mashine and also traffic between tvheadend and client. - this is also not visible.

Is mystake on setting of the plugin? 
https://webshare.cz/#/file/Lm0c6pAwNS/setting-png

Is mystake on mikrotik setting?
https://webshare.cz/#/file/xvIMg9hdbJ/4-png
https://webshare.cz/#/file/Mz0Uuks3Rm/1-png
https://webshare.cz/#/file/uLDa3YVVJm/2-png
https://webshare.cz/#/file/CVyY4A342W/3-png

Here is also log from plugin:
https://webshare.cz/#/file/gafExngys7/config-entry-mikrotik-router-7067e31fe3fcc5a4b302dd5135931d1d-json-txt

Grafana:
https://webshare.cz/#/file/muwHqmAd4B/wire-png
https://webshare.cz/#/file/NyAsFtP9Ne/mikr-status-png
https://webshare.cz/#/file/0Ask5QB5wb/wifi-png

Thanks for help and sorry for my bad english.

Martin

**Comment by tomaae** [comment]
Accounting funguje:
          "host-name": "CoreELEC",
          "tx-rx-attr": "Mbps",
          "wan-tx": 0.01,
          "wan-rx": 2.14,
Mas nastavene Mbps, takze mensi traffic nezobrazi.  Skus zmenit na Kbps pokial potrebujes viac detailov.

**Comment by Marvicek** [comment]
Ano, funguje,  ale jenom internetový traffic. Ne interní ... Když dám kopírovat 12 giga filmu z NASKY na stolní pc, tak mi to kopírování v grafech neukáže. I když to kopíruje par minut na 113 MB/s. Taffic televize ze satip tunerů a jednotlivýma klientama také vidět není. Nastavení mikrotiku špatně? že ho to nezobrazuje .. jen do internetu. Když nasku nstavuji přes webové rozhraní a instaluji třeba zasuvný modul tak se internetový traffic zobrazí oka... ale ne lokalní .

**Comment by tomaae** [comment]
Nastavenie vyzera v poriadku.
Pozri home assistant log ci tam nieje varovanie alebo chyba z accountingu.

**Comment by ondras12345** [comment]
Jde ten lokalni taffic z NASu na PC vubec pres MTik? Pochopil jsem to tak, ze jsou obe zarizeni pripojena do TPlink switche. Mikrotik nemuze merit to, o cem ani nevi.

**Comment by Marvicek** [comment]
Zdravím
Interní traffic probíhá přes switch. Ale mikrotik dělá dhcp klienta, tak by měl mít přehled o přenesených datech? Nebo ne?

**Comment by ondras12345** [comment]
Pro vnitrni sit je MTik asi spis DHCP server, ne?
DHCP slouzi jen pro prideleni sitove konfigurace (IP adresa, default gateway, DNS apod.). Kdyz se nekdo pripoji do site a chce adresu, pozada o ni broadcastem a DHCP server mu nejakou prideli (na urcitou dobu, treba 1 den). Potom uz nekomunikuji, dokud tato doba nevyprsi -- pak je potreba pozadat  o prodlouzeni.

**Comment by tomaae** [comment]
pokial data ako take nejdu cez mikrotik, nema o nich ako vediet.
