### ISSUE TITLE
[Bug] temperature displays in F not Celsius on Netpower16p

### ISSUE THREAD

**Issue by MouseRatt** [tomaae/homeassistant-mikrotik_router#271]
Amazing integration, great work. Are used to monitor several outdoor switches located on my rural property 

The only problem I have ran into is when trying to monitor the entity for Robert temperature on my netpower 16p, it displays the temperature units in Fahrenheit instead of Celsius. Is there an easy fix for this?

**Comment by tomaae** [comment]
check your HA configuration. integration presents all temp sensors as celsius, but HA is allowed to change it based on your system preferences.
