### ISSUE TITLE
[Bug] Missing Ether from CHR v7.7 (PVE)

### ISSUE THREAD

**Issue by home110120** [tomaae/homeassistant-mikrotik_router#273]
## Describe the issue
Missing ether3 (CHR-3) after setup integration in HA, tried deleting it once and re-setup, the issue still exists.

## How to reproduce the issue
Missing ether3 (CHR-3) after setup integration in HA, tried deleting it once and re-setup, the issue still exists.

## Expected behavior
Got the ether3 back of course.

## Screenshots
![图片](https://user-images.githubusercontent.com/87372532/221397166-56867902-a87b-4d74-85f3-b2bbfbe9ca9b.png)
![图片](https://user-images.githubusercontent.com/87372532/221397167-bec8f752-1fea-44a8-957f-2f1ae81d9d61.png)

## Software versions

 - Home Assistant version: <2023.2.5>
 - Mikrotik Router integration version: <3.2.0>
 - Mikrotik Hardware: <N5105, PVE>
 - RouterOS version: <CHR v7.7>

## Traceback/Error logs
did not see specific mikrotik_router related integration error logs, before and after 2 times reboots.

## Additional context
The missing port is in the middle of the ethers, not sure what is related here.

**Comment by tomaae** [comment]
Latest integration version is 2.1.2, check again what you have installed.
Once you make sure you have 2.1.2 and issue still occurs, run integration in debug. This is a weird issue, I will need to see debugs.

**Comment by home110120** [comment]
Sorry for not replying the ticket, issue resolved today while checking again. Not sure what happened before, indeed missing for several days, no update done for integration... Feel free to close the ticket.
