### ISSUE TITLE
[Question] Devices cycling between unavailable/home

### ISSUE THREAD

**Issue by skaffff** [tomaae/homeassistant-mikrotik_router#274]
Hi, I have two issues.

1. every device connected to Mikrotik cycles between unavailable and home/away every 30 seconds. Still trying to figure out why. All of the devices are connected all the time... 
2. Also, all devices are shown as wired connections, even though everything is connected on WLAN only. I have nothing connected to the router with a LAN cable (except HA RPi)

<img width="275" alt="image" src="https://user-images.githubusercontent.com/82477500/222747939-7bf646d7-31bc-4134-ba1d-59571baeb485.png">
Thanks

**Comment by tomaae** [comment]
check your HA log for errors. there is probably something there. if not, you wil have to run it in debug to see what is happening.
