### ISSUE TITLE
[Feature] number of active connections

### ISSUE THREAD

**Issue by SamJongenelen** [tomaae/homeassistant-mikrotik_router#277]
## Is your feature request related to a problem? Please describe.

I would like to see the number of active connections, possibly per interface. 

Would that be possible?

## Describe the solution you'd like

Sensors with connection count 

## Describe alternatives you've considered

None

**Comment by tomaae** [comment]
can you give more detail? not sure what do you mean by active connections per interface.

**Comment by SamJongenelen** [comment]
Well, for instance, if i have say some internet facing hosts on different interfaces, is like to know the IP connections/sockets that are open.
I don't have winbox near me, but i think the interface has a list op connections, id like just the count.

Reason: sometimes my network is slow bc a ver very high amount of small packets is being sent. (Think BitTorrent style).
So not much down or up is consumed, not much CPU of ram, but still my network is slow. For me to see this (eg `Eth1: 1083 connection`  in a dashboard in HA can help me see what's going on. Maybe even the socket state (open,idle, waiting,..) would even be possible 

Hope this helps make it clear.

**Comment by tomaae** [comment]
I dont think something like that is available on mikrotik. but if you can find it, I will look if its feasable.

**Comment by SamJongenelen** [comment]
The command that would be similar would be
`/ip/firewall/connection/print`

I guess?

**Comment by tomaae** [comment]
using connection list is not really an option. that can be a long list which is known to cause high cpu load on mikrotik.
we would need access to already computed data provided by mikrotik.
