### ISSUE TITLE
[Bug] Multiple Router devices, showing all Scripts together

### ISSUE THREAD

**Issue by hiagocosta** [tomaae/homeassistant-mikrotik_router#278]
## Describe the issue
I have two Hex S devices, that I include on HA, and all your scripts is showing in together on the scripts entities.
Wil be better when I open a device, it shows only scripts configured in that device, not in all devices that I have added on HA.

## How to reproduce the issue
add more than one routerboard, and let different scripts on each device you will see that all scripts are on both scripts lists

## Expected behavior
I expected to only show scripts integrated on the routerboard that I opened on the list of devices included in this integration

## Screenshots
![image](https://user-images.githubusercontent.com/22087481/230916470-d8b44c86-ea97-406f-a44e-ea0d3919b782.png)

## Software versions

 - Home Assistant version: 2023.4.2
Supervisor 2023.04.0
Operating System 9.5
Frontend: 20230406.1
 - Mikrotik Router integration version: Mikrotik Router 2.1.2
 - Mikrotik Hardware: Rb760iGS - RB750Gr3
 - RouterOS version: v7.8 on both

**Comment by tomaae** [comment]
hmm, not sure what is a problem here. did both miktorik devices ended up named the same, so teh merged?

**Comment by tomaae** [comment]
Can you screenshot how this looks under integration for you?
![image](https://user-images.githubusercontent.com/23486452/234689061-2288a818-c6c5-4613-a26f-67c5f9d20f47.png)
![image](https://user-images.githubusercontent.com/23486452/234689183-c42746ff-409a-489e-9685-dec0d078f6bc.png)

for each of you systems?

**Comment by hiagocosta** [comment]
yes, of course

![image](https://user-images.githubusercontent.com/22087481/234984439-9294dec8-a121-4662-8426-72f676c10cfb.png)

now its strange, because, I can't get scripts that is placed on RT-WORLD, even with the configuration checked to get these

**Comment by hiagocosta** [comment]
this is another strange behavior

this keeps showing that I have an update, but i'm on the latest versions:

![image](https://user-images.githubusercontent.com/22087481/234986218-33bb0fd6-18cf-4f97-b798-e53be31a33a8.png)

**Comment by tomaae** [comment]
that is problem on mikrotik side. it most likely cannot reach update servers.

can you run debug for at least 2 cycles? I need to understand what is happening with those script sensors internally.

**Comment by hiagocosta** [comment]
After a restart it seems to be the dns connections to get the updates, now is corrected
I will check the "meshing on scripts" , and if needed, I'lll open another issue to investigate better
