### ISSUE TITLE
[Bug] No devices added to the integration / KeyError: 'unknown'

### ISSUE THREAD

**Issue by bbacskay** [tomaae/homeassistant-mikrotik_router#28]
**Describe the bug**
No device or entity is added from the given router. The log has the following entries:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/config/custom_components/mikrotik_router/__init__.py", line 34, in async_setup_entry
    await controller.async_update()
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 359, in async_update
    await self.hass.async_add_executor_job(self.get_dhcp)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 857, in get_dhcp
    self.data["dhcp"][uid]["server"]
KeyError: 'unknown'

**To Reproduce**
1. In WinBox open the 'IP->DHCP Server' window, switch to the 'Leases' tab.
2. Change any static entry's 'Server' option to 'all'
3. Add a new integration for the router or restart HA

**Expected behavior**
Regardless of the DHCP Server value the devices should be detected/added.

**Screenshots**

**Software:**
 - Hass.io / Home Assistant version: Hassio v217/ HA v0.108.3
 - HA Mikrotik Router integration version: v1.5.1
 - Mikrotik Hardware: RB951G-2HnD
 - Mikrotik Software version: v6.46

**Additional context**
When processing the response of the API query: /ip/dhcp-server/lease

Example with DHCP Server set to one of the DHCP servers:
`2020-04-12 21:57:10 DEBUG (SyncWorker_10) [custom_components.mikrotik_router.helper] Processing entry {'.id': '*77', 'address': '192.168.XX.15', 'mac-address': 'XX:XX:XX:XX:XX:XX', 'client-id': '1:XX:XX:XX:XX:XX:XX', 'address-lists': '', 'server': 'default-LAN', 'dhcp-option': '', 'status': 'waiting', 'last-seen': '262w2d16h39m54s', 'host-name': 'hostname', 'radius': False, 'dynamic': False, 'blocked': False, 'disabled': False, 'comment': 'comment'}`

Example with DHCP Server set to 'all':
`2020-04-12 21:57:10 DEBUG (SyncWorker_10) [custom_components.mikrotik_router.helper] Processing entry {'.id': '*B5', 'address': '192.168.XX.20', 'mac-address': 'YY:YY:YY:YY:YY:YY', 'client-id': '1:YY:YY:YY:YY:YY:YY', 'address-lists': '', 'dhcp-option': '', 'status': 'waiting', 'last-seen': '2w2d9h35m4s', 'host-name': 'hostname2', 'radius': False, 'dynamic': False, 'blocked': False, 'disabled': False, 'comment': 'comment'}`

So in the second example the 'server' entry is missing.

**Comment by tomaae** [comment]
Thank for reporting, should be fixed in v1.5.2
