### ISSUE TITLE
Device tracker reporting unknown

### ISSUE THREAD

**Issue by Luc3as** [tomaae/homeassistant-mikrotik_router#282]
Hi, 
I don't know if I am doing something wrong, I have successfully set the integration, it is detecting hosts and reporting correct zone I configured. 
However when I setup people entity, use this device tracker for tracking, it will show unknown entity even tho the zone in device itself is correct. 
I tried to rename the zone, use small caps, remove special characters, remove and recreate new people entity, still the same.

entity on left is people, on the right is detected device from Mikrotik router integration 
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/6381468/3be4a3e5-900e-411e-9ff5-c5c601b4df18)

**Comment by tomaae** [comment]
As long as integration is reporting correct status, it should work. Cant help you much in how to configure people integration, I dont have experience with that.
