### ISSUE TITLE
intergration not working after HA 2023.6.0

### ISSUE THREAD

**Issue by martinhanes** [tomaae/homeassistant-mikrotik_router#286]
Integration stopped working after upgrading to version 2023.6.0 due to the following error:

homeassistant.helpers.entity_registry' has no attribute 'async_get_registry'

probable fix is to change the line from 
`device_registry = await dr.async_get_registry(hass)`
to 
`device_registry = dr.async_get(hass).
`

**Comment by tomaae** [comment]
I have not tested it on 2023.6, will do

**Comment by Korol-Yurii** [comment]
I have the same problem

Error setting up entry mymikrotik for mikrotik_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mikrotik_router/__init__.py", line 40, in async_setup_entry
    await controller.async_update()
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 542, in async_update
    await self.async_get_host_hass()
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 398, in async_get_host_hass
    registry = await self.hass.helpers.entity_registry.async_get_registry()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1050, in __getattr__
    value = getattr(self._module, attr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.helpers.entity_registry' has no attribute 'async_get_registry'

**Comment by sshalyminov** [comment]
@tomaae any news please? 2003.6.1 is actual HA version already...

**Comment by tomaae** [comment]
yea, I'm just really busy. I have a lot planned for this integration, but I need to get some free time which is very difficult for me right now.
I will most likely just realease small patch version for this.

**Comment by tomaae** [comment]
It is taking longer then expected since I decided to go all the way and implement all new HA features.
Specially HA build-in value conversion such as units of measurements and unit precision. We will no longer need to use our custom integration wide conversions.
Difficult part is already done, I mostly need to go over all the entities and configure them for new system. Also, a lot of testing, since this integration is massive.

**Comment by tomaae** [comment]
Just to keep you guys updated, I'm having trouble with HA coordinator ignoring update interval.
I'm trying to get help from HA devs, but its getting slow since they are busy of course and this is some weird issue.

**Comment by tomaae** [comment]
Update: everything except device tracker works now

**Comment by tomaae** [comment]
Everything should work now, needs more testing and some cleanup.
If you want to help testing, its in coordinator branch

**Comment by apaneiro** [comment]
Any plans to put the coordinator in production to be available in HA?

**Comment by tomaae** [comment]
thats the point of coordinator branch. 
it still needs more testing and some work. this is very feature wide integration.

**Comment by tomaae** [comment]
rebased and merged into master for easier testing, its easier to install from HACS

**Comment by tomaae** [comment]
v2.1.3 released
