### ISSUE TITLE
[Question] Configuration via config file yaml

### ISSUE THREAD

**Issue by Losenmann** [tomaae/homeassistant-mikrotik_router#287]
Hello!
I had a need to use the settings through the configuration file of the yaml format. I have searched for configuration documentation but all attempts have been in vain. Tell me, does the integration support configuration through the config file? If so, where can I find documentation on setting up via the config file?

**Comment by tomaae** [comment]
No, its not supported. As HA is phasing out yaml configuration for integration, it will not be implemented.
