### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by carels** [tomaae/homeassistant-mikrotik_router#29]
Could you improve the documentation on this project? It leaves a lot of unanswered questions:

1. Refers to the built-in Mikrotik integration (Configuration -> Integrations -> Add -> Mikrotik), however, there's no clarity on whether this code is the same as the built-in integration. e.g. the built-in integration only produces device tracking (no scripts, interfaces visibility, etc - unless there is something wrong with my setup).

2. Assuming there's a difference in the code, what is the installation steps? Assuming copying of the code to custom_components, but what about configuration.yaml?

3. Sample howto describing triggering a script or disabling an interface would also be appreciated

Thanks

**Comment by tomaae** [comment]
I'm all for improving the documentation if there is something missing. But your questions are related to misread part of the documentation.

1. It say "Configuration -> Integrations -> Add -> Mikrotik Router". There is no reference to build-in mikrotik integration at all.

2. This integration is installed using HACS. Of course you could install it manually without HACS, but I wont cover that method as it is needlessly complicated and troublesome to keep integration up to date.

3. Like any other HA switch, just toggle it manually or using automation

**Comment by tomaae** [comment]
If you are not familiar with HACS, here is a link [https://hacs.xyz/](https://hacs.xyz/)

**Comment by carels** [comment]
Thanks for the quick response :)

The readme file doesn't actually mention HACS. I did find the reference in another ha/mikrotik integration (https://github.com/pilotak/homeassistant-mikrotik) which looks like a different repository. Oddly, in HACS I can also see both repositories. pilotak's repo doesn't mention API scripts, etc, but in HACS it does. Yours states api scripts, etc on github, but not in HACS. What is the relationship between these two repos?

Regards,
Carel

**Comment by tomaae** [comment]
There is a HACS badge at the top, I didnt really go into detail because HACS is the only place where you can find this integration. Except random google result of course :)
HACS loads readme file from github, so it has to show exactly the same information. For me it does.
There is no relationship between these repos at all.

**Comment by carels** [comment]
OK, I've managed to get it installed now. Probably worth adding to the documentation:

- Add reference to HACS as prerequisite. I found this integration via Google, not from within HA
- The Documentation states: "Setup this integration for your Mikrotik device in Home Assistant via 
 Configuration -> Integrations -> Add -> Mikrotik Router". It would be helpful to highlight that there is a built-in Mikrotik Integration which is not the same module. This caused a lot of confusion for me
- It is not obvious that Track Network States MUST be enable to get any useful info from the integration. I want to trigger scripts, not necessarily track devices so it didn't make sense to tick that box which resulted in not being able to find any of the scripts being detected. Not sure if this is a bug or expected behaviour. 
- It does look like after installing and configuring the integration HA needs to be restarted. 

The integration does work brilliantly. Now finally I can cut off the kids' internet when they leave the bathroom light on! 🤣

**Comment by tomaae** [comment]
what do you mean by not being able to get any useful info when tracking is not enabled?

yes, after installing you need to restart. HACS will prompt you to do so. no restart is needed after configuring it tho. I keep removing and adding new routers all the time during development, there is no problem with that.

now I feel bad for your kids 🤣

**Comment by carels** [comment]
Without tracking enabled, i didn't see any information populated under device (no scripts, interfaces, or devices). This was before a restart though so may just have needed a restart. 

> now I feel bad for your kids 🤣
They've been moaning the whole morning! 🤣

**Comment by tomaae** [comment]
thats really weird. integration should not even appear in the list before you restart. I will clean up my dev instance and test it.

**Comment by tomaae** [comment]
so I have installed brand new ha instance, added integration and everything works fine even without enabling tracked devices.
of course I can see all scripts, interfaces and other sensors

**Comment by tomaae** [comment]
If possible, could you test it once more?
If you wont get any entities when tracking is disabled, run it in debug to capture the issue so I can look into it.
