### ISSUE TITLE
[Bug]: Home Assistant shows "Mikrotik Firmware Update is available" although it was yet installed

### ISSUE THREAD

**Issue by argually** [tomaae/homeassistant-mikrotik_router#290]
## Software versions

 - Home Assistant version: 
 - Mikrotik Router integration version: 
 - Mikrotik Hardware: 
 - RouterOS version:

**Comment by argually** [comment]
Addenum:
The "Installed Version" (of the Routerboard Firmware) is falsely detected as "Version 7.6". In fact it is Version 7.10.1.

**Comment by tomaae** [comment]
I dont think that is possible. Can you show me output from your router?

**Comment by argually** [comment]
Which "output" do you need?

**Comment by tomaae** [comment]
your router firmware version. I dont mind if it is from console or screenshot from gui

**Comment by argually** [comment]
Look...
![github screenshot](https://github.com/tomaae/homeassistant-mikrotik_router/assets/82281525/54a77f9d-427b-4f2f-b674-8dfb488e4803)

**Comment by tomaae** [comment]
Thats RouterOS version, not RouterBoard firmware.
You can check it at `/system/routerboard/print`

**Comment by argually** [comment]
Seems, that you are right ...
![routerboard firmware](https://github.com/tomaae/homeassistant-mikrotik_router/assets/82281525/079d1df3-c2ec-45e9-b51c-a3b55c9d2b86)

**Comment by argually** [comment]
So why doesńt it upgrade the firmware?

**Comment by argually** [comment]
After upgrading from the menu /system/routerboard/upgrade the update message in Home Assistant is gone.
THANK YOU very much!

**Comment by tomaae** [comment]
it does update the firmware, you could just install it from HA if you wanted.
every routerboard has 2 updates with each version. non-routerboard devices, just one.
