### ISSUE TITLE
Listing WiFi Interfaces

### ISSUE THREAD

**Issue by NyariG** [tomaae/homeassistant-mikrotik_router#294]
Hello, the program is great, however, I couldn't find the WiFi interfaces anywhere. I've written a script for the router that I would like to run, but it depends on whether the WiFi interfaces are enabled or not. But I couldn't find an entity to query their statuses.

**Comment by tomaae** [comment]
Supported are wireless, wifiwave2 and capsman. They all work.

**Comment by NyariG** [comment]
Ah, I understand! But then where can I find these entities, and with what can these be regulated?

**Comment by tomaae** [comment]
right now, you can just look for those entities in list.
There was an undocumented breaking change which broke links between devices, so they are not properly categorized. Its fixed dev #292
I will be merging it with master soon #286
