### ISSUE TITLE
[Bug]Cant see any of the interfaces

### ISSUE THREAD

**Issue by dustin-auby** [tomaae/homeassistant-mikrotik_router#295]
## Cant see any of the interfaces even when given all permissions and check all the options in the config

I have done a standard install through HACS and most of the entites are accessible just not the interfaces which is actually the only thing i am looking for. i have given the user full access and checked all of the options in the config window. the integration loads 159 entities but none of them are the interfaces.

## How to reproduce the issue

I followed the standard install procedure from the HACS store

## Expected behavior

I should be able to see a list of interfaces and each of their attributes

## Software versions

All fields in this sections are required.

 - Home Assistant version: 2023.8.1
 - Mikrotik Router integration version: 2.1.2
 - Mikrotik Hardware: RB2011UiAS
 - RouterOS version: 6.46.6

**Comment by tomaae** [comment]
I dont think that can happen. Check entities again, it should be there.
You can upload diagnostics to crosscheck.

**Comment by PetrP2B** [comment]
I have the same problem. I don't know exactly when it happened, whether when updating Mikrotik or HA to the beta version. I didn't change the Mikrotik settings, I tried uninstalling the extension in HA, resetting the connection with MK, but nothing helped.

Home Assistant 2023.9.0b4
Mikrotik Router 2.1.2
Mikrotik sw 7.11.2

Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:621
Integration: Vypínač (documentation, issues)
First occurred: 08:58:07 (35 occurrences)
Last logged: 08:59:25

mikrotik_router: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.2.6', 'connections': {('mac', 'xx:xx:xx:xx:24:42')}, 'default_manufacturer': 'MikroTik', 'default_model': 'hAP ac lite', 'default_name': 'Mikrotik wlan1', 'identifiers': {('mac', 'xx:xx:xx:xx:24:42')}, 'sw_version': '7.11.2 (stable)', 'via_device': ('mikrotik_router', 'xxxxxxxxFB09')} for 'mikrotik_router' config entry: device info needs to either describe a device, link to existing device or provide extra information.
mikrotik_router: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.2.6', 'connections': {('mac', 'xx:xx:xx:xx:24:41')}, 'default_manufacturer': 'MikroTik', 'default_model': 'hAP ac lite', 'default_name': 'Mikrotik wlan2', 'identifiers': {('mac', 'xx:xx:xx:xx:24:41')}, 'sw_version': '7.11.2 (stable)', 'via_device': ('mikrotik_router', 'xxxxxxxxFB09')} for 'mikrotik_router' config entry: device info needs to either describe a device, link to existing device or provide extra information.
mikrotik_router: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.2.6', 'connections': {('mac', 'xx:xx:xx:xx:56:19')}, 'default_manufacturer': 'MikroTik', 'default_model': 'hAP ac lite', 'default_name': 'Mikrotik lte1', 'identifiers': {('mac', 'xx:xx:xx:xx:56:19')}, 'sw_version': '7.11.2 (stable)', 'via_device': ('mikrotik_router', 'xxxxxxxxFB09')} for 'mikrotik_router' config entry: device info needs to either describe a device, link to existing device or provide extra information.
mikrotik_router: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.2.6', 'connections': {('mac', xx:xx:xx:xx:76:1F-ovpn-out1')}, 'default_manufacturer': 'MikroTik', 'default_model': 'hAP ac lite', 'default_name': 'Mikrotik ovpn-out1', 'identifiers': {('mac', xx:xx:xx:xx:76:1F-ovpn-out1')}, 'sw_version': '7.11.2 (stable)', 'via_device': ('mikrotik_router', 'xxxxxxxxFB09')} for 'mikrotik_router' config entry: device info needs to either describe a device, link to existing device or provide extra information.
mikrotik_router: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.2.6', 'connections': {('mikrotik_router', 'NAT')}, 'default_manufacturer': 'MikroTik', 'default_model': 'hAP ac lite', 'default_name': 'Mikrotik NAT', 'identifiers': {('mikrotik_router', 'NAT')}, 'sw_version': '7.11.2 (stable)', 'via_device': ('mikrotik_router', 'xxxxxxxxFB09')} for 'mikrotik_router' config entry: device info needs to either describe a device, link to existing device or provide extra information.

**Comment by BluThunder2k** [comment]
I see you're running 9.0b4, I just upgrade to 9 non beta release and the integration is now giving me the same errors in my log.

**Comment by tomaae** [comment]
I dont see any breaking changes in 2013.9 that could cause issues. but there was undocumented one in 2013.8 as well, so who knows.
Did you try master?

**Comment by dustin-auby** [comment]
For me deleting the integration and starting from scratch seemed to resolve the problem
