### ISSUE TITLE
[Bug] 2023.9.X missing system and diagnostic sensors

### ISSUE THREAD

**Issue by alexanderznamensky** [tomaae/homeassistant-mikrotik_router#300]
After upgrading to HA 2023.9.0 + master branch, I have missed following sensors:
- sensor.mikrotik_hap_ac_cpu_temperature
System sensors:
- sensor.mikrotik_uptime
- sensor.mikrotik_cpu_load
- sensor.mikrotik_memory_usage
- sensor.mikrotik_hdd_usage
- sensor.mikrotik_wired_clients
- sensor.mikrotik_captive_portal_clients

Home Assistant 2023.9.0
Supervisor 2023.08.3
MikroTik FW 6.49.10

**Comment by NyvenZA** [comment]
Same issue. None of my Mikrotik info is working.

**Comment by HA-TB303** [comment]
Some here, seems to be a bug related to the new version of HA.

**Comment by fotis3d** [comment]
Same here also. After the latest HA update.

I have 2 Mikrotiks lost the sensors too.

**Comment by EvgveneSV** [comment]
Same issues. Have few devises with ROS 7.11.2 and 7.9.1

**Comment by NyvenZA** [comment]
Updated to 2023.9.1 and still not working.

**Comment by tomaae** [comment]
I dont have this issue on master branch:
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/23486452/1415026f-5b3a-4f4a-9fa9-44907565780c)
Check HA log and integration diagnostics. if there is nothing, we will need to look at debugs.

**Comment by aurelmarius** [comment]
No problem here also...
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/7074653/9b72c65b-9f40-4379-a4f2-74844df8c03a)

**Comment by brezuicabogdan** [comment]
I have the same issue with ROS 7.11.2, HA 2023.9.0 plugin version 2.1.2. I tried uninstalling and re-installing the plugin besides rebooting both the Mikrotik device and HA.

I noticed these errors in teh HA logs ... maybe it can help debugging

`homeassistant    | 2023-09-09 20:34:10.358 ERROR (MainThread) [homeassistant.components.switch] mikrotik_router: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.1.1', 'connections': {('mac', '1A:FD:74:C3:85:A7-wifi-devices-24ghz')}, 'default_manufacturer': 'MikroTik', 'default_model': 'hAP ax^2', 'default_name': 'router.lan wifi-devices-24ghz', 'identifiers': {('mac', '1A:FD:74:C3:85:A7-wifi-devices-24ghz')}, 'sw_version': '7.11.2 (stable)', 'via_device': ('mikrotik_router', 'HD808EFE1DZ')} for 'mikrotik_router' config entry: device info needs to either describe a device, link to existing device or provide extra information.
homeassistant    | 2023-09-09 20:34:10.358 ERROR (MainThread) [homeassistant.components.switch] mikrotik_router: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.1.1', 'connections': {('mac', '1A:FD:74:C3:85:A8-wifi-guests-5ghz')}, 'default_manufacturer': 'MikroTik', 'default_model': 'hAP ax^2', 'default_name': 'router.lan wifi-guests-5ghz', 'identifiers': {('mac', '1A:FD:74:C3:85:A8-wifi-guests-5ghz')}, 'sw_version': '7.11.2 (stable)', 'via_device': ('mikrotik_router', 'HD808EFE1DZ')} for 'mikrotik_router' config entry: device info needs to either describe a device, link to existing device or provide extra information.
homeassistant    | 2023-09-09 20:34:10.358 ERROR (MainThread) [homeassistant.components.switch] mikrotik_router: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.1.1', 'connections': {('mac', '1A:FD:74:C3:85:A9-wifi-guests-24ghz')}, 'default_manufacturer': 'MikroTik', 'default_model': 'hAP ax^2', 'default_name': 'router.lan wifi-guests-24ghz', 'identifiers': {('mac', '1A:FD:74:C3:85:A9-wifi-guests-24ghz')}, 'sw_version': '7.11.2 (stable)', 'via_device': ('mikrotik_router', 'HD808EFE1DZ')} for 'mikrotik_router' config entry: device info needs to either describe a device, link to existing device or provide extra information.
homeassistant    | 2023-09-09 20:34:10.359 ERROR (MainThread) [homeassistant.components.switch] mikrotik_router: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.1.1', 'connections': {('mac', '18:FD:74:C3:85:A7')}, 'default_manufacturer': 'MikroTik', 'default_model': 'hAP ax^2', 'default_name': 'router.lan wifi1', 'identifiers': {('mac', '18:FD:74:C3:85:A7')}, 'sw_version': '7.11.2 (stable)', 'via_device': ('mikrotik_router', 'HD808EFE1DZ')} for 'mikrotik_router' config entry: device info needs to either describe a device, link to existing device or provide extra information.
homeassistant    | 2023-09-09 20:34:10.359 ERROR (MainThread) [homeassistant.components.switch] mikrotik_router: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.1.1', 'connections': {('mac', '18:FD:74:C3:85:A8')}, 'default_manufacturer': 'MikroTik', 'default_model': 'hAP ax^2', 'default_name': 'router.lan wifi2', 'identifiers': {('mac', '18:FD:74:C3:85:A8')}, 'sw_version': '7.11.2 (stable)', 'via_device': ('mikrotik_router', 'HD808EFE1DZ')} for 'mikrotik_router' config entry: device info needs to either describe a device, link to existing device or provide extra information.
homeassistant    | 2023-09-09 20:34:10.360 ERROR (MainThread) [homeassistant.components.update] mikrotik_router: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.1.1', 'connections': {('mikrotik_router', 'HD808EFE1DZ')}, 'default_manufacturer': 'MikroTik', 'default_model': 'hAP ax^2', 'default_name': 'router.lan hAP ax^2', 'identifiers': {('mikrotik_router', 'HD808EFE1DZ')}, 'sw_version': '7.11.2 (stable)', 'via_device': ('mikrotik_router', 'HD808EFE1DZ')} for 'mikrotik_router' config entry: device info needs to either describe a device, link to existing device or provide extra information.
homeassistant    | 2023-09-09 20:34:10.360 ERROR (MainThread) [homeassistant.components.update] mikrotik_router: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.1.1', 'connections': {('mikrotik_router', 'HD808EFE1DZ')}, 'default_manufacturer': 'MikroTik', 'default_model': 'hAP ax^2', 'default_name': 'router.lan hAP ax^2', 'identifiers': {('mikrotik_router', 'HD808EFE1DZ')}, 'sw_version': '7.11.2 (stable)', 'via_device': ('mikrotik_router', 'HD808EFE1DZ')} for 'mikrotik_router' config entry: device info needs to either describe a device, link to existing device or provide extra information.`

**Comment by aurelmarius** [comment]
> I have the same issue with ROS 7.11.2, HA 2023.9.0 plugin version 2.1.2. I tried uninstalling and re-installing the plugin besides rebooting both the Mikrotik device and HA.
> 
> 
> 
> I noticed these errors in teh HA logs ... maybe it can help debugging
> 
> 
> 
> `homeassistant    | 2023-09-09 20:34:10.358 ERROR (MainThread) [homeassistant.components.switch] mikrotik_router: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.1.1', 'connections': {('mac', '1A:FD:74:C3:85:A7-wifi-devices-24ghz')}, 'default_manufacturer': 'MikroTik', 'default_model': 'hAP ax^2', 'default_name': 'router.lan wifi-devices-24ghz', 'identifiers': {('mac', '1A:FD:74:C3:85:A7-wifi-devices-24ghz')}, 'sw_version': '7.11.2 (stable)', 'via_device': ('mikrotik_router', 'HD808EFE1DZ')} for 'mikrotik_router' config entry: device info needs to either describe a device, link to existing device or provide extra information.
> 
> homeassistant    | 2023-09-09 20:34:10.358 ERROR (MainThread) [homeassistant.components.switch] mikrotik_router: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.1.1', 'connections': {('mac', '1A:FD:74:C3:85:A8-wifi-guests-5ghz')}, 'default_manufacturer': 'MikroTik', 'default_model': 'hAP ax^2', 'default_name': 'router.lan wifi-guests-5ghz', 'identifiers': {('mac', '1A:FD:74:C3:85:A8-wifi-guests-5ghz')}, 'sw_version': '7.11.2 (stable)', 'via_device': ('mikrotik_router', 'HD808EFE1DZ')} for 'mikrotik_router' config entry: device info needs to either describe a device, link to existing device or provide extra information.
> 
> homeassistant    | 2023-09-09 20:34:10.358 ERROR (MainThread) [homeassistant.components.switch] mikrotik_router: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.1.1', 'connections': {('mac', '1A:FD:74:C3:85:A9-wifi-guests-24ghz')}, 'default_manufacturer': 'MikroTik', 'default_model': 'hAP ax^2', 'default_name': 'router.lan wifi-guests-24ghz', 'identifiers': {('mac', '1A:FD:74:C3:85:A9-wifi-guests-24ghz')}, 'sw_version': '7.11.2 (stable)', 'via_device': ('mikrotik_router', 'HD808EFE1DZ')} for 'mikrotik_router' config entry: device info needs to either describe a device, link to existing device or provide extra information.
> 
> homeassistant    | 2023-09-09 20:34:10.359 ERROR (MainThread) [homeassistant.components.switch] mikrotik_router: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.1.1', 'connections': {('mac', '18:FD:74:C3:85:A7')}, 'default_manufacturer': 'MikroTik', 'default_model': 'hAP ax^2', 'default_name': 'router.lan wifi1', 'identifiers': {('mac', '18:FD:74:C3:85:A7')}, 'sw_version': '7.11.2 (stable)', 'via_device': ('mikrotik_router', 'HD808EFE1DZ')} for 'mikrotik_router' config entry: device info needs to either describe a device, link to existing device or provide extra information.
> 
> homeassistant    | 2023-09-09 20:34:10.359 ERROR (MainThread) [homeassistant.components.switch] mikrotik_router: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.1.1', 'connections': {('mac', '18:FD:74:C3:85:A8')}, 'default_manufacturer': 'MikroTik', 'default_model': 'hAP ax^2', 'default_name': 'router.lan wifi2', 'identifiers': {('mac', '18:FD:74:C3:85:A8')}, 'sw_version': '7.11.2 (stable)', 'via_device': ('mikrotik_router', 'HD808EFE1DZ')} for 'mikrotik_router' config entry: device info needs to either describe a device, link to existing device or provide extra information.
> 
> homeassistant    | 2023-09-09 20:34:10.360 ERROR (MainThread) [homeassistant.components.update] mikrotik_router: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.1.1', 'connections': {('mikrotik_router', 'HD808EFE1DZ')}, 'default_manufacturer': 'MikroTik', 'default_model': 'hAP ax^2', 'default_name': 'router.lan hAP ax^2', 'identifiers': {('mikrotik_router', 'HD808EFE1DZ')}, 'sw_version': '7.11.2 (stable)', 'via_device': ('mikrotik_router', 'HD808EFE1DZ')} for 'mikrotik_router' config entry: device info needs to either describe a device, link to existing device or provide extra information.
> 
> homeassistant    | 2023-09-09 20:34:10.360 ERROR (MainThread) [homeassistant.components.update] mikrotik_router: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://192.168.1.1', 'connections': {('mikrotik_router', 'HD808EFE1DZ')}, 'default_manufacturer': 'MikroTik', 'default_model': 'hAP ax^2', 'default_name': 'router.lan hAP ax^2', 'identifiers': {('mikrotik_router', 'HD808EFE1DZ')}, 'sw_version': '7.11.2 (stable)', 'via_device': ('mikrotik_router', 'HD808EFE1DZ')} for 'mikrotik_router' config entry: device info needs to either describe a device, link to existing device or provide extra information.`

Upgrade plugin to master branch.

**Comment by brezuicabogdan** [comment]
Thanks - this worked

**Comment by fotis3d** [comment]
How do we upgrade to master branch ?

**Comment by artpcpl** [comment]
HACS 
![Screenshot - 10 09 2023 , 13_46_42](https://github.com/tomaae/homeassistant-mikrotik_router/assets/51026569/2530e543-15a3-4c71-9813-b4679fdc3100)

**Comment by hippieua** [comment]
same bug on 2.1.2
I see all data in downloaded diagnostic file, but they are not shown in HA
after updating to master - problem solved

**Comment by tomaae** [comment]
this issue cannot show up on 2.1.2 and 2023.9.X, its something completely different.

**Comment by fotis3d** [comment]
@artpcpl thanks

Worked for me also on "master". Should we stay on master though ?

**Comment by tomaae** [comment]
its fine to stay on master until next version is released. thats the only option if you need integration working in the mean time.

**Comment by fotis3d** [comment]
@tomaae ok gr8 thanks a lot ;)

**Comment by emilianogetino** [comment]
If I change to the master version, will any configuration be lost? Or will everything stay the same as it was?
thank you.

**Comment by fotis3d** [comment]
@emilianogetino everything will stay the same. At least for me did ;)

**Comment by tomaae** [comment]
some uid will change, still have to fix that one.

**Comment by hippieua** [comment]
> this issue cannot show up on 2.1.2 and 2023.9.X, its something completely different.

I noticed it after updating to 2023.9.1, Im not sure if it was working on 2023.9.0, but on latest 2023.8.x it was working correctly

I tried reintalling, reinitializing, reconfiguring nothing helped, only switch to master

i noticed the the only record it could create in HA - were related to device_tracker domain.

but in debug i could see all data.
[config_entry-mikrotik_router-136de2ca81680c3da3f4c244e6a0420b.json.txt](https://github.com/tomaae/homeassistant-mikrotik_router/files/12575687/config_entry-mikrotik_router-136de2ca81680c3da3f4c244e6a0420b.json.txt)

**Comment by tomaae** [comment]
I can see system sensors there and available.

**Comment by hippieua** [comment]
yes, that what I am talking about. But in HA there was 0 sensors and switches available. Only related to device tracker

**Comment by bonsi001** [comment]
I have the same issue as [hippieua].
On HA there was 0 sensors and switches available. Only related to device tracker
On 2023.9.0
And on 2023.9.1
2.1.2 
ROS 7.11.2

**Comment by tomaae** [comment]
This is abotu master branch, not 2.1.2

**Comment by alexanderznamensky** [comment]
after update to 2.1.3 issue is still existing:
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/65254375/bcbe0f30-de5a-4d38-bf08-7f2b3ca076d2)

![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/65254375/5178ebbb-9a85-474e-ac3c-44366ebdcad0)

**Comment by asifkassam** [comment]
this problem only exists for me with RouterOS 6 (works fine with RouterOS 7)

tried master branch and 2.13

unable to download diagnostics

![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/67918736/4571f773-e11c-4d4a-b3d2-9f40af99bef5)


debug logs attached:

[home-assistant_2023-09-13T11-51-47.065Z.log](https://github.com/tomaae/homeassistant-mikrotik_router/files/12597067/home-assistant_2023-09-13T11-51-47.065Z.log)

**Comment by tomaae** [comment]
```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 586, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'unknown'```
I see, this is probably related to https://developers.home-assistant.io/blog/2023/08/23/sensor-updates/

Diagnostics not working is another issue. Have to look into that.

**Comment by alexanderznamensky** [comment]
After update to Home Assistant 2023.9.2 (Supervisor 2023.09.2, MikroTik FW 6.49.10):

1. Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:593
Integration: Сенсор (documentation, issues)
First occurred: 09:14:24 (2 occurrences)
Last logged: 09:14:24

Error adding entities for domain sensor with platform mikrotik_router
Error while setting up mikrotik_router platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 586, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 589, in state
    numerical_value = float(value)
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unknown'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1002, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 771, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 593, in state
    raise ValueError(
ValueError: Sensor sensor.mikrotik_hap_ac_cpu_temperature has device class 'temperature', state class 'measurement' unit '°C' and suggested precision '0' thus indicating it has a numeric value; however, it has the non-numeric value: 'unknown' (<class 'str'>)

2. Logger: homeassistant.components.device_tracker
Source: custom_components/mikrotik_router/device_tracker.py:72
Integration: Устройство для отслеживания ([documentation](https://www.home-assistant.io/integrations/device_tracker), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+device_tracker%22))
First occurred: 09:14:24 (1 occurrences)
Last logged: 09:14:24

Error while setting up mikrotik_router platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mikrotik_router/device_tracker.py", line 110, in async_setup_entry
    await async_add_entities(hass, config_entry, dispatcher)
  File "/config/custom_components/mikrotik_router/device_tracker.py", line 89, in async_add_entities
    await async_update_controller(
  File "/config/custom_components/mikrotik_router/device_tracker.py", line 72, in async_update_controller
    data = coordinator.data[entity_description.data_path]
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

Thanks!

**Comment by tomaae** [comment]
yes, thats exactly same error message as above.

**Comment by alexanderznamensky** [comment]
[tomaae](https://github.com/tomaae)? thanks for your excelent work!
Now it is perfect - all sensors are working!

Thanks indeed!

**Comment by tomaae** [comment]
perfect
