### ISSUE TITLE
[Bug] Error on start when not having device tracker on

### ISSUE THREAD

**Issue by tomaae** [tomaae/homeassistant-mikrotik_router#302]
I'm not using device tracking feature, but I noticed this error popping up in HA logs on every restart:

```console
Logger: homeassistant.components.device_tracker
Source: custom_components/mikrotik_router/device_tracker.py:72
Integration: Device Tracker (documentation, issues)
First occurred: 04:42:10 (2 occurrences)
Last logged: 05:07:10

Error while setting up mikrotik_router platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mikrotik_router/device_tracker.py", line 110, in async_setup_entry
    await async_add_entities(hass, config_entry, dispatcher)
  File "/config/custom_components/mikrotik_router/device_tracker.py", line 89, in async_add_entities
    await async_update_controller(
  File "/config/custom_components/mikrotik_router/device_tracker.py", line 72, in async_update_controller
    data = coordinator.data[entity_description.data_path]
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

```

Software versions:
- Home Assistant version: HA 2023.9.2
- Mikrotik Router integration version:v2.1.3
- Mikrotik Hardware: CRS305-1G-4S+
- RouterOS version: v7.11.2

_Originally posted by @alexdelprete in https://github.com/tomaae/homeassistant-mikrotik_router/issues/301#issuecomment-1717941639_

**Comment by tomaae** [comment]
@alexdelprete I'm not able to reproduce this, can you give me step by step to reproduce this issue?

**Comment by alexdelprete** [comment]
I'm able to reproduce it every time. I reconfigure without modifying anything:

![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/7027842/744639d6-06fe-4f6e-be0c-8cf5fe55a1bd)
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/7027842/cd7ed1ec-4b92-4664-8172-e6c4d28a5e60)

I receive a confirmation and the integration reloads. Then I go to the logs (I just did it) and I see this:

![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/7027842/eac12e15-2cc6-4c50-8c96-ec320e809fa8)

**Comment by tomaae** [comment]
which integration version are you using?

**Comment by alexdelprete** [comment]
v2.1.3

**Comment by tomaae** [comment]
ah okey, test with 2.1.4.
2.1.3 may had this issue, it was fixed in master

**Comment by alexdelprete** [comment]
> ah okey, test with 2.1.4. 2.1.3 may had this issue, it was fixed in master

So there was actually a bug. :)

Thanks for the quick fix. I'll test it and let you know...

**Comment by tomaae** [comment]
Yea, it was something that was fixed before you opened the issue :)
Forgot it was just in master, thats why I got confused why this happens

**Comment by alexdelprete** [comment]
You assumed I was using master branch. It happens also to me sometimes with my ABB integration. Too many things to follow. :)
