### ISSUE TITLE
[Bug] Duplicate names in device

### ISSUE THREAD

**Issue by mvdwetering** [tomaae/homeassistant-mikrotik_router#306]
## Describe the issue

I noticed that devices in exposed by the integration have duplicate names in the device. I think it is new as I did not notice it before.

I noticed first in the update dialog
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/732514/00b64575-d891-484d-8ad0-6d320e0b0254)

In this case "hAP ac³" is the name I gave it when adding the integration. The integration itself seems to add the device model.

## How to reproduce the issue

Add router to integration, go to the device exposing the update entity.

## Expected behavior

A clear name for devices.

I see why the integration name + something method is used as a lot of stuff is exposed as devices to have it all managable.

Maybe just not duplicate the name for the main router/unit device? 
or call it with a different postfix than model name, but can't come up with something good. Thought about "hAP ac3 main",  "hAP ac3 unit", but don't like any of them.

FYI there is a discussion in the architecture repo about subdevices which may (or may not) help in the future https://github.com/home-assistant/architecture/discussions/957

## Software versions

 - Home Assistant version: 2023.9.2
 - Mikrotik Router integration version: 2.1.3
 - Mikrotik Hardware:  hAP ac3, wAP AC and RB4011iGS+ something, with wifi
 - RouterOS version: 7.11.0 or 7.11.2 depends on device

## Additional context

Edit:
Actually after writing all this, maybe it is more noticable for me because I name the routers by the model. Not sure how I would name them otherwise...

Hmmm... I also see duplication on the devices added for the client traffic.
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/732514/3f00b669-87f7-48e7-bfa6-54f3d889e3f2)

The RX/TX sensors have the device name included. This means that in some contexts HA shows "MICHEL-PC2 MICHEL-PC2 TX"
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/732514/bd3a9fc9-a1ee-4870-9b18-8be2e60c1227)

**Comment by tomaae** [comment]
I dont see what is a problem here. Everything is based on the integration instance you named. part of it is router itself (as system device in the list) which is represented by its model name.
Standard naming is: Instance, Device, Entity

In case of device tracker, that one is weird, I havce to look into it.

**Comment by mvdwetering** [comment]
Ah, ok. I got confused to t the double "hAP ac" in the name, but I see where it is coming from.
Thanks for fixing the other entity names with 2.14 👍
