### ISSUE TITLE
[Bug] error log about kid control (which is not enabled)

### ISSUE THREAD

**Issue by SamJongenelen** [tomaae/homeassistant-mikrotik_router#314]
## Describe the issue

HA log contains error. I use routeros 7rc1 and have indeed not enabled kid control. Also have not checked kid control in the integration.

I guess I can ignore this error, but I would not have expected it as I did not check the box

>  This error originated from a custom integration.

Logger: custom_components.mikrotik_router.coordinator
Source: custom_components/mikrotik_router/coordinator.py:2407
Integration: Mikrotik Router (documentation, issues)
First occurred: 19:35:38 (1 occurrences)
Last logged: 19:35:38

No kid control devices found on your Mikrotik device, make sure kid-control feature is configured
## Software versions

 - Home Assistant version: 
 - Mikrotik Router integration version: 
 - Mikrotik Hardware: 
 - RouterOS version:

**Comment by tomaae** [comment]
This is not a bug and is not related to kid control in HA. But client traffic, which is handled by kid control.
https://github.com/tomaae/homeassistant-mikrotik_router#client-traffic
