### ISSUE TITLE
[Bug] Wireless clients always shows 0

### ISSUE THREAD

**Issue by DIMMonchik** [tomaae/homeassistant-mikrotik_router#317]
## Describe the issue

Wireless clients always shows 0.

## Software versions

 - Home Assistant version: 2023.10.1
 - Mikrotik Router integration version: 2.1.4
 - Mikrotik Hardware: hAP ac^2
 - RouterOS version: 7.11.2 (stable)

**Comment by tomaae** [comment]
pretty sure I seen someone reporting this already.
do you have host tracking enabled?

**Comment by DIMMonchik** [comment]
> pretty sure I seen someone reporting this already. do you have host tracking enabled?

[https://drive.google.com/file/d/1bjrSpBEMembYDgHJ3HZed5ZnBKmUIww0/view?usp=sharing](https://drive.google.com/file/d/1bjrSpBEMembYDgHJ3HZed5ZnBKmUIww0/view?usp=sharing)

**Comment by tomaae** [comment]
ok, can you attach integration diagnostics data?

**Comment by DIMMonchik** [comment]
[config_entry-mikrotik_router-82bc866e19f82f6526cf6c88002acda9.json.txt](https://github.com/tomaae/homeassistant-mikrotik_router/files/12904621/config_entry-mikrotik_router-82bc866e19f82f6526cf6c88002acda9.json.txt)


> ok, can you attach integration diagnostics data?

**Comment by tomaae** [comment]
thats because you dont have any wireless clients on that device.
      "wireless": {},
      "wireless_hosts": {},

**Comment by DIMMonchik** [comment]
> thats because you dont have any wireless clients on that device. "wireless": {}, "wireless_hosts": {},

![2023-10-24_08-42-29](https://github.com/tomaae/homeassistant-mikrotik_router/assets/38500475/8e6abca7-ddaf-44f4-aede-5e6586c68b6a)

**Comment by Zarox666** [comment]
I cannot repro:

![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/115449639/4b586342-1000-4d19-b0a3-0627b23b9e6c)

Unfortunately the docu says little about what sensor in the config is for what, but if I am not mistaken your need "Port tracker sensors" enabled to get these statistics.

**Comment by DIMMonchik** [comment]
> I cannot repro:
> 
> ![image](https://user-images.githubusercontent.com/115449639/278295447-4b586342-1000-4d19-b0a3-0627b23b9e6c.png)
> 
> Unfortunately the docu says little about what sensor in the config is for what, but if I am not mistaken your need "Port tracker sensors" enabled to get these statistics.

I have this option enabled

**Comment by Zarox666** [comment]
Only other Sensor that I have enabled besides Device Tracker is "Environmental Variable Sensors".
Have you tried this?

Might not sound very logic at first, but as it gives the overall number of Wifi Clients, not seperated by the different Ports, Interfaces or Networks, it must be a very global source sensor.

**Comment by DIMMonchik** [comment]
> Only other Sensor that I have enabled besides Device Tracker is "Environmental Variable Sensors". Have you tried this?
> 
> Might not sound very logic at first, but as it gives the overall number of Wifi Clients, not seperated by the different Ports, Interfaces or Networks, it must be a very global source sensor.

when this sensor is turned on, the integration stops working

**Comment by Zarox666** [comment]
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/115449639/cfdfe1c7-78c9-4b74-814f-abe162b3ae56)

That sounds, that there is something seriously wrong.
Have you tried uninstalling/reinstalling the integration?

**Comment by jfjeronimo** [comment]
Same here, I never get wifi clients in homeassistant with this integration ( 2 years ago), I think is same diferente configuration in mikrotik like dhcp manual config or arp, but I dont know... I need investigate how get the wifi clients to found the problem.

**Comment by jfjeronimo** [comment]
Hi,

I solved it yesterday, I made a couple of changes in Mikrotik and reload the mikrotik integration in HA and works.

1, Fix permissions in mikrotik following tutorial ( I had too much permissions, strange but... )
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/16325054/1238c0de-332b-4ab5-9e57-537e65b47e42)

2, Remove Acl by Mac in Wireless devices (really useless today). 

And.. ready!

![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/16325054/82c39ce8-26ba-4d6c-b1d3-7b9109ef5aec)

I hope help you @DIMMonchik !!

**Comment by tomaae** [comment]
No idea what is happening in your case.
Can you run integration in debug? we should find out more that way.

**Comment by tomaae** [comment]
I need those debugs to figure out whats wrong

**Comment by VolleyTom8** [comment]
Hallo,Could you Tell me which Logs you Need, because I‘m New With HomeAssistant.BR TomAm 18.12.2023 um 01:22 schrieb Tomaae ***@***.***>:﻿
I need those debugs to figure out whats wrong

**Comment by tomaae** [comment]
Sure. 
First, follow instruction here to enable debug logs for integration and restart home assistant afterwards:
https://github.com/tomaae/homeassistant-mikrotik_router?tab=readme-ov-file#enabling-debug

Let it run for about 2 minutes, then download diagnostics:
https://github.com/tomaae/homeassistant-mikrotik_router?tab=readme-ov-file#diagnostics

Download /config/home-assistant.log file from you HA.

Afterwards revert debug config changes and restart HA again.

**Comment by VolleyTom8** [comment]
I activated the logging and downloaded the file. Could I mail this directly to you, because there a IP/MAC/etc. inside.
BR Tom

**Comment by VolleyTom8** [comment]
> I activated the logging and downloaded the file. Could I mail this directly to you, because there a IP/MAC/etc. inside. BR Tom

I had a look at the logs and found the following:

```
2023-12-20 21:23:55.231 ERROR (MainThread) [custom_components.mikrotik_router.coordinator] Unexpected error fetching MyRouter-AC3 data: '*1'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mikrotik_router/coordinator.py", line 599, in _async_update_data
    await self.hass.async_add_executor_job(self.get_wireless)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mikrotik_router/coordinator.py", line 1967, in get_wireless
    self.ds["wireless"][uid][tmp] = self.ds["wireless"][
                                    ^^^^^^^^^^^^^^^^^^^^
KeyError: '*1'
```
Hope this helps.
br
Tom

**Comment by VolleyTom8** [comment]
Do you need something Else from my Site?

**Comment by mainTAP** [comment]
it might be related to this issue: a Chateau running 7.12 only shows wireless clients at the 2ghz wireless interface, and the clients from the 5ghz are not included in the wireless count

**Comment by fineryx** [comment]
Hello, im getting the same error. I have this in the log. 
`Logger: custom_components.mikrotik_router.mikrotikapi
Source: custom_components/mikrotik_router/mikrotikapi.py:95
Integration: Mikrotik Router ([documentation](https://github.com/tomaae/homeassistant-mikrotik_router), [issues](https://github.com/tomaae/homeassistant-mikrotik_router/issues))
First occurred: February 2, 2024 at 22:52:07 (37 occurrences)
Last logged: 01:37:40

    Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
    Mikrotik 192.168.88.1 error while building list for path /system/script/environment : not enough permissions (9)`
