### ISSUE TITLE
Not see mikrotik ethernet ports[Bug]

### ISSUE THREAD

**Issue by tothtechnika** [tomaae/homeassistant-mikrotik_router#322]
## Screenshots

<img width="1379" alt="Képernyőfotó 2023-11-08 - 23 07 42" src="https://github.com/tomaae/homeassistant-mikrotik_router/assets/33352971/a01bcafe-1bc7-4dbb-b5e2-66537020ad0f">
<img width="325" alt="Képernyőfotó 2023-11-08 - 23 07 58" src="https://github.com/tomaae/homeassistant-mikrotik_router/assets/33352971/248e65e4-aea6-4f4b-8a2e-12df0ddb8cf5">

## Software versions

Home Assistant 2023.10.5
Supervisor 2023.11.0
Operating System 9.5
 - Mikrotik Router integration version: 
 - Mikrotik Hardware: RB4011iGS
 - RouterOS version: 6.48.6

**Comment by tomaae** [comment]
hmm, you have same hardware as I do.
can you upload diagnostics?

**Comment by tothtechnika** [comment]
Yes: [config_entry-mikrotik_router-cd6e9998da6577b24d2981052877370c.json.txt](https://github.com/tomaae/homeassistant-mikrotik_router/files/13304912/config_entry-mikrotik_router-cd6e9998da6577b24d2981052877370c.json.txt)

**Comment by tomaae** [comment]
I can see interfaces available in diagnostics. check in case you hidden those entities

**Comment by tothtechnika** [comment]
I also see it in the diagnostics, but not in the home assistant. It used to work. I can't see it now. I used it to check the current bandwidth of the ether2 port (this is my wan port)

**Comment by tothtechnika** [comment]
entity not available:: sensor.mikrotik_rb4011igs_cpu_load_2
entity not available:: sensor.mikrotik_rb4011igs_memory_usage_2
entity not available:: sensor.mikrotik_ether2_rx
entity not available:: sensor.mikrotik_ether2_tx

it's definitely not working for over a month. Maybe since I updated HA
