### ISSUE TITLE
HA not showing new ROS update available

### ISSUE THREAD

**Issue by dragonat0r** [tomaae/homeassistant-mikrotik_router#323]
## Describe the issue
Does not show that there is new update

## Screenshots

![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/115716771/1a20449f-165e-4094-8696-a1aa3e3fbeaa)

![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/115716771/10da3482-4f29-4005-a4cc-064af5394222)

## Software versions

 - Home Assistant version: HA 2023.11.1
 - Mikrotik Router integration version:  v.2.1.4
 - Mikrotik Hardware:  hAP ax^3
 - RouterOS version: 7.12rc4

## Diagnostics data

part from log:

2023-11-09 11:44:44.198 DEBUG (SyncWorker_8) [custom_components.mikrotik_router.mikrotikapi] API query: /system/package/update
2023-11-09 11:44:44.199 DEBUG (SyncWorker_8) [custom_components.mikrotik_router.apiparser] Processing source [{'channel': 'stable', 'installed-version': '7.12rc4', 'latest-version': '7.11.2', 'status': 'New version is available'}]
2023-11-09 11:44:44.199 DEBUG (SyncWorker_8) [custom_components.mikrotik_router.apiparser] Processing entry {'channel': 'stable', 'installed-version': '7.12rc4', 'latest-version': '7.11.2', 'status': 'New version is available'}

**Comment by tomaae** [comment]
there should be more in a log after that

**Comment by dragonat0r** [comment]
log attached, filtered with "mikrotik" word

[log.txt](https://github.com/tomaae/homeassistant-mikrotik_router/files/13321305/log.txt)


hope this is enough

**Comment by tomaae** [comment]
debug looks fine, no problem there.
I tried to reproduce the issue but I cannot. works fine with testing channel too.
Can you upload integration diagnostics too? Maybe there will be some lead.

**Comment by dragonat0r** [comment]
integration diagnostics are attached
[config_entry-mikrotik_router-c285b569e9788a97ead78a8d41417ae7.json.txt](https://github.com/tomaae/homeassistant-mikrotik_router/files/13325473/config_entry-mikrotik_router-c285b569e9788a97ead78a8d41417ae7.json.txt)


Meanwhile  i observe some records into integration logbook like this:

Mikrotik BB hAP ax^3 RouterBOARD firmware update turned off
14:37:39 - 1 minute ago
Mikrotik BB hAP ax^3 Uptime changed to November 7, 2023 at 23:55
14:37:39 - 1 minute ago
Mikrotik BB hAP ax^3 RouterOS update turned off
14:37:39 - 1 minute ago
Mikrotik BB hAP ax^3 RouterBOARD firmware update became unavailable
14:37:36 - 1 minute ago
Mikrotik BB hAP ax^3 RouterOS update became unavailable
14:37:36 - 1 minute ago

**Comment by dragonat0r** [comment]
I think i found the reason for not showing new ROS update

probably when comparing current and available versions, integration counts only 7.12 part. Does not take on count rc4, in that case


  Installed version
          7.12rc4
          Latest version
          7.12


          
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/115716771/3c4bfe30-ef4b-478d-9bc4-539425f6088c)


for example when versions differ, integration notes that there is an update:

 Installed version
          7.12rc4
          Latest version
          7.13beta1

![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/115716771/e2d58985-71a7-4341-8d01-31f36286ba5b)

**Comment by tomaae** [comment]
yea, it may have issues with text in version number. nto sure what I can do about it tho.
