### ISSUE TITLE
Mikrotik router on Docker HA [Question]

### ISSUE THREAD

**Issue by snycko** [tomaae/homeassistant-mikrotik_router#326]
Hello,

I am running Home Assistant in docker, therefore HACS is not available.
Is it possible to install it also without HACS ?
If so, could you please explain how or at least guide me to some direction ?

Thanks.

Regards,
snyco

**Comment by L2jLiga** [comment]
Hi there,
You have to mkdir `custom_components` in your HA config PVC
Then just copy HACS / Mikrotik integration into that directory
