### ISSUE TITLE
Plans for, or ways to read, dynamic counters?

### ISSUE THREAD

**Issue by Extrapilot1** [tomaae/homeassistant-mikrotik_router#327]
Hi. At present, the integration seems to limit totals counters to core components as listed in the api query for /interface. There are dynamic counters created with things like firewall rules, and with devices that would be helpful to have in the integration. It does not return device counters, where those are returned under /ip/kid-control/device (bytes up/down). Likewise, it does not query for firewall data- (bytes, or packets) for IPv4 or v6. 

I recall mention that with v7 Router OS there were to be some changes to the integration as regards counters, but I dont know if that is still in work, or if this was overlooked, etc. 

Thank you-
Rob

**Comment by tomaae** [comment]
No, there are no plans for this. HA DB does not like fast changing entities like that, it would grow very fast.
