### ISSUE TITLE
[Question] How to delete entities

### ISSUE THREAD

**Issue by c0mplex1** [tomaae/homeassistant-mikrotik_router#333]
Hello!

Thanks for your great Home Assistant integration.

In HA, how can I delete entities created by the router from network devices that no longer exist ?
(Settings > Devices & services > Integrations > Mikrotik)
I did not find any option to remove them.
Had to manually remove entries in core.device_registry file... but I don't like that !

Thanks for the great job !

**Comment by tomaae** [comment]
same as any other unused entities. clock on them and press delete.
if delete is grayed out, you need to restart HA to release them.

**Comment by c0mplex1** [comment]
This does not work... delete button is grayed out.
![afbeelding](https://github.com/tomaae/homeassistant-mikrotik_router/assets/81088928/7c40fc90-1322-444b-bebc-085d8aece2bb)

**Comment by tomaae** [comment]
that is not obsolete entity, but manually disabled one.
