### ISSUE TITLE
[Question] Why not all NAT rules showing as switches

### ISSUE THREAD

**Issue by eiakovlev** [tomaae/homeassistant-mikrotik_router#335]
Hi,
Could you explain how NAT switches are adding as objects, What is the criteria? 
I have several NAT rules with different parameters: some of them are masquerade rules with different source networks and destination networks - address lists, some other are dst-nat rules with different Comments.
Actually added only couple of rules - only dst-nat and with simple comments - at least without "(" , "|", ")" symbols in comments.
So i need to create scripts to enable/disable rules.

Thanks.

**Comment by tomaae** [comment]
All dst-nat are added, as long as unique id can be built. If there is conflict, you will see it in HA log.
https://github.com/tomaae/homeassistant-mikrotik_router/blob/a61dfa5ff7e1e6d2b744e0cdfeee08377e277e2d/custom_components/mikrotik_router/coordinator.py#L972-L991

**Comment by tomaae** [comment]
srcnat rules are not listed, no
