### ISSUE TITLE
Router OS 7.13, integration not work

### ISSUE THREAD

**Issue by fezo76** [tomaae/homeassistant-mikrotik_router#336]
Hello! I updated the Mikrotik OS to 7.13
Unfortunately, the Mikrotik integration does not work after the update.
Integration message: "failed setup, will retry.
Mikrotik log: user1 logged in and immediately logged out

Thank you!

**Comment by fezo76** [comment]
sorry, I see now that there was already such a post. it is true that it still applied to the beta.

**Comment by tomaae** [comment]
related to #328
