### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ranrinc2** [tomaae/homeassistant-mikrotik_router#338]
## Describe the issue
Mikrotik Router fail to connect to my router period.

## How to reproduce the issue
After the latest update on HA its now unable to detect my router

## Expected behavior
working properly

## Screenshots
![CleanShot 2024-01-03 at 09 01 02](https://github.com/tomaae/homeassistant-mikrotik_router/assets/85998380/b1e66bba-585f-44ae-bc2a-df44f6fb2093)

## Software versions

 - Home Assistant version: 2023.12.4
 - Mikrotik Router integration version: v2.1.4
 - Mikrotik Hardware: hAP ac³
 - RouterOS version: v7.13

## Traceback/Error logs
This error originated from a custom integration.

Logger: custom_components.mikrotik_router.mikrotikapi
Source: custom_components/mikrotik_router/mikrotikapi.py:95
Integration: Mikrotik Router (documentation, issues)
First occurred: 8:53:40 AM (20 occurrences)
Last logged: 9:13:49 AM

Mikrotik 192.168. error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix

**Comment by L2jLiga** [comment]
Duplicates https://github.com/tomaae/homeassistant-mikrotik_router/issues/328

PR with fix: https://github.com/tomaae/homeassistant-mikrotik_router/pull/332

**Comment by erkedocara** [comment]
same problem with hap ax3 ros 7.13 stoped working

**Comment by tomaae** [comment]
7.13 is not yet supported. it will take me a bit to catch up to everything after my vacation

**Comment by M0DDer** [comment]
It Works even at 7.14 !

With this
[custom_components/mikrotik_router/coordinator.py](https://github.com/tomaae/homeassistant-mikrotik_router/pull/332/files/1bbedfaa8b411553876b8cb9454d925bb284a2b2#diff-4a39d7d77d0cdde5dca3c20452a70e10c9b684d6b94524b0e46a71389d109572)

and this
[custom_components/mikrotik_router/coordinator.py](https://github.com/tomaae/homeassistant-mikrotik_router/pull/332/files/1bbedfaa8b411553876b8cb9454d925bb284a2b2#diff-4a39d7d77d0cdde5dca3c20452a70e10c9b684d6b94524b0e46a71389d109572)

**Comment by zandhaas** [comment]
> It Works even at 7.14 !
> 
> With this file, added manualy [custom_components/mikrotik_router/coordinator.py](https://github.com/tomaae/homeassistant-mikrotik_router/pull/332/files/1bbedfaa8b411553876b8cb9454d925bb284a2b2#diff-4a39d7d77d0cdde5dca3c20452a70e10c9b684d6b94524b0e46a71389d109572)
> 
> and this changes [[custom_components/mikrotik_router/coordinator.py](https://github.com/tomaae/homeassistant-mikrotik_router/pull/332/files/1bbedfaa8b411553876b8cb9454d925bb284a2b2#diff-4a39d7d77d0cdde5dca3c20452a70e10c9b684d6b94524b0e46a71389d109572)]([#332 (comment)](https://github.com/tomaae/homeassistant-mikrotik_router/pull/332#issuecomment-1890752107))

Works for me Also
