### ISSUE TITLE
Integration didn't pick-up my Netwatch items

### ISSUE THREAD

**Issue by aurimas-btk** [tomaae/homeassistant-mikrotik_router#339]
Hello, team.

Could you explain please what needs to be configured  that Integration (2.1.4) could pick-up Netwatch Items from Mikrotik RB1100x4 (7.11 as well as 7.13)? 
Hosts are retrieved, ports are retrieved also, but there is no such choice in Integration configutation as Netwatch Tracking (I expected some as per features description in documentation). 

Bug, feature, or lack of understanding how things work from my side😉?

**Comment by tomaae** [comment]
Looking at code, you just need to enable it in integration configuration.

**Comment by aurimas-btk** [comment]
Could you please advice, witch option in configuration screen would enable this feature? 
![IMG_20240215_074541](https://github.com/tomaae/homeassistant-mikrotik_router/assets/129221514/342be5b8-d954-4602-a472-9bab9e2ab7b3)

**Comment by tomaae** [comment]
you need to use master version if you want to use netwatch now. its not available in release version yet.

**Comment by tomaae** [comment]
you can wait for release or use master version
