### ISSUE TITLE
[Bug] 'Failed setup, will retry' only for a couple of RBs

### ISSUE THREAD

**Issue by rinners** [tomaae/homeassistant-mikrotik_router#341]
## Describe the issue
Integration accepts login credentials, but fails to load after initializing. The API user can be briefly seen in Winbox for about 1s then disappears

## How to reproduce the issue
1. Add entry
2. Enter correct details, IP, u/n, p/w etc
3. Submit

## Expected behavior
Device to initialize and show devices and entities as it does on the other switch (same model).

## Software versions
All fields in this sections are required.
 - Home Assistant version: HA 2024.2.1 
 - Mikrotik Router integration version:  v.2.1.4 
 - Mikrotik Hardware: RB4011 & CRS328 both have this issue 
 - RouterOS version:  v7.13.4 

## Diagnostics data
Unable to download diagnostic data

## Additional context
I have another CRS328 on the same network that works as expected and multiple APs.

**Comment by tomaae** [comment]
duplicate #328
