### ISSUE TITLE
[Bug] Filter rules removed as duplicate, miscalculated unique ID?

### ISSUE THREAD

**Issue by baylanger** [tomaae/homeassistant-mikrotik_router#344]
## Describe the issue

This is my first installation of this integration, the current release. I'm facing the same issue that was described in #141 and since it's my first ever installation, I'm not sure if code changes that happened later might have broke the unique ID.

Per the commit referenced in issue #141, src-address-list was added to the unique ID filters list but somehow, the 2 rules below generates an error, even if they should have unique IDs.

```
add action=dst-nat chain=dstnat dst-port=443 protocol=tcp src-address-list=CF4 \
    to-addresses=1.1.1.1 to-ports=443
add action=dst-nat chain=dstnat dst-port=443 protocol=tcp src-address-list=2 \
    to-addresses=1.1.1.1 to-ports=443
```
Note: the to-addresses isn't the actual IP in the rule, just masking my IP.

## Expected behavior
Rules should have unique IDs.

## Software versions
 - Home Assistant version: HA 2024.2.1
 - Mikrotik Router integration version: v2.1.4
 - Mikrotik Hardware: RB5009UG+S+
 - RouterOS version: v7.12.1

## Diagnostics data
The json file doesn't show any of the 2 rules above.

## Traceback/Error logs
```
ERROR (SyncWorker_62) [custom_components.mikrotik_router.coordinator] Mikrotik gw.xxxxxxx.com duplicate NAT rule tcp:443, entity will be unavailable.
```

**Comment by baylanger** [comment]
I just noticed that commit for #141 might not cover NAT rules, that probably explains why.

**Comment by tomaae** [comment]
That rule is only in mangle and filters, not NAT.
it is correct behavior.

**Comment by baylanger** [comment]
I'm curious, today the reason not to add the filters for NAT is still to prevent current users to have their sensors' data reset or am I missing something else? It's just not clear in my mind when reading #141

If it's to prevent a reset, I guess a "toggle switch" (off by default) could be added via the tool to either include or not added filters for NAT but I know this isn't probably best option... and I realized moments ago, one of the src-address-list has a single IP, so I can move it to src-address and I'll get a unique-id for that one.

**Comment by tomaae** [comment]
yes, changing unique ID would break all existing sensors in that category for everyone.
This is something I dont like changing for that reason, unless its really necessary.
