### ISSUE TITLE
[Bug] Upgraded my hap ax2 to 7.13.4 error mesage failed setup will retry

### ISSUE THREAD

**Issue by GiannisDorokidis** [tomaae/homeassistant-mikrotik_router#345]
## Describe the issue
 I upgraded my hap ax2 drom 7.12 to 7.13.4 and now the integration doesnt work anymore the error it gives is: Failed setup , will retry

## How to reproduce the issue
 
Needs attention
Failed seup, will retry

## Expected behavior
 it should work normaly and display entity data and let me toggle interfaces

## Screenshots

![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/60039054/3bcc6683-61a8-4eb0-9bb7-4ad6aea48227)

## Software versions

 - Home Assistant version: 
 - Mikrotik Router integration version: 
 - Mikrotik Hardware: 
 - RouterOS version: 

## Traceback/Error logs
This error originated from a custom integration.

Logger: custom_components.mikrotik_router.mikrotikapi
Source: custom_components/mikrotik_router/mikrotikapi.py:95
Integration: Mikrotik Router (documentation, issues)
First occurred: 22:10:49 (57 occurrences)
Last logged: 23:11:05

Mikrotik 192.168.10.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix

## Additional context
 packages installed on the mikrotik are router os and wifi-qcom

**Comment by tomaae** [comment]
7.13 is only supported in master, not in release yet
