### ISSUE TITLE
[Bug] unable to install version from master via HACS

### ISSUE THREAD

**Issue by L2jLiga** [tomaae/homeassistant-mikrotik_router#346]
## Describe the issue

Unable to install version from master branch via HACS

## How to reproduce the issue

1. Open HA
1. Navigate to HACS
1. Click "Explore and download repositories"
1. Search for any with for "Mikrotik Router" integration and click on it
1. Click "Download"
1. In "Select version" dropdown choose "master"
1. Click "Download"

## Expected behavior

Integration installed successfully

## Software versions

 - Home Assistant version: HA 2024.2.1
 - Mikrotik Router integration version: master
 - Mikrotik Hardware: n/a
 - RouterOS version: n/a

## Diagnostics data

This is happens because `hacs.json` contains `"zip_release": true`, so HACS trying to download "master" release and expectly fails with 404 error.

I've created issue in HACS firstly, however HACS maintainer answered that it's expected behavior.

https://github.com/hacs/integration/issues/3513

**Comment by tomaae** [comment]
well, since HACS decided it will no longer be possible to install master this way, it wont be possible. Nothing I can do there. Obviously, zip release cannot be generated for master, so I will be disabling master from HACS.
Too bad they removed this feature.
