### ISSUE TITLE
[Bug] CCR1016-12G  will not connect

### ISSUE THREAD

**Issue by Po3uk** [tomaae/homeassistant-mikrotik_router#347]
I have a total of three Mikrotiks in my network, two connect without problems, but the CCR1016-12G has a problem. Where can the error be?

**Comment by tomaae** [comment]
you will need to give more information. always use full issue template

**Comment by Po3uk** [comment]
I don't know what the rest will be if I have two Mikrotiks working but this one with the same setup doesn't but oh well.

## Describe the problem
Mikrotiks RB962UiGS-5HacT2HnT connect without a problem. Mikrotik CCR1016-12G with the same settings, version and everything around no.


## How to reproduce the problem
I don't know.


## Expected behavior
I was expecting a setup.


## Screenshots
Not necessary. Mikrotik just won't connect.


## Software version

   - Home Assistant version: 2024.2.1
   - Mikrotik router integration version: v.2.1.4
   - Mikrotik Hardware: CCR1016-12G
   - RouterOS version: 7.13.4 in all


## Diagnostic data
error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix


## Traceback/error logs
I think the caps-man error is enough.


## More context
He is not proper

**Comment by tomaae** [comment]
duplicate #328
