### ISSUE TITLE
Hap ax3

### ISSUE THREAD

**Issue by neosilviu** [tomaae/homeassistant-mikrotik_router#348]
it doesn't work with hap ax2 and hap ax3

**Comment by riddley** [comment]
This is #304

**Comment by RafaG** [comment]
I have an hap ax2 with the same problem. Any workaround?

**Comment by riddley** [comment]
The one found in the other ticket that I linked to yesterday.

**Comment by udivankin** [comment]
same with cAP ax and hAP ax2. "Failed to set up"

**Comment by marlovh** [comment]
FWIW, I have the same issue (" Failed to set up") using a hAP ax3 and hAP ax2. Disabling and Re-enabling the integration prompts "Restart Home Assistant to finish enabling this integration" in my case. Restart of HA and/or complete reboot of the rpi running HA does not solve this.

**Comment by pi-ledge** [comment]
Any update on this issue? Still not wprking on HAP ax² and HAP ax³.
Downgrade to ROS 7.12 and it works as it should ...

**Comment by Turbovix** [comment]
Still not working in version ROS 7.14.2

**Comment by fusionstream** [comment]
remain unstale please

**Comment by tomaae** [comment]
I will be closing this one, as "not working on ax2/3" is not really something I can work with. 
you can reopen the issue once you add required details.
