### ISSUE TITLE
[Bug] Traffic TX/RX Total incorrect

### ISSUE THREAD

**Issue by KoalaBear84** [tomaae/homeassistant-mikrotik_router#352]
## Describe the issue
The values shown/detected in Home Assistant are ~7.5 times less than the values in Mikrotik.

## How to reproduce the issue
1. Add Mikrotik integration
2. See values reported

## Expected behavior
Correct values as seen in Mikrotik

## Screenshots
**Mikrotik:**
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/5886900/ba706a19-097e-4c0b-a24a-160a310ee34d)

**Home Assistant:**
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/5886900/cf778b2b-6ecb-4a18-b42d-e27ce2e4fbca)

It was rebooted ~ 12.5 hours ago, and it started counting again (which is good):
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/5886900/68770d35-df83-4fc3-ba9e-11c5f0d531a0)

## Software versions
 - Home Assistant version: HA 2024.3.0
 - Mikrotik Router integration version: v2.1.4
 - Mikrotik Hardware: RB750Gr3
 - RouterOS version: 7.14.1

```
[admin@MikroTik] > /system/resource/print
                   uptime: 12h37m59s
                  version: 7.14.1 (stable)
               build-time: 2024-03-08 12:50:23
         factory-software: 6.46.3
              free-memory: 168.7MiB
             total-memory: 256.0MiB
                      cpu: MIPS 1004Kc V2.15
                cpu-count: 4
            cpu-frequency: 880MHz
                 cpu-load: 25%
           free-hdd-space: 2120.0KiB
          total-hdd-space: 16.0MiB
  write-sect-since-reboot: 78119
         write-sect-total: 19627118
        architecture-name: mmips
               board-name: hEX
                 platform: MikroTik
[admin@MikroTik] > /system/routerboard/print
       routerboard: yes
        board-name: hEX
             model: RB750Gr3
          revision: r4
     serial-number: ****
     firmware-type: mt7621L
  factory-firmware: 6.47.9
  current-firmware: 7.14
  upgrade-firmware: 7.14.1
```

## Diagnostics data
Removed bridge_host, arp, kid-control, dhcp, host, and client_traffic.

All the values in here are like the values from the Mikrotik terminal and screenshots, so that luckily is correct.

[config_entry-mikrotik_router-bff2ea65e24355c052f45769f1978e89-redacted.json](https://github.com/tomaae/homeassistant-mikrotik_router/files/14568073/config_entry-mikrotik_router-bff2ea65e24355c052f45769f1978e89-redacted.json)

## Additional context

**Comment by KoalaBear84** [comment]
Bump

**Comment by tomaae** [comment]
HA show average traffic since last pool, not realtime like mikrotik UI.
Btw, RouterOS 7.14.1 with v2.1.4 wont work, that would crash right away.

**Comment by KoalaBear84** [comment]
OK, maybe the issue was not clear. It's clear that the value in HA can be seconds/minutes old, depending on the polling interval, that's fine.

But HA reports RX total 18.3 GB / TX total 4.6 GB while it should be RX total 136.6 GB / TX total 34.6 GB. Please check the included config file to see that the values are not OK.

Relevant parts:
```json
{
  "data": {
    "data": {
      "interface": {
        "ether2": {
          "default-name": "ether2",
          "name": "ether2",
          "type": "ether",
          "rx-current": 149272510241,
          "tx-current": 38170446964,
          "rx-total": 149272510241,
          "tx-total": 38170446964
        },
        "glasnet": {
          "default-name": "glasnet",
          "name": "glasnet",
          "type": "pppoe-out",
          "rx-current": 54001823074,
          "tx-current": 148542453762,
          "rx-total": 54001823074,
          "tx-total": 148542453762
        }
      }
  }
}
```

149272510241 / 1024 / 1024 / 1024 = 139.0 GB
38170446964 / 1024 / 1024 / 1024 = 35.6 GB

Which is not anywhere close to 18.3 GB / 4.6 GB.

**Comment by tomaae** [comment]
Ah, you mean total.
This was fixed in a61dfa5ff7e1e6d2b744e0cdfeee08377e277e2d

**Comment by KoalaBear84** [comment]
Bump

**Comment by tomaae** [comment]
Like I said, this was already fixed. You can give master a test if you want.

**Comment by KoalaBear84** [comment]
OK, sorry for misunderstanding this. Because I tought "master" as in the released branch, not development.

Tried downloading this verison with HACS, but that fails. Removed the whole integration from HA, and from HACS. Tried to (re)install it again, but that fails. I'm guessing this will never work (as it isn't a release)?

```
Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:986
integration: HACS (documentation, issues)
First occurred: 07:47:58 (1 occurrences)
Last logged: 07:47:58

<Integration tomaae/homeassistant-mikrotik_router> Failed to download https://github.com/tomaae/homeassistant-mikrotik_router/releases/download/master/mikrotik_router.zip
```

How should it work? It's not specifically mentioned in:
https://github.com/tomaae/homeassistant-mikrotik_router?tab=readme-ov-file#using-mikrotik-development-branch

**Comment by tomaae** [comment]
try now

**Comment by KoalaBear84** [comment]
Thanks, it works. Would like to let you know that a checkbox has no title/label:
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/5886900/19c2f3bf-5d5a-4679-b78d-fbd137af90b9)

**Comment by tomaae** [comment]
hmm, I probably need to check out translations to github. thats not on your side.
