### ISSUE TITLE
[Bug] Mikrotik version info not updating

### ISSUE THREAD

**Issue by dannyvanderzande** [tomaae/homeassistant-mikrotik_router#355]
First off all.. thanks for the hard work on the integration. It works really well and I've used it happily for quite some time.

There is just one things that gives me problems. After upgrading a Mikrotik device the integration does not detect the new version. The update badge next to the settings button remains active at the number it had before the update. Reloading the integration removes the update notification for a few seconds only. Restarting HA completely also does not solve the issue.

The only way to get rid off the notifications is by using the "skip update" function.

I am using Home Assistant in a docker container. At the moment i'm running the following versions.
Core
2024.4.3
Frontend
20240404.2

All my MT devices are at version
7.14.3
I have a RB3011 and 3 HAP AC's.

The problem has been there for probably over a year so I doubt it's version related. However I never found the time to report it before today. If there's any additional info you need, please let me know.

Thanks for the hard work, it's really appreciated!

**Comment by skrashevich** [comment]
Try fix from #354

**Comment by dannyvanderzande** [comment]
@skrashevich I replaced the file from your fix. At first nothing seemed to have changed but after "installing" the updates through the HA interface again (even though the MT's were already up to date) the update notification seems to have gone away. Thanks :)
