### ISSUE TITLE
[Feature] Option to exclude device trackers from certain domains (ARP, etc)

### ISSUE THREAD

**Issue by clau-bucur** [tomaae/homeassistant-mikrotik_router#360]
## Is your feature request related to a problem? Please describe.

Device trackers created from the ARP list very often, in my case, create device trackers which are not valid.
When I join a new device to the networks it gets a dynamic IP and then I make it static in a different subnet. But the old dynamic IP remains active in the ARP list for quite some time (deleting it from the router does not help, it appears back).

## Describe the solution you'd like

Add some options which domains to be included when creating device trackers:
- ARP
- DHCP
- etc

## Describe alternatives you've considered

Commenting out lines 2045 -> 2052 in `cordinator.py`.

**Comment by clau-bucur** [comment]
@tomaae is it not doable?

**Comment by tomaae** [comment]
no, cant do this from HA side. you can only disable automatic creation of new entities.
