### ISSUE TITLE
[Bug]while building list for path /system/routerboard

### ISSUE THREAD

**Issue by sian-jing** [tomaae/homeassistant-mikrotik_router#363]
## Describe the issue
while building list for path /system/routerboard : no such command or directory (routerboard), no such command prefix

## Software versions

 - Home Assistant version: HA 2024.5.5
 - Mikrotik Hardware: CHR
 - RouterOS version: v7.15

**Comment by tomaae** [comment]
is /system/routerboard inaccessible on your system using cli?

**Comment by sian-jing** [comment]
![123](https://github.com/tomaae/homeassistant-mikrotik_router/assets/22487327/5d103ab3-aff7-4450-964e-85e9e6fd62d6)

**Comment by home110120** [comment]
Same issue here, seems something changed from 7.15 at least for CHR.

**Comment by jm3west** [comment]
Same here, CHR. No chance :-(

**Comment by smit60rus** [comment]
Same here, x86. No chance (

**Comment by home110120** [comment]
The issue should not be closed since it was not resolved.

**Comment by Albirew** [comment]
of course CHR has no routerboard submenu, since it's NOT routerboard but either a VM or an OS running on non-mikrotik hardware...

**Comment by tomaae** [comment]
It wont be closed, no worries. Thats just automatic actions and me not having much time at the moment.

Are we talking about cloud hosted router? 
Both x86 VM and CHR should work, unless mikrotik changed something. Can you give me output of /system/resource?

**Comment by Albirew** [comment]
Yes, CHR is meant to run as VM and x86 as bare metal on "normal" hardware.
Here /system/resource output:
```
[user@CHR] > /system/resource/print 
                   uptime: 1w10h21m40s
                  version: 7.15.2 (stable)
               build-time: 2024-06-26 11:42:37
              free-memory: 45.1MiB
             total-memory: 128.0MiB
                      cpu: Intel(R)
                cpu-count: 1
            cpu-frequency: 2394MHz
                 cpu-load: 2%
           free-hdd-space: 31.9MiB
          total-hdd-space: 59.5MiB
  write-sect-since-reboot: 2092336
         write-sect-total: 2092336
        architecture-name: x86_64
               board-name: CHR VMware, Inc. VMware Virtual Platform
                 platform: AlbiTik
[user@CHR] >
```
please ignore platform name, it's because i have custom branded index.

**Comment by tomaae** [comment]
looks like mikrotik changed board name, try master
