### ISSUE TITLE
Setup failed, will try again: Mikrotik Disconnected

### ISSUE THREAD

**Issue by ChanningCCapwell** [tomaae/homeassistant-mikrotik_router#364]
## Software versions

 - Home Assistant version: 
 - Mikrotik Router integration version: 
 - Mikrotik Hardware: 
 - RouterOS version:

**Comment by alirezadigi** [comment]
same issue here
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/47608350/94ae2007-ff7e-4b52-8b5c-7c9f265410d8)

**Comment by alirezadigi** [comment]
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/47608350/ad4c2785-31aa-44b7-870d-cbf58a3beeb7)

its the log file after reloading

**Comment by matissrapsa** [comment]
Same problem, Router OS 15,1, don't have Wi-Fi package for this router.
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/36150309/a824d33a-03ea-45af-b697-4d83baff6e38)

**Comment by matissrapsa** [comment]
Just in case there is temporally available workaround
https://github.com/tomaae/homeassistant-mikrotik_router/issues/328#issuecomment-1892676046

**Comment by alirezadigi** [comment]
Does anybody know how we can get more detailed logs? maybe we can create a pull request...

**Comment by matteop87** [comment]
This is the error on my logs: 
2024-06-25 15:14:55.448 ERROR (SyncWorker_52) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.1.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix

2024-06-25 15:14:55.449 DEBUG (MainThread) [custom_components.mikrotik_router.coordinator] Finished fetching Mikrotik data in 1.192 seconds (success: False)

For debug try this:
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/121861864/863b4b36-9929-4bfb-b536-bf2316bbedd9)

**Comment by garrettstoupe** [comment]
Installing the Master in Homeassistant has fixed the issue for me. Had to manually do this

**Comment by goro22052** [comment]
I have the same problem...
What the mean "Installing the Master in Homeassistant "?

**Comment by fabiojrsantos** [comment]
> [goro22052](/goro22052)

I think he meant user with root permission.

**Comment by garrettstoupe** [comment]
> I have the same problem...
> What the mean "Installing the Master in Homeassistant "?

Sorry downloaded the master zip file and unzipped it to /config/custom_components/mikrotik_router/

You may need to backup and remove the current /config/custom_components/mikrotik_router/ and restart ha

**Comment by tomaae** [comment]
You can choose master in HACS version selection.
I have not yet tested 7.15 at all, so not sure if it works. Best is to update to master and submit debugs if its not working.

**Comment by ilwalti** [comment]
Just installed version 2.1.4... of 3 routers I've configured, two works fine, the third one shows the "setup failed" problem.
Switched back to master, all ok.
BTW, working pieces are a cAP AC and an L009, the other is a cAP AX. All with 7.15.2 RouterOS on board...

**Comment by dcupaiolo** [comment]
I have version of MK 7.15.2 and I also have this problem, the error is similar to the one reported, can an option be made so that it does not check for the existence of the capsman module? I would think that this would momentarily resolve it. The log indicates

2024-07-16 18:51:56.554 DEBUG (SyncWorker_9) [custom_components.mikrotik_router.mikrotikapi] API query: /caps-man/registration-table
2024-07-16 18:51:56.555 ERROR (SyncWorker_9) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.31.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix

**Comment by tomaae** [comment]
you need to install master version for 7.13 and up.
its not about missing module, but mikrotik changing api paths

**Comment by alirezadigi** [comment]
@tomaae Thanks for your message. Is there anything that we can help with?

**Comment by tomaae** [comment]
you can install "master" version using HACS to confirm that its working. if its not, we can look into debugging the issue

**Comment by dcupaiolo** [comment]
> you need to install master version for 7.13 and up. its not about missing module, but mikrotik changing api paths

Hi, I tried the master version by downloading it from github and also following the steps in the issue https://github.com/tomaae/homeassistant-mikrotik_router/issues/328 and it worked for me

**Comment by matteop87** [comment]
I confirm that solution work correctly on my RB4011...

Ensuring beta features are disabled in HACS
Use Redownload in HACS, wait for the versions to be populated, select Master at the bottom of the list. Wait a bit
Reboot HA (**not just a quick restart**)
Do above again and again until it works

**I recommend that you completely restart home assistant after installing the master version, for me that was the error**

**Comment by gionag** [comment]
i got 
`error while building list for path /system/routerboard : no such command or directory (routerboard), no such command prefix`

that's because i use a chr, and there's no routerboard subsection under system (it runs on plain x86 machine...)
can i work around this ?
