### ISSUE TITLE
Port[Question]

### ISSUE THREAD

**Issue by Yamaha0014** [tomaae/homeassistant-mikrotik_router#365]
Hi I have big attack on my network where is Mikrotik. I have integration in HA and I need to change the port of API. Where the port is stored  from first configuration?
B. R. Andzia

**Comment by sshalyminov** [comment]
/config/.storage/core.config_entries 
But much easier is just to delete integration entry and add back - in a case if you don't have many customizations like renamed entries and etc.

**Comment by tomaae** [comment]
You cannot define port manually.
But you should never expose your API port to internet. Or even lock it down to specific IPs within your network if you dont trust it.
