### ISSUE TITLE
Integration version is missing (or wrong)

### ISSUE THREAD

**Issue by Cougar** [tomaae/homeassistant-mikrotik_router#367]
Somehow the `version` number has been missed a long time. This is the version that will be shown to the user

https://github.com/tomaae/homeassistant-mikrotik_router/blob/de1ca6a6f6cc37e37c9e6da216849bb5063e66f6/custom_components/mikrotik_router/manifest.json#L16

![Screenshot 2024-07-14 at 16-59-33 Settings – Home Assistant](https://github.com/user-attachments/assets/2e850154-3a6d-4d56-8906-b9549bd08f3e)

**Comment by tomaae** [comment]
Yes I know, I dont use internal version in any of my integrations. Its easy to forget about and then it causes real issues.

**Comment by Cougar** [comment]
It is usable for normal users where they can see if their integration is up to date or not. Right now there is no easy way to make sure that latest HACS is running. I don't know if this has any other advantage. It is definitely something that needs to be remembered and updated for every release at least.

**Comment by tomaae** [comment]
I will look into it, if it can be included by release automation. otherwise even master would have release version which will cause even more confusion during debugging
