### ISSUE TITLE
[Bug] Component Causing Excessive DNS Queries & Updates to Fail

### ISSUE THREAD

**Issue by jwshields** [tomaae/homeassistant-mikrotik_router#371]
## Describe the issue
Two "issues" can be manifested by this, I will be describing both of them.  
See the bottommost point "Additional information" for a link to where this behavior is triggered.

- A DNS query (for `upgrade.mikrotik.com`) is made by a device every **{refresh interval}**
  - I have two examples of conditions where this can happen
    - If you have this component set to refresh often (Ex, more often than once per minute)
    - If you have this component configured to check against multiple devices
  - In either condition, your DNS server is queried constantly for updates, and the number of requests is compounding the more devices you have and how frequently you refresh data
- If there is another active session on the device (ex: Winbox) and it is checking for or downloading packages, **when the component refreshes data** for the device, it will cause the package download or check in the Winbox session to be aborted
  - This can cause problems when attempting to upgrade devices via Winbox
  - It is not configurable whether or not an upgrade check is performed, even if the update sensors are disabled

## How to reproduce the issue
1. Configure the component for a device
2. Set the refresh interval to something like 30 seconds
3. To test for the compounding dns requests, configure additional devices
4. To test for failures, utilize Winbox to check for and download packages, the download will be aborted when the component refreshes data (ie, low interval)

## Expected behavior
1. The component doesn't cause my devices to slam my DNS servers
2. The component doesn't excessively check for updates (aka, spamming Mikrotik's servers)
3. The component doesn't cause package downloads/upgrades to fail

## Screenshots
N/A

## Software versions
 - Home Assistant version:
   -  Core 2024.8.2 / Supervisor 2024.08.0 / Operating System 13.1 / Frontend 20240809.0
 - Mikrotik Router integration version: 2.1.4
 - Mikrotik Hardware: RB5009UG+S+, RB960PGS, cAPGi-5HaxD2HaxD, CubeG-5ac60ad, RB924i-2nD-BT5&BG77, RB924iR0-2nD-BT5&BG77, RB4011iGS+5HacQ2HnD
 - RouterOS version: (All) Experienced on all ROS versions from 7.11->7.16rc2

## Diagnostics data
N/A

## Traceback/Error logs
N/A

## Additional context
https://github.com/tomaae/homeassistant-mikrotik_router/blob/de1ca6a6f6cc37e37c9e6da216849bb5063e66f6/custom_components/mikrotik_router/coordinator.py#L583

**Comment by jwshields** [comment]
Not stale

**Comment by jwshields** [comment]
Not stale....

**Comment by jwshields** [comment]
@tomaae Thoughts here?

**Comment by tomaae** [comment]
update query is every 4 hours, you can see it exactly where you linked the code.
 2.1.4 is not a valid integration version, maybe you are using something else that is causing this?
