### ISSUE TITLE
Integration doesn't work with RouterOS 7.15.3

### ISSUE THREAD

**Issue by fa35ife** [tomaae/homeassistant-mikrotik_router#375]
## Describe the issue

integration doesn't work

## How to reproduce the issue

Upgrade Router OS to 7.15.3   on device

## Expected behavior

It should work like on Router OS <7.13

## Screenshots

![Screenshot from 2024-10-02 22-56-56](https://github.com/user-attachments/assets/d803867c-af34-4414-80a4-ba1eaa94f049)
![Screenshot from 2024-10-02 22-58-10](https://github.com/user-attachments/assets/bcda2d41-84c6-4fee-9c95-5ea4bf3644a4)

## Software versions

 - Home Assistant version: HA 2024.9.3 
 - Mikrotik Router integration version: v2.1.4 
 - Mikrotik Hardware: L009UiGS-2HaxD 
 - RouterOS version: v7.15.3 

## Diagnostics data

  no

## Traceback/Error logs

This error originated from a custom integration.

Logger: custom_components.mikrotik_router.mikrotikapi
Source: custom_components/mikrotik_router/mikrotikapi.py:95
integration: Mikrotik Router (documentation, issues)
First occurred: 1 October 2024 at 02:17:29 (34 occurrences)
Last logged: 22:41:24

Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix

**Comment by djrawe** [comment]
Same problem

**Comment by arfoll** [comment]
I have it working with 7.16 using tip of master, pretty sure https://github.com/tomaae/homeassistant-mikrotik_router/commit/1bbedfaa8b411553876b8cb9454d925bb284a2b2 is fixing the issue you have with the wifi package changes. My router runs capsman (new one) and at least that works.

**Comment by pomah86** [comment]
Is there anyone who can merge this and release a new version? Seems like the maintainer does not have time for this anymore

**Comment by djexit** [comment]
The problem occurs with the wifi-qcom and wifi-qcom-ac packages because capsman is no longer available. The integration looks for the path "/caps-man/registration-table", which no longer exists. Now it should be "/caps-man/registration-table"

**Comment by pomah86** [comment]
> The problem occurs with the wifi-qcom and wifi-qcom-ac packages because capsman is no longer available. The integration looks for the path "/caps-man/registration-table", which no longer exists. Now it should be "/interface/wifi/registration-table"

I think that is established by now, the problem is that the maintainer does not have time to update this, and the forks that I have tried can not be used in HACS...

**Comment by 7lano** [comment]
same problem, same cause

`2024-10-18 02:02:33.921 DEBUG (SyncWorker_2) [custom_components.mikrotik_router.mikrotikapi] API query: /caps-man/registration-table
2024-10-18 02:02:33.922 ERROR (SyncWorker_2) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 10.10.12.34 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
2024-10-18 02:02:33.923 DEBUG (MainThread) [custom_components.mikrotik_router.coordinator] Finished fetching Mikrotik WiFi data in 1.164 seconds (success: False)`

**Comment by Extrapilot1** [comment]
Guys-
Not the same error, but for many, a problem. With the new MT software, they have removed from the CLI menu options that are empty. Example, AC2 seems to not have much in the way of system health in the sense some other hardware does- no fan, no power monitoring etc. So, you will not find a system/health option. A lot of the code in the Integration here assumes these paths must exist. But, it seems to function OK if you bypass the check(s) in question. Some have problems with CAPSMAN, but with the System/Health thing, which will catch a lot of people, its an edit to the file coordinator.py under the mikrotik_router custom component (depends on where that is installed on your setup. Its found starting at line 1347 for a get_system_health routine. In that, there is a check where if the firmware is <7 it does one thing, but for anything else, it does another thing. That secondary path is the problem. It is a check on line 1370, where there is an elif 0 < self.major_fw_version >=7: conditional. Copy that line and paste it just below, and comment it with a # sign, so you have the original to reference. And then just modify the check to something like elif 8< self.major_fw_version >=9:

That will bypass that second section of code which is looking as /system/health, and the system seems to be fine without it. Probably requires a HA restart to reload the config. 

[coordinator.zip](https://github.com/user-attachments/files/17483424/coordinator.zip)

**Comment by idhammulya** [comment]
Same problem with routerOS 7.15

**Comment by djrawe** [comment]
> three changes to the file: \config\custom_components\mikrotik_router\coordinator.py from "/caps-man/registration-table", to "/interface/wifi/registration-table" from "/interface/{wifimodule}", to "/interface/wifi" from "/interface/{wifimodule}/registration-table", to "/interface/wifi/registration-table"
> 
> I'm not sure if everything works, but the integration starts and shows the data I use.

It’s working for me. Thank you very much.

**Comment by ilgarmehmetali** [comment]
FYI. self.major_fw_version only gets populated if user group has all three of "write, policy, reboot"  policies.
If you dont give any of these policies integration works. Alas with limited functionality.

**Comment by lukyrys** [comment]
+1

**Comment by 7lano** [comment]
@tomaae wake up please

**Comment by h1ghrise** [comment]
not stale! Broken and not being maintained anymore..
