### ISSUE TITLE
[Bug]Can you get RouterOS update pls?

### ISSUE THREAD

**Issue by hooonza** [tomaae/homeassistant-mikrotik_router#380]
## Describe the issue
Since about July 2024, I can't install any update in Home Assistant whether I click install or skip.
Thank you

## How to reproduce the issue

1. Settings / Mikrotik hAP Lite RouterOS Update / 
2. click "Install"  
3. Error ... nothing happens here

## Expected behavior
Regular update

## Screenshots

<div style="text-align: center;"><a href="https://acosbot.com/pl/blog/amazon-brand-store-witryna-twojej-marki/" target="_blank"><img src="https://img.eselt.de/img/16489559_PAwhmoUTVomPz5OY/ad.jpg" alt="Eselt - amazon brand store" style="margin-bottom: 16px;"></a></div>

## Software versions

 - Home Assistant version: 
 Core 2024.10.4
Supervisor 2024.10.3
Operating System 13.2
Frontend 20241002.4

 - Mikrotik Router integration version: Mikrotik RouterBOARD v. 6.49.13
 - Mikrotik Hardware: hAP lite , Firmware: 6.49.13 (stable) 
 - RouterOS version: see the screenshot pls.

## Traceback/Error logs
No error messages

**Comment by tomaae** [comment]
that does not look like integration related problem, but check HA error log for any messages.

**Comment by hooonza** [comment]
It is possible but all other integrations can be updated only this one no. No error messages in the log or whatever else. Nothing just happens and there is no update. Thanks.
