### ISSUE TITLE
[Feature] Kid Control Device data with read only policies

### ISSUE THREAD

**Issue by ilgarmehmetali** [tomaae/homeassistant-mikrotik_router#381]
Currently in the integration Kid Control Device data is not available if the user don't have "write, policy, reboot" policies.

With my tests i can use "reboot, read, test, api" policies and can access device data.
I just removed version checks and everything seems to working fine.

Changed https://github.com/tomaae/homeassistant-mikrotik_router/blob/master/custom_components/mikrotik_router/coordinator.py#L668
from
```
        if self.api.connected() and self.option_sensor_client_traffic:
            if 0 < self.major_fw_version < 7:
                await self.hass.async_add_executor_job(self.process_accounting)
            elif 0 < self.major_fw_version >= 7:
                await self.hass.async_add_executor_job(self.process_kid_control_devices)
```
to
```
        if self.api.connected() and self.option_sensor_client_traffic:
            await self.hass.async_add_executor_job(self.process_kid_control_devices)
```

Can you look into this?

**Comment by tomaae** [comment]
removing write should break the switch itself

**Comment by ilgarmehmetali** [comment]
I havent tried the switches as I was mainly intrested in traffic data of devices and they get read fine with the permissions above. 

Maybe switch control and traffic data logic could be separated.
