### ISSUE TITLE
[Bug] Version showing as 0.0.0 on config/integrations

### ISSUE THREAD

**Issue by reedy** [tomaae/homeassistant-mikrotik_router#384]
## Describe the issue
Version on the HA integration page shows as 0.0.0

## How to reproduce the issue

Go to integration page

## Expected behavior
Version to show as 2.1.4, not 0.0.0

## Screenshots

![Screenshot 2024-11-27 at 21 06 11](https://github.com/user-attachments/assets/e921a651-4fb9-45c0-b20a-f6cd2952d7c4)
![Screenshot 2024-11-27 at 21 07 24](https://github.com/user-attachments/assets/3a4fd064-08a9-40d4-a352-dc2a1117c873)

## Software versions
 - Home Assistant version: 2024.11.3
 - Mikrotik Router integration version: 2.1.4
 - Mikrotik Hardware: SXT R (not specific)
 - RouterOS version: 7.16.1

**Comment by tomaae** [comment]
thats not a bug, that is intended.

**Comment by reedy** [comment]
Why?

It makes it harder for people to report bugs as they've got to go to the HACS page to dig up the info...
