### ISSUE TITLE
Cannot read the state of Queues

### ISSUE THREAD

**Issue by bruxy70** [tomaae/homeassistant-mikrotik_router#40]
## Describe the issue
The switch entities for the individual queues are not updated when the queue is disabled or enabled. It can write the state, but not read (the other switches e.g. on interfaces or NAT work fine). In the integration, the switch is on all the time, when I turn it off, it will disable the queue, but the switch state will shortly change back to on (but the queue will stay disabled).
Or, if I enable/disable the queue, the switch will stay on all the time.

## How to reproduce the issue
Configure a simple queue on the router, Enable/disable the queue and observe the related switch in HA.

## Expected behavior
The switch should reflect the state of the queue and can be used to enable/disable queue

## Screenshots
![image](https://user-images.githubusercontent.com/44951610/80697746-b5272800-8ad9-11ea-8366-a51de2198a62.png)

## Software versions
 - Home Assistant version: HA v. 0.109.0
 - Mikrotik Router integration version: v1.5.5
 - Mikrotik Hardware: RB4011iGS+
 - RouterOS version: v6.46.6

## Traceback/Error logs
mikrotik_router: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this (but this is not related I suppose - they made a change in 0.109.0 (should have created another bug for that)
And You are using a custom integration for mikrotik_router which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant, which is a default.
No other errors.

**Comment by tomaae** [comment]
Could you export your queue config for me so I can have a look on some real settings? I dont use queues at all.
Thanks for info about translations, I have not updated to 0.109 yet.

**Comment by bruxy70** [comment]
# apr/30/2020 12:45:49 by RouterOS 6.46.6
# software id = B4KA-NAM9
#
# model = RB4011iGS+
# serial number = AAB10A424B92
/queue simple
add max-limit=2M/2M name=YOUTUBE packet-marks=Youtube target=bridge-main
add max-limit=4M/4M name=NETFLIX packet-marks=Netflix target=bridge-main
add max-limit=512k/512k name=APPLE packet-marks=Apple target=bridge-main
add max-limit=128k/512k name=Minecraft packet-marks=Minecraft target=bridge-main

**Comment by bruxy70** [comment]
Whilst you are at it. How hard would it be to get the download/upload rate for the query to the attributes? :) So I could detect if there is that kind of traffic....

**Comment by tomaae** [comment]
Not sure, can you send me mangles for those as well? I will see what I can do about traffic.

**Comment by bruxy70** [comment]
```
/ip firewall mangle
add action=add-dst-to-address-list address-list=Youtube address-list-timeout=30m chain=prerouting comment=\
    "YOUTUBE add address list" content=youtube.com
add action=add-dst-to-address-list address-list=Youtube address-list-timeout=30m chain=prerouting comment=\
    "GOOGLE VIDEO add address list" content=googlevideo.com
add action=add-dst-to-address-list address-list=Netflix address-list-timeout=30m chain=prerouting comment=\
    "NETFLIX add address list" content=nflxvideo.net
add action=add-dst-to-address-list address-list=Netflix address-list-timeout=30m chain=prerouting comment=\
    "NETFLIX add address list" content=netflix.com
add action=mark-packet chain=forward comment="Mark YOUTUBE" new-packet-mark=Youtube passthrough=no \
    src-address-list=Youtube
add action=mark-packet chain=forward comment="Mark Apple" new-packet-mark=Apple passthrough=no \
    src-address-list=Apple
add action=mark-packet chain=forward comment="Mark NETFLIX" new-packet-mark=Netflix passthrough=no \
    src-address-list=Netflix
```

The rates are available in the queue columns.

**Comment by bruxy70** [comment]
Oh, and if you want to test it, disable fast path in IP settings. Otherwise the packets will go around mangle...

**Comment by tomaae** [comment]
Thanks, this will help a lot to setup test environment for queues

**Comment by tomaae** [comment]
Changes released in v1.5.6

**Comment by tomaae** [comment]
It would be possible to also add sensors for rates, it that would be helpful.

**Comment by bruxy70** [comment]
Works beautifully, thank you. I think the sensor is not necessary, I will dig it out from the attributes. Love it. Thanks for the quick response!

**Comment by bruxy70** [comment]
![image](https://user-images.githubusercontent.com/44951610/80920165-50383000-8d6e-11ea-8241-baa6b461b879.png)

```yaml
sensor:
  - platform: template
    sensors:
      youtube_download:
        friendly_name: "Youtube download"
        unit_of_measurement: 'Kbps'
        value_template: >
          {% if is_state("switch.mikrotik_queue_youtube","on") %}
            {{ state_attr('switch.mikrotik_queue_youtube', 'Download rate') | regex_replace(find='[a-z]', replace='', ignorecase=True) | int }}
          {% else %}
            0
          {% endif %}
```

**Comment by tomaae** [comment]
True, there are always template sensors.
