### ISSUE TITLE
Cannot connect to Mikrotik

### ISSUE THREAD

**Issue by henriquehsa** [tomaae/homeassistant-mikrotik_router#41]
## Software versions

The IP address is correct. Winbox works Fine in the same address.
API port and winbox ports are default mikrotik ports.

Homeassistant 
109.4
Plugin inteled (HACS)
1.5.5

 - Home Assistant version: HA v0.109.4
 - Mikrotik Router integration version: 
 - RouterOS version: 

## Additional context

Thanks in advanced.

**Comment by tomaae** [comment]
Check your firewall, api port have to be accessible from HA server.
You can test it with telnet.

```
add action=accept chain=input comment=API dst-port=8728 protocol=tcp
add action=accept chain=input comment="API SSL" dst-port=8729 protocol=tcp
```

**Comment by henriquehsa** [comment]
You are right!

Thank’s!!
