### ISSUE TITLE
SwitchEntity & BinarySensorEntity deprecated in 0.110.0

### ISSUE THREAD

**Issue by bruxy70** [tomaae/homeassistant-mikrotik_router#44]
After the update to HA 0.110.0, these are in the error log:

![image](https://user-images.githubusercontent.com/44951610/82451883-d9f63600-9aae-11ea-9eec-aeccb9c9c59a.png)

![image](https://user-images.githubusercontent.com/44951610/82452160-30637480-9aaf-11ea-9700-33201106b50c.png)

## How to reproduce the issue
Upgrade to HA 0.110.0

## Expected behavior
No errors

## Screenshots
See above

## Software versions
HA 0.110.0

## Traceback/Error logs
Screenshots above

**Comment by tomaae** [comment]
hmm, this was not in release notes. thanks for reporting.
Fix released as v1.5.7
