### ISSUE TITLE
[Question] Change One AP to another. Switch Away mode...

### ISSUE THREAD

**Issue by vampywiz17** [tomaae/homeassistant-mikrotik_router#45]
Hello there,

I use the device tracking funktion, but some reason, i not use CapsMAN. I monitor your integration two AP, but if one miss the connection and connect it to other one (move in the house) the person state went to "away" It is a big problem in my case, because i control it this the alarm system auto on/off. So it this case, the alarm system go to "away" mode and trigger the alarm.

I read that the timeout is not working on wireless mode, so i don't know how to solve it.

Any idea?

**Comment by tomaae** [comment]
I dont think there is an easy workaround for this if you dont want to use capsman. 
perhaps waiting for one cycle before triggering the alarm would work. you could use manual binary sensors to control that. its not easy, but should be doable.
