### ISSUE TITLE
[Question] Can we have pppoe interface RX/TX as sensor?

### ISSUE THREAD

**Issue by nutinshell** [tomaae/homeassistant-mikrotik_router#48]
Is this possible? Thanks :)

**Comment by tomaae** [comment]
I have to see how it looks like. can you export you pppoe configuration.

**Comment by nutinshell** [comment]
hi, PPPoE client's RX/TX I think it should be like other ether interfaces?

![image](https://user-images.githubusercontent.com/211299/83377334-d8f6ca00-a407-11ea-84f5-ea22c1b220d0.png)

**Comment by tomaae** [comment]
screenshot is not sufficient, I will need you pppoe config to replicate it in my development environment.

**Comment by nutinshell** [comment]
/interface pppoe-client export 
# jun/01/2020 14:20:40 by RouterOS 6.46.6
# software id = WNC0-YY7A
#
# model = RB450Gx4
# serial number = *
/interface pppoe-client
add disabled=no interface=eth1 name=pppoe-out1 password=xxx \
    user=xxx

Just a very normal PPPoE session on the router :)

**Comment by tomaae** [comment]
thanks, I will look into it

**Comment by tomaae** [comment]
released in v1.5.9
