### ISSUE TITLE
[Bug] Mikrotik xxx.xxx.xxx.xxx error while building list for path : unknown

### ISSUE THREAD

**Issue by icemanshutter** [tomaae/homeassistant-mikrotik_router#49]
## Describe the issue

Entity id's missing during take on of Mikrotik router

## How to reproduce the issue

This issue can be seen in the logs right after adding the device info to the configuration ie. IP, Username, Password etc

## Expected behavior

After adding the config, to scan the device (Mikrotik router) and add the entities to HA

## Software versions

 - Home Assistant version: **HA v0.110.3**
 - Mikrotik Router integration version: **v1.5.8**
 - Mikrotik Hardware: **2011UAS**
 - RouterOS version: **v6.42.12**

## Traceback/Error logs

Mikrotik xxx.xxx.xxx.xxx error while building list for path : unknown.

    Exception in update_controller when dispatching 'mikrotik_router-update-MyRouter ': () Traceback (most recent call last): File "/config/custom_components/mikrotik_router/sensor.py", line 149, in update_controller update_items(inst, mikrotik_controller, async_add_entities, sensors) File "/config/custom_components/mikrotik_router/sensor.py", line 174, in update_items sensors[item_id].async_schedule_update_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 443, in async_schedule_update_ha_state self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 294, in async_write_ha_state f"No entity id specified for entity {self.name}" homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity MyRouter Temperature
    Exception in update_controller when dispatching 'mikrotik_router-update-MyRouter ': () Traceback (most recent call last): File "/config/custom_components/mikrotik_router/binary_sensor.py", line 48, in update_controller update_items(inst, mikrotik_controller, async_add_entities, sensors) File "/config/custom_components/mikrotik_router/binary_sensor.py", line 71, in update_items sensors[item_id].async_schedule_update_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 443, in async_schedule_update_ha_state self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 294, in async_write_ha_state f"No entity id specified for entity {self.name}" homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity MyRouter Firmware update

## Additional context

Connecting to the router via API on port 8728 not using SSL and with a Admin account that has full and all rights. Also tried with a restricted account that was created as per die setup / config page of the homeassist-mikrotik-router page.

**Comment by tomaae** [comment]
your firmware may be a problem. they changed how api logins are handled back in 6.43 and librouteros does not seem to handle old system well.
This old version are no longer supported by mikrotik, try upgrading to current or long-term channel version.

**Comment by icemanshutter** [comment]
Thank you very much for the quick response.

Will update the router and test.

**Comment by icemanshutter** [comment]
Updating the firmware fixed the issue. Maybe just add a note on the config page (not sure if i maybe missed it) of the minimum Mikrotik version required.

Thank you for the help and building this.
