### ISSUE TITLE
[Lokalise] Add new translations language

### ISSUE THREAD

**Issue by samueljon** [tomaae/homeassistant-mikrotik_router#54]
Please add support for Icelandic language is_IS. Native name Íslenska ( which means Icelandic)

Thanks 
Samúel Jón Gunnarsson

**Comment by tomaae** [comment]
[is_IS](https://app.lokalise.com/project/581188395e9778a6060128.17699416/?view=single&reference_lang_id=640&single_lang_id=806) added on lokalise
