### ISSUE TITLE
[Bug] Device tracking stops working suddenly

### ISSUE THREAD

**Issue by tekand** [tomaae/homeassistant-mikrotik_router#56]
## Describe the issue
Device tracking stops working after a few hours/days after all tracked devices go offline and stay offline.
The tracked devices would remain in Away state even after they are visible in the DHCP leases on Mikrotik side. After a HA restart it suddenly starts working again. Happens with wired and wireless devices as well.
Similar to problems described in #24.

## How to reproduce the issue
Not clear. Maybe the following:
1. Enable device tracking.
2. Disable all device trackers except one.
3. Wait (hours, days)
4. Reconnect to the network with that device and observe that it stays in Away state.

## Expected behavior
The device would move to Home state.

## Software versions
 - Home Assistant version: HA 0.112.4
 - Mikrotik Router integration version: 1.5.10
 - Mikrotik Hardware: hAP ac
 - RouterOS version: 6.47.1

## Traceback/Error logs
Did not see any errors or warnings in the HA log. Changed log level to debug, but so far the issue has not appeared. Once the issue comes again, I'll recheck the logs.

Do you have any idea how could I debug this issue?

**Comment by tomaae** [comment]
try this:
connect a device which is using DHCP. disconnect it and delete its DHCP lease manually in mikrotik. afterwards connect it and make sure its IP is different.
will this reproduce the issue?

does it also affect other tracking methods, or just DHCP?

**Comment by tekand** [comment]
Thank you @tomaae for your suggestion.
All of my DHCP leases are static, this way they always get the same IP.
Other tracking methods? Only other I know is CAP, which I don't use. :(

**Comment by tekand** [comment]
Sure. Which part of the log do you need?

**Comment by tekand** [comment]
I've made my e-mail public, can you please shoot me a mail so I can send the logs in e-mail. Don't really feel comfortable posting it here.

**Comment by tomaae** [comment]
Logs look good, but I was not able to reproduce it with same setup.
For now, I will keep trying. If you have any more details, just let me know.

**Comment by tomaae** [comment]
I dont get this issue at all, no matter what I do, I'm not able to reproduce it.
Of course I tried your step by step several times, but it always worked fine.

**Comment by ultratoto14** [comment]
I have the same kind of problem as @tekand, will try to find a reproducible way to prove it.
