### ISSUE TITLE
[Feature] Present environment variables to HA

### ISSUE THREAD

**Issue by glmnet** [tomaae/homeassistant-mikrotik_router#58]
I have a static route I sometimes turn on when my main ISP fails (quite often actually) I have a script to enable the route and another script to disable it when connection works again.

How can I tell from HA if this route is enabled?

While I'm writing this I am thinking... there is also a NAT rule which I could deactivate (not necessary) when I activate the route rule so I could use this as workaround, but not ideal. In any case if this is a FR could instead there be access to read variables in mikrotik from HA? Or in any case do scripts support returning a value?

**Comment by tomaae** [comment]
HA integration does not show route status. With proper setup, there should not be any need to change routes on the fly.
You should not have to do any manual action for failover connection. Just setting your 2nd connection with higher distance should activate it when primary route is not available.

Scripts on mikrotik does not have return values, you can only trigger them as async.

**Comment by glmnet** [comment]
> You should not have to do any manual action for failover connection. Just setting your 2nd connection with higher distance should activate it when primary route is not available.

Thanks for pointing out this 

Is this automatically done based on reachability of the route? My issues generally are beyond that, so I can see, ping and communicate with upstream router but that does not mean the connection is useful. 
So I ended up doing is: my main internet connection has a distance 2 and the (usually disabled) alternate route has distance 1. And I manually enable the alternate route when “the connection gets very slow and loses many packets”. 

What do you think about variables?  Is that possible? That would allow end users doing more interesting stuff.

**Comment by glmnet** [comment]
````
[glm@MikroTik] > :global selectedIsp;
[glm@MikroTik] > :set selectedIsp "Skynet";
[glm@MikroTik] > :environment print
defconfMode=[:nothing]
lastChange="OK"
selectedIsp="Skynet"

[glm@MikroTik] > /environment
[glm@MikroTik] /environment> export
bad command name export (line 1 column 1)
[glm@MikroTik] /environment> print
defconfMode=[:nothing]
lastChange="OK"
selectedIsp="Skynet"
````

I've just play a bit with librouteros and could not get it to work,

The following works

````python
>>> tuple(api.path('/interface'))
[....]
```` 

but this give nothing:

````python
>>> tuple(api.path('/environment'))
()
````

**Comment by tomaae** [comment]
Ah, you mean env. I will take a look.

**Comment by glmnet** [comment]
In case anyone needs something like this I ended up using an ssh command to the router with hass command line sensor.

**Comment by tomaae** [comment]
True, you can do that. I still plan to look into integrating it when I find some free time.

**Comment by glmnet** [comment]
Thank you!!! Will check it when released as I use this via HACS
