### ISSUE TITLE
[Bug]  KeyError: 'dst-port'

### ISSUE THREAD

**Issue by volshebniks** [tomaae/homeassistant-mikrotik_router#6]
I got the following error:
Fri Dec 20 2019 13:23:45 GMT+0300 (Москва, стандартное время)
Error setting up entry Mikrotik_R for mikrotik_router
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 192, in async_setup
hass, self
File "/config/custom_components/mikrotik_router/init.py", line 48, in async_setup_entry
await mikrotik_controller.async_update()
File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 160, in async_update
self.get_nat()
File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 391, in get_nat
self.data['nat'][uid]['name'] = "{}:{}".format(entry['protocol'], entry['dst-port'])
KeyError: 'dst-port'

To Reproduce

1. Set up the integration.
2. Happens after that and on each reboot.

Software (please complete the following information):

Hass.io / Home Assistant version: Hassio v193 / HA v 0.103.2
Mikrotik Hardware: hAP ac²
Mikrotik Software version: v6.46.1

**Comment by tomaae** [comment]
Can you provide output for:
`/ip firewall nat print terse without-paging where chain=dstnat and !dst-port`
You can censor any values you want, just keep the syntax in tact.

**Comment by volshebniks** [comment]
the result:
 0 X  comment=aaa.bbb.me chain=dstnat action=dst-nat to-addresses=192.168.100.
14 to-ports=8123 protocol=tcp dst-address=192.168.100.14 in-interface=eth1.wan log
=no log-prefix=smart

**Comment by tomaae** [comment]
I see what was the problem, but I cannot reproduce it in dev version. During refactoring I did many checks and default values for everything when values are not present, so that most likely fixed it.
I have released it under v1.2, can you give it a try?
