### ISSUE TITLE
[Bug] Interface aggregation creates MAC conflict in HA 

### ISSUE THREAD

**Issue by golddragon007** [tomaae/homeassistant-mikrotik_router#60]
## Describe the issue
2020-08-22 15:22:02 ERROR (MainThread) [homeassistant.util.logging] Exception in update_controller when dispatching 'mikrotik_router-update-Mikrotik': ()
Traceback (most recent call last):
  File "/config/custom_components/mikrotik_router/device_tracker.py", line 91, in update_controller
    update_items(
  File "/config/custom_components/mikrotik_router/device_tracker.py", line 142, in update_items
    tracked[item_id].async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 426, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 274, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity Mikrotik combo4: home>

2020-08-22 15:22:02 ERROR (MainThread) [homeassistant.util.logging] Exception in update_controller when dispatching 'mikrotik_router-update-Mikrotik': ()
Traceback (most recent call last):
  File "/config/custom_components/mikrotik_router/switch.py", line 89, in update_controller
    update_items(inst, mikrotik_controller, async_add_entities, switches)
  File "/config/custom_components/mikrotik_router/switch.py", line 138, in update_items
    switches[item_id].async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 426, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 274, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity Mikrotik port combo4: on>

## How to reproduce the issue
It's just simple appears in the HA log periodically.

## Expected behavior
No exceptions.

## Software versions

 - Home Assistant version: 0.114.1
 - Mikrotik Router integration version: latest
 - Mikrotik Hardware: CRS312-4C+8XG
 - RouterOS version: v6.46.6

**Comment by golddragon007** [comment]
Ehh for a proper aggregation you need two devices that support, On the interfaces panel you need to add a new bond. Then you need to select the slaves, that will be the aggregated ports. But also you need to add this new aggregation on the Bridge bonds page. and I guess also to your bridge.

**Comment by golddragon007** [comment]
I've found also this now when I started HA:

2020-08-28 00:40:21 ERROR (MainThread) [homeassistant.components.device_tracker] Platform mikrotik_router does not generate unique IDs. ID mikrotik-interface-74:4D:28:C8:01:58 already exists - ignoring device_tracker.mikrotik_combo3
2020-08-28 00:40:21 ERROR (MainThread) [homeassistant.components.switch] Platform mikrotik_router does not generate unique IDs. ID mikrotik-enable_switch-74:4D:28:C8:01:58 already exists - ignoring switch.mikrotik_port_combo3

**Comment by golddragon007** [comment]
mikrotik_port_combo3 and mikrotik_port_combo4 are aggregated, therefore anything that 3 sees also 4 sees.

**Comment by tomaae** [comment]
ah, you hidden mac address, thats why I didnt notice.
Yeah, I remember there is something like that with aggregation, I need exact info to workaround the issue.
Check using "interface print" command on mikrotik for mac addresses for these 3 interfaces:
combo3, combo4, 20G
I just need to know which if those have duplicate mac and which are unique.

**Comment by golddragon007** [comment]
all 3 has the same MAC address, while the others have all unique.
I think you need to check in your code if the interface has the same MAC, if it has, you treat it like an aggregated port, therefore if a device shows up on any of those, it's totally fine, nothing 'changed'.

```
> interface print     
Flags: D - dynamic, X - disabled, R - running, S - slave 
 #     NAME                                TYPE       ACTUAL-MTU L2MTU  MAX-L2MTU MAC-ADDRESS      
 0   S combo1                              ether            1500  1592      10218 MAC1
 1   S combo2                              ether            1500  1592      10218 MAC2
 2  RS combo3                              ether            1500  1592      10218 MAC
 3  RS combo4                              ether            1500  1592      10218 MAC
 4   S ether1                              ether            1500  1592      10218 MAC3
 5   S ether2                              ether            1500  1592      10218 MAC4
 6   S ether3                              ether            1500  1592      10218 MAC5
 7   S ether4                              ether            1500  1592      10218 MAC6
 8   S ether5                              ether            1500  1592      10218 MAC7
 9   S ether6                              ether            1500  1592      10218 MAC8
10   S ether7                              ether            1500  1592      10218 MAC9
11  RS ether8                              ether            1500  1592      10218 MAC10
12   S ether9                              ether            1500  1598       2028 MAC11
13  RS 20G                                 bond             1500  1592            MAC
14  R  ;;; defconf
       bridge                              bridge           1500  1592            MAC12
```

Also alternatively you can ask if there is bonds/aggregation:

```
> interface bonding print
Flags: X - disabled, R - running 
 0  R name="20G" mtu=1500 mac-address=MAC arp=enabled arp-timeout=auto slaves=combo3,combo4 mode=802.3ad primary=none link-monitoring=mii arp-interval=100ms arp-ip-targets="" mii-interval=100ms down-delay=0ms up-delay=0ms lacp-rate=30secs transmit-hash-policy=layer-2-and-3 min-links=1
```

**Comment by golddragon007** [comment]
"I assume all interfaces show same traffic values as well?"
No, those are not the same. It shows actually where the traffic goes. So all the 3 has different traffic values, depending on the link's usage and the 20G is a sum of the links.
"obvious solution is to query bonding list and exclude slaves from interface list. but if I did that, it would not be possible to monitor them via HA."
Yes, it would be bad... For me at least.
"another option would be to handle slaves in different ways, like appending default interface name and slave keyword."
The interface names are not unique as far as I know, I can name it exactly to the same (needs a check), so there's no reason to include it. I thinking on the interface number '#' that can be interesting to concatenate with that one. In this case maybe just the list reorder can make some problem.

**Comment by tomaae** [comment]
oh, interface default-name is unique. you can name them, but their default-name is still available to api. I use that elsewhere.
I think interface number can change on reboot.

I will look into it soon, I just have too much work right now. I pretty much know how to solve it without loosing any functionality.

**Comment by marine1988** [comment]
This plugin is still working?

**Comment by tomaae** [comment]
Yes it is. This is specific issues with aggregated links.

**Comment by tomaae** [comment]
Can you test master on your system?
