### ISSUE TITLE
[Feature] Kid Control support

### ISSUE THREAD

**Issue by ville82** [tomaae/homeassistant-mikrotik_router#62]
## Is your feature request related to a problem? Please describe.

No

## Describe the solution you'd like

Adding support for Kid Control, with possibility to pause/resume/enable/disable and view current status. 
/ip kid-control

## Describe alternatives you've considered

For now I create a mikrotik scipt for each kid and use the current script execution support. But I have no sollution to retrieve current status.

**Comment by tomaae** [comment]
Hmm, sure, why not. I will have to research how it works first tho.

**Comment by tomaae** [comment]
Working on this in #70. I will close this one as we already started discussing there
