### ISSUE TITLE
[Feature] Hotspot validation feature request

### ISSUE THREAD

**Issue by dborsnich** [tomaae/homeassistant-mikrotik_router#63]
Hi, I think that will be very useful, to use hotspot to validate into the Hassio
The idea is to login in hotspot and redirect and validate directly to HA
This solution will solve the user unfriendly of HA and permit all functionalities of hotspot
Thanks for your works!

**Comment by tomaae** [comment]
Hi,
Not sure what you mean. I'm not familiar with mikrotik hotspot, so you will need to go more into detail.

**Comment by dborsnich** [comment]
ok, for example. The idea is validate only once. When you connect to your wifi network, use an user and password (could be inclusive radius validation without hotspot). Then the mikrotik use a token to validate with hassio or use login credentials, and goes directly without validate again in Hassio
The idea is, you validate into the mikrotik user radius structure, and this, validate into Hassio
With hotspot you a have a lot of programs that manage the user more friendly and, depending of it user, you can redirect to hassio web that you prefer

Other way could be, that hassio logins, goes to command line authetication and validate into radius mikrotik database
I dont know if I complicate more my explanation, jaja
Thanks

**Comment by dborsnich** [comment]
Here I tested this solution and works well
I use Hassio command line authentication with miktorik radius. Then with userman of mikrotik, manage all users. I follow testing, thanks!
https://gist.github.com/doino-gretchenliev/d9faf0bf1bbad8919764cd1fbf8d2c64#gistcomment-3498407

**Comment by tomaae** [comment]
Ok, I will have a look at that code when I will be working on next release.
