### ISSUE TITLE
[Bug] Disabled DHCP leases are added to devices

### ISSUE THREAD

**Issue by clau-bucur** [tomaae/homeassistant-mikrotik_router#66]
## Describe the issue
Disabled DHCP leases are added to the list of availailable HA devices for the integration.

## How to reproduce the issue
1. Go to IP / DHCP Server / Leases
2. Disable a static lease
3. The device should not be exposed in HA integration.

## Expected behavior
Disabled Mikrotik objects (DHCP leases, etc) should not be exposed by the integration.

## Screenshots
![image](https://user-images.githubusercontent.com/47672949/97295334-d03fde00-1857-11eb-88ed-5bc86a44cff3.png)

## Software versions
 - Home Assistant version: HA v0.117.0b5
 - Mikrotik Router integration version: v1.5.10
 - Mikrotik Hardware: RB2011UiAS-2HnD
 - RouterOS version: v6.47.6

**Comment by tomaae** [comment]
This is expected behavior, integration should show all known entities. Integration controls enable/disable status of most entities, so it would not really work if they were hidden.

**Comment by clau-bucur** [comment]
Thank you. I understand.
In this case (for the DHCP leases) I don't see a switch to enable or disable them.
