### ISSUE TITLE
[Feature] Show manufacturername based on mac address instead of fixed Mikrotik

### ISSUE THREAD

**Issue by mvdwetering** [tomaae/homeassistant-mikrotik_router#67]
## Is your feature request related to a problem? Please describe.

Some of the devices exposed by the integration are just mac addresses. E.g. 84:25:DB:E4:8F:0E and it is unclear what the device is as there is no other information. Manufacturer and model just show Mikrotik and my router model.

I wish the information exposed by the integration is closer to what it actually is.

Now I look up the mac address (for example with https://macvendors.com/) and it shows "Samsung Electronics Co.,Ltd" so I at least know it is a Samsung device and I guess it is my old phone that I turned on recently again.

## Describe the solution you'd like

Instead of showing Mikrotik as manufacturer for all devices in HA show a manufacturer based on mac address lookup (or something else, but I guess mac is all there is to work with). Only for "external" devices, the router ports etc... of course stay Mikrotik manufacturer.

Maybe something similar for model. It shows the Mikrotik router model for all devices while actually the integration does not know the model. It might be clearer to leave it out when not known.

## Describe alternatives you've considered

Could not think of anything else.

## Additional context

Can't think of anything

**Comment by tomaae** [comment]
Agreed, that would be nice. Not sure if its doable tho, I have to research this.

**Comment by tomaae** [comment]
![image](https://user-images.githubusercontent.com/23486452/101052206-a5e3ed80-3586-11eb-868a-611d347e5b41.png)
