### ISSUE TITLE
[Feature] Allow to select entities presented to HA in settings

### ISSUE THREAD

**Issue by nocturneop15** [tomaae/homeassistant-mikrotik_router#68]
After enablig this integration, my Homeassistant becomes flooded with devices imported from Mikrotik - but I only need to monitor status of some ports and VPN tunnels, not more. 

I would appreciate, if we have option to selectivly enable/disable publishing groups of entities from Mikrotik. 

Especially disable publishing client devices would be extremely useful.

From my point of view,  all exports should be disabled by default.

**Comment by nocturneop15** [comment]
ok, but you can only enable or disable this. Not filter out what to enable (and all is enabled by default) - as result, I have 59 devices and 230 entities just after enabling integration. 

Having options what to publish would be great for keeping HA as clean as possible.

**Comment by nocturneop15** [comment]
Separate switches for exporting entities: 

- physical interfaces including wifi and cellular (switch, rx, tx)
- PPP interfaces (rx, tx, switch)
- queues (switch)
- ip/routes (switch)
- mangle objects (switch)
- filter rules (switch)
- client devices (rx, tx)

also, I should leave general system values (cpu, ram etc.) enabled by default, 

That would give us great granular control what to include in HA - this might be useful for larger networks (my home network contains 9 mikrotik routers at all, that's why I was scared by exporting 230 entities from just one, first connected mkt)

**Comment by tomaae** [comment]
hmm, I will need to have a look if it is even possible, since many objects are interconnected. most should be tho, but such change wont be fast since that would involve translation files.
I will have a look on what can be done here.

**Comment by nocturneop15** [comment]
Cool, hope this will be doable! 

If possible, could also scripts be presented with toggle button? That would allow very simple, but absolutely full controll over mkt in HA...(and allows automations that are otherwise impossible, e.g. switching routing chain across multiple devices. In my case - I have more WANs available ,but some of them are behind another subnets and devices)

**Comment by nocturneop15** [comment]
oups, sorry - i did not nottice, that is great! I must check this further. Thanks for your work!

**Comment by adventurous-geek** [comment]
This feature is important. I took was surprised that after adding just one of 5 mikrotik routers, I had 300+ entities. I would very much like to limit this to specific interfaces/devices only. Sure, I can disable the unwanted ones, but with a list that long, that is not a nice job.

**Comment by tomaae** [comment]
it wont be possible to limit to specific interfaces/devices, you have to do that in HA like with any other integration.
I can only filter by functionality groups.

**Comment by tomaae** [comment]
![Screenshot 2020-12-10 063143](https://user-images.githubusercontent.com/23486452/101725778-87638200-3ab1-11eb-8aa5-d9e34fbeef3e.png)
This is my general idea at the moment. I have implemented multi page configuration, this will be its 2nd page.
For now, I'm leaving only port switch and system sensors on by default, rest will have to be turned on in options.

I think this is what you had in mind.

**Comment by nocturneop15** [comment]
Exactly! This is awesome option, thumbs up!

**Comment by tomaae** [comment]
All done, it will be available in next release.

**Comment by adventurous-geek** [comment]
This is a great way of reducing the number of entities listed. Additionally, you might consider including a REGEX filter on the entity names, so that only those meeting the filter will be included.
