### ISSUE TITLE
[Feature] Would it be possible to add count of devices/interfaces?

### ISSUE THREAD

**Issue by kbalint** [tomaae/homeassistant-mikrotik_router#69]
I saw the following card on one HA setup:
![image](https://user-images.githubusercontent.com/4146263/98108156-d52a1080-1e9b-11eb-815c-7a7ab1e18144.png)

and would like to implement something similar on my Mikrotik setup, for example how many devices connected via cable or wifi, to which subnet etc.

Is there any possibility to build with the current code with templates for example, or requires some development?

Thanks!

**Comment by tomaae** [comment]
Not sure, I will add it to my to-do list. It will require development for sure, but thats not a problem.
