### ISSUE TITLE
[Feature] PPP user tracker and switches

### ISSUE THREAD

**Issue by i-o-m-a** [tomaae/homeassistant-mikrotik_router#76]
Active VPN user monitoring, maybe something like /ppp active print output

**Comment by tomaae** [comment]
I need more information here, please elaborate

**Comment by i-o-m-a** [comment]
Hello,

One of the possible Home Assistant remote access option is to setup VPN server on home network.
Mikrotik routers can act as VPN server (site-to-site or client vpn), PPTP, SSTP, L2TP, OpenVPN. Here wiki  of L2TP VPN server configuration https://wiki.mikrotik.com/wiki/Manual:Interface/L2TP.
Will be nice to have:
- monitor active\connected to Mikrotik VPN users in HA
- enable\disable Mikrotik VPN users (secrets) from HA

Some screenshots of active VPN users from
Winbox:
![image](https://user-images.githubusercontent.com/76471219/102980382-2bb4e200-4510-11eb-8e09-8ac46cfa362b.png)
![image](https://user-images.githubusercontent.com/76471219/102980399-2f486900-4510-11eb-93be-1d3b55bebde0.png)

Command line:
![image](https://user-images.githubusercontent.com/76471219/102980411-340d1d00-4510-11eb-8395-cc12fb0fb468.png)
![image](https://user-images.githubusercontent.com/76471219/102980428-38393a80-4510-11eb-8930-57b541db73db.png)

**Comment by tomaae** [comment]
So user switches and user trackers for ppp. Sounds good to me.
can you give me output of `/ppp active print terse`?
also print terse for ppp user list, not sure how that is defined.

**Comment by i-o-m-a** [comment]
/ppp active print - command will show all currently connected users.
PPP active connection (brief):
# - serial number
R - radius 
NAME - User name supplied at authentication stage
SERVICE - Type of service the user is using (PPTP, L2TP, SSTP or OpenVPN)
CALLER-ID - For PPTP and L2TP it is the IP address the client connected from. For PPPoE it is the MAC address the client connected from.
ADDRESS - IP address the client got from the server
UPTIME - User's uptime
ENCODING - Shows encryption and encoding (separated with '/' if asymmetric) being used in this connection

[admin@MikroTik] > /ppp active print 
Flags: R - radius 
 #   NAME         SERVICE CALLER-ID         ADDRESS         UPTIME   ENCODING                                                                                                                    
 0   igors        l2tp    123.1.123.12      192.168.0.208   1s       cbc(aes) + hmac(sha1)   
 1R igors        l2tp    123.1.123.12      192.168.0.208   1s       cbc(aes) + hmac(sha1)   

################################################################################################
PPP User list (brief):
# - serial number
X - disabled
NAME - Name used for authentication
SERVICE - Specifies the services that particular user will be able to use (PPTP, L2TP, SSTP or OpenVPN, any)
CALLER-ID - For PPTP and L2TP it is the IP address a client must connect from. For PPPoE it is the MAC address (written in CAPITAL letters) a client must connect from. For ISDN it is the caller's number (that may or may not be provided by the operator) the client may dial-in from
PASSWORD - Password used for authentication
PROFILE - vpn profile assigned to user
REMOTE-ADDRESS - IP address that will be assigned to remote ppp interface.

[admin@MikroTik] > /ppp secret print 
Flags: X - disabled 
 #   NAME   SERVICE CALLER-ID       PASSWORD                     PROFILE              REMOTE-ADDRESS 
 0   igors      l2tp                                MyCoolPassword12         vpn                                     
 1 X olga      any                                MyCoolPassword12         vpn                                     

################################################################################################
/ppp secret disable igors - disable user "igors"
/ppp secret enable igors - enable user "igors"

**Comment by tomaae** [comment]
thanks, looks good.
print terse does not exist for ppp?

**Comment by i-o-m-a** [comment]
"/ppp secret print" by default is the same as "/ppp secret print brief"

**Comment by i-o-m-a** [comment]
[admin@MikroTik] > /ppp active print terse 
 0   name=igors service=l2tp caller-id=11.11.11.11 address=192.168.0.207 uptime=14s encoding=cbc(aes) + hmac(sha1) session-id=0x8120001F limit-bytes-in=0 limit-bytes-out=0

**Comment by tomaae** [comment]
Can you give it a try? I was only able to test it with my phone.

**Comment by i-o-m-a** [comment]
Sure. How?

**Comment by tomaae** [comment]
in hacs select reinstall, and chose "master"

**Comment by i-o-m-a** [comment]
Aha, got it!

Can You please also add translation? 1) i can test translations 2) i can understand what i do :)))

![image](https://user-images.githubusercontent.com/76471219/103137397-4a160b80-46d1-11eb-8986-c613e1a99d9e.png)

**Comment by i-o-m-a** [comment]
![image](https://user-images.githubusercontent.com/76471219/103137575-bc3b2000-46d2-11eb-87f4-25f5fa579867.png)

**Comment by tomaae** [comment]
Cant do that, sorry. Translations are pulled from lokalize when release is build. Master is always without translation.
Here is the list:
![image](https://user-images.githubusercontent.com/23486452/103137634-cc4f0180-46ca-11eb-8e71-f5ac44c99240.png)

**Comment by i-o-m-a** [comment]
OK, clear thank You for legend! it looks that something not working\not available, but let me re-test it, disabling unneeded features

**Comment by tomaae** [comment]
sure, take your time :)

**Comment by i-o-m-a** [comment]
So, it looks like it is not what i expected, but if we take in to account the whole tracking idea, i think its ok!

![image](https://user-images.githubusercontent.com/76471219/103137927-17224680-46d6-11eb-8768-fa20a9f03378.png)

![image](https://user-images.githubusercontent.com/76471219/103137932-1c7f9100-46d6-11eb-8309-33788d4bc9d4.png)

enable and disable PPP users (secrets) also working.

Cool!

**Comment by tomaae** [comment]
what did you had in mind? I'm open to ideas ;)

**Comment by i-o-m-a** [comment]
Its showing "Home"\"Away". i wanted to see "Connected"\"Not connected" status
But need to think about project in general, if its tracking, maybe its okay to have such status in HA....

**Comment by tomaae** [comment]
hmm, I will look into how this can be done

**Comment by tomaae** [comment]
Done. I used connected/disconnected as thats how HA handles connectivity device class.

**Comment by i-o-m-a** [comment]
Cool!

![image](https://user-images.githubusercontent.com/76471219/103139233-dd0b7180-46e2-11eb-875c-949bcdc860da.png)

**Comment by i-o-m-a** [comment]
Hello,

There is small issue with the addon (i think with addon in general), if mikrotik user that configured with home assistant integration does not have enough permissions and any of integration switches triggered, HA becomes unusable until restart (for example: "ha core restart")...

**Comment by tomaae** [comment]
hmm, that could happen I guess. I have to test what exactly happens and which permissions cause that.
Opened new issue for this #80
