### ISSUE TITLE
[Lokalise] Add new translations language - Latvian?

### ISSUE THREAD

**Issue by i-o-m-a** [tomaae/homeassistant-mikrotik_router#77]
If You need, i can help You with translation to Latvian language.

P.S. Already checked Your Russian translation and made correction, You can review.

**Comment by tomaae** [comment]
Thanks, added

**Comment by i-o-m-a** [comment]
Sorry, not sure that i understand correctly, if You need Latvian translation, then please give me access to Latvian translations

**Comment by i-o-m-a** [comment]
Thank You! But You added Lithuanian language :) Please add Latvian 
![image](https://user-images.githubusercontent.com/76471219/103029371-56c82180-4562-11eb-9a40-9f5588b32666.png)

**Comment by i-o-m-a** [comment]
Thank You!
I have some questions\comments about translations, can You take a look on comments in lokalise.com?

**Comment by tomaae** [comment]
> You take a look on comments in lokalise.com?

Dont worry, I get a notification for every comment there :)
