### ISSUE TITLE
[Feature] CPU & Board temperature sensors

### ISSUE THREAD

**Issue by ckiliboz** [tomaae/homeassistant-mikrotik_router#79]
## Is your feature request related to a problem? Please describe.

Temperature sensor works well for RB450Gx4 but for CRS328, it has 2 temperature sensors (board-temperature1 and cpu-temperature) and temperature value shows Unknown

## Describe the solution you'd like

Addition of new sensors, can be called the same way it's shown under System > Health

## Additional context

Just found this integration and it's really amazing! Thanks a lot!

**Comment by tomaae** [comment]
Yeah, these sensors can be different on different boards. I'm not familiar with CRS series myself.
Can you give me output of `/system health print`?

**Comment by ckiliboz** [comment]
This one is for CRS328-24P-4S+, not sure if others are similar or not though
```
     cpu-temperature: 58C
   power-consumption: 34.7W
  board-temperature1: 34C
        psu1-voltage: 26.5V
        psu2-voltage: 52.7V
        psu1-current: 0A
        psu2-current: 0.6A
          fan1-speed: 2685RPM
          fan2-speed: 2970RPM
```

**Comment by tomaae** [comment]
thanks

**Comment by tomaae** [comment]
Added in master. I cannot make this dynamic since it is not presented as a table. But this will work fine too.

**Comment by ckiliboz** [comment]
Thanks a lot, works great for CRS328! 

My only concern is the same sensors are also available for other devices and value is "unknown" since they don't exists (like cap ac). It will get more cluttered in time and for some people it might even be confusing to see them. It will be great if the sensors can be based on the device connected but that will probably take a lot more effort.

**Comment by tomaae** [comment]
do they show up as unknown on some of your devices?

I have tested it on my dev lab device and my main router:

cAP Lite:
![image](https://user-images.githubusercontent.com/23486452/103139193-1095ce00-46da-11eb-972f-071f3c8fc213.png)
cAP AC:
![image](https://user-images.githubusercontent.com/23486452/103139213-34f1aa80-46da-11eb-8bc6-a6f684d9f0ab.png)
RB450G:
![image](https://user-images.githubusercontent.com/23486452/103139229-708c7480-46da-11eb-80e6-a4f0d15933f8.png)
RB4011:
![image](https://user-images.githubusercontent.com/23486452/103139248-91ed6080-46da-11eb-954c-941b9eab8ab6.png)

**Comment by ckiliboz** [comment]
That's interesting, I see them as unknown - that's how I realized the cpu/board temperature difference in CRS also just "temperature" value was unknown. 

<img width="279" alt="Screen Shot 2020-12-25 at 21 32 39" src="https://user-images.githubusercontent.com/3728003/103139762-033c0c00-46f9-11eb-8419-aaac0cd14ca6.png">
<img width="285" alt="Screen Shot 2020-12-25 at 21 32 56" src="https://user-images.githubusercontent.com/3728003/103139764-06cf9300-46f9-11eb-9a75-63cd18fb9e1a.png">
<img width="282" alt="Screen Shot 2020-12-25 at 21 33 18" src="https://user-images.githubusercontent.com/3728003/103139765-07682980-46f9-11eb-9270-774f4e291df5.png">

**Comment by ckiliboz** [comment]
I was using v1.5.10, sensors are shown as unknown. Master branch behaves like you mentioned, sensors are not showing up if they are unknown. 
I can still get the logs if needed, but I don't see any errors or anything out of place. I need to clean them a bit to remove any sensitive information.

**Comment by tomaae** [comment]
No need, its only important that it works in master.
