### ISSUE TITLE
[Bug] System health not updating regularly

### ISSUE THREAD

**Issue by ckiliboz** [tomaae/homeassistant-mikrotik_router#81]
## Describe the issue

System health is not updated along with other sensors.

## How to reproduce the issue

Check last updated time for any health sensor & compare it with others (resources in my case)

## Expected behavior

Health sensor values to be updated along with other sensors.

## Screenshots

<img width="398" alt="Screen Shot 2020-12-28 at 15 25 37" src="https://user-images.githubusercontent.com/3728003/103211311-4678c380-4921-11eb-9cb3-6d400b2a0f47.png">
<img width="400" alt="Screen Shot 2020-12-28 at 15 25 46" src="https://user-images.githubusercontent.com/3728003/103211322-4c6ea480-4921-11eb-916b-fc13b5cc0ae1.png">

## Software versions

 - Home Assistant version:  2020.12.1
 - Mikrotik Router integration version:  master branch
 - Mikrotik Hardware:  RB450Gx4, CRS328-24P
 - RouterOS version:  6.48

## Traceback/Error logs

No errors.. `[custom_components.mikrotik_router.mikrotikapi] API query: /system/health` is missing after first query

**Comment by ckiliboz** [comment]
mikrotik_controller.async_update function is missing below lines
```
if self.api.connected():
            await self.hass.async_add_executor_job(self.get_system_health)
```

**Comment by tomaae** [comment]
> mikrotik_controller.async_update function is missing below lines
> 
> ```
> if self.api.connected():
>             await self.hass.async_add_executor_job(self.get_system_health)
> ```

No, thats not the issue. It should not be in hwinfo.
Should be fixed now.

**Comment by ckiliboz** [comment]
Makes sense. All good now - thanks!
