### ISSUE TITLE
[Feature] Some Enhancements i got in my mind

### ISSUE THREAD

**Issue by PanosssD** [tomaae/homeassistant-mikrotik_router#82]
Hello.
some new enhancements i`ve got in my mind based on my setups

 **Is it possible to get scheduler status (enabled/next run/comment)**
> I have a scheduler:
> Schedule Reboot at 3 am and it will be usefull if i can enable it from HA and get status 

Also it will be good to get logs (or some logs eg only a buffer called HA)
to visualize it inside HA

**Another good feature will be to clear attackers list something like:**
- show a list with attackers address list (IPs)
- have the ability to press a button to clear attackers list
or run a script with that button eg:
`/ip firewall address-list remove [find list=Attackers]`

**also i have scripts eg. Advanced Firewall toggle ON/OFF which:**
> 1. Checks comment of the script (if its advanced toggles to basic and vice versa)
> 2. Finds firewall rules with ~ADV comment and enables or disables these rules
> 3. sets comment of script to the new status and adds a log entry
> so i think if you can get comment to HA entity attribute it wil be like a whole new platform because you can do anything with scripts and just post the comments to HA 

**Here is the code for reference**
``` 
#Find Comment on Filter & Raw and TOGGLE ON/OFF

 #BEGIN SETUP
 :local NAME ".Advanced Firewall <-> Basic Firewall"
 :local toTOGGLE "ADV"
 :local ONcomm "Advanced Firewall is Running"
 :local OFFcomm "Basic Firewall is Running"
 #END SETUP

 #Predifined Variables
 :local gtCOMM [system script get [find name=$NAME] comment]

 #First RUN
 :if (($gtCOMM ="$ONcomm") || ($gtCOMM ="$OFFcomm")) do={} else={
 system script set [find name=$NAME] comment="$ONcomm"
 exit
 }

 #OFF -> ON
 :if ($gtCOMM ="$OFFcomm") do={
 system logging disable [find action=LogFileBIG topics~"account" topics~"info"]
 /ip firewall filter enable [find comment~"$toTOGGLE"]
 /ip firewall raw enable [find comment~"$toTOGGLE"]
 /system logging enable [find action=LogFileBIG topics~"account" topics~"info"]
 /system script set [find name=$NAME] comment="$ONcomm"
 }

 #ON -> OFF
 :if ($gtCOMM ="$ONcomm") do={
 system logging disable [find action=LogFileBIG topics~"account" topics~"info"]
 /ip firewall filter disable [find comment~"$toTOGGLE"]
 /ip firewall raw disable [find comment~"$toTOGGLE"]
 /system logging enable [find action=LogFileBIG topics~"account" topics~"info"]
 /system script set [find name=$NAME] comment="$OFFcomm"
 }

 :local gtCOMM [system script get [find name=$NAME] comment]
 :log warning message="$gtCOMM (Changed by User)"
```

**Comment by tomaae** [comment]
You can already execute scripts from integration. As to see the data, you can put them into environment variables and read them in HA.
HA is not suitable for reading address list, it would result in large number of deleted entities.

It is possible to change comments, but what you describe may be better to leave to scripts, since creating automation for that could be really complicated.
