### ISSUE TITLE
[Feature] Different order for device tracker hostname resolve

### ISSUE THREAD

**Issue by clau-bucur** [tomaae/homeassistant-mikrotik_router#86]
## Is your feature request related to a problem? Please describe.

Would it be possible to change the order the hostnames are resolved for device tracking?
The current order is, as mentioned in #24: DNS, DHCP mikrotik comment(useful for reserved DHCP addresses), DHCP hostname, MAC address

## Describe the solution you'd like

Would it be possible to make the **DHCP mikrotik comment** the top priority here?
As it's something the user sets up, it makes sense to use it over all other, as it's under user's control.

## Describe alternatives you've considered

I've changed my `mikrotik_controller.async_process_host` to process in that order, but I'd rather make a PR for it, if accepted, so I don't have to locally maintain this change on every release.

## Additional context

I use this for 20+ leases I manage and would let me be in control to the entity IDs the integration creates for device trackers.

**Comment by tomaae** [comment]
Hmm, how is DNS being a priority here cause any issues? if you didnt set it up in DNS, it should go to DHCP comment next. Or am I missing something?

**Comment by clau-bucur** [comment]
Yeah :)
I also have a DHCP script to create static DNS entries for DHCP leases, but those dns entries have a different format than the DHCP comment.

**Comment by tomaae** [comment]
ah, I see. that makes sense then.
better approach would be:
1. DNS comment
2. DHCP comment
3. DNS hostname
4. DHCP hostname
5. MAC address

This would keep both correct logical approach while allowing customization for people who want that.

**Comment by clau-bucur** [comment]
Order looks good. There's one issue though. My DHCP script adds a "#DHCP" comment to the "dynamic created static dns entries" so that it knows those entries are created by it and can manage them.

**Comment by clau-bucur** [comment]
Then that's perfect! Thank you.

**Comment by tomaae** [comment]
All implemented. will be in next release soon.
