### ISSUE TITLE
[Enhancement] Sensor selection does not show during setup

### ISSUE THREAD

**Issue by clau-bucur** [tomaae/homeassistant-mikrotik_router#87]
## Describe the issue

After upgrading to 1.6 I reinstalled the Mikrotik Router integrations so that I can select only those sensors I need.
However the "Sensor selection" dialog does not show up.

## How to reproduce the issue

1. Add "Mikrotik Router" integration
2. Set the name "Main", set the host "main.gme", set user and password. Then click Submit.
3. The "Success!" window pops up showing the detected devices. After I click "Finish" the new integration is created.
4. No "device tracker" entries are created.

## Expected behavior

"Sensor selection" dialog to be visible after integration setup dialog.

## Software versions

 - Home Assistant version: HA v2021.1.2 
 - Mikrotik Router integration version: v1.6 
 - Mikrotik Hardware: RouterBOARD 3011UiAS & 2011UiAS-2HnD 
 - RouterOS version: v6.48

**Comment by tomaae** [comment]
I dont think thats possible.
I tried that before for initial setup, but variables from installation and option dialogues seem to be stored differently and cannot be access from one another.

**Comment by clau-bucur** [comment]
Not sure what you mean :) I was not asking for a "new feature".
I was saying that for me, the **"Select sensors" dialog is not showing**:
![image](https://user-images.githubusercontent.com/47672949/104726017-989c5000-573b-11eb-9b0f-e71539abd654.png)

So I can't specify the types of sensors the integration should add.
Or am I misunderstanding something from what you said?

**Comment by tomaae** [comment]
possibly we are both misunderstanding :)
this dialog is only available from integration options. its on 2nd page.

**Comment by clau-bucur** [comment]
Pff! Indeed. I go to Integrations / Mikrotik Router integration / Options / click Submit on the "Basic options" page => it shows then the "Select sensors" page.
It was not clear, for me, from the intructions.
Thank you. Closing.
