### ISSUE TITLE
Missing RX/TX ETH sensors the integration.

### ISSUE THREAD

**Issue by zsgodor** [tomaae/homeassistant-mikrotik_router#89]
Hi,
I update the Mikrotik Router integration HA, with HACS, after the update i re add the Integration, and my all Mikrotik devices.
Now i cant see the ETH sensor my Mikrotik devices. I see only the switch, and health sensors. (See the attached pictures.)
I cant find the Sensor Selection panel my HA settings, i see only switch.
Thank you for your support. If you need more information, please feel free.
My Mikrotik Router version.: 1.6
Mikrotik OS: v6.48 (all of my devices)
![Képernyőfotó 2021-01-15 - 19 52 02](https://user-images.githubusercontent.com/64435192/104766623-2e030880-576b-11eb-9ebf-fc4d6798b15a.png)

![Képernyőfotó 2021-01-15 - 19 48 05](https://user-images.githubusercontent.com/64435192/104766451-ea100380-576a-11eb-83db-3951cdeeb2bc.png)
![Képernyőfotó 2021-01-15 - 19 49 39](https://user-images.githubusercontent.com/64435192/104766460-eb413080-576a-11eb-9190-d3ce1358f60a.png)

## System Health

version | 2021.1.3
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 4.19.0-8-amd64
arch | x86_64
timezone | Europe/Budapest

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.10.0
Stage | running
Available Repositories | 775
Installed Repositories | 8

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 43

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | 2020.12.7
docker_version | 19.03.11
disk_total | 113.1 GB
disk_used | 34.8 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | TasmoAdmin (0.13.1), Mosquitto broker (5.1), File editor (5.2.0), SQLite Web (2.2.2), Simple Scheduler (0.16.10), ESPHome (1.15.3), Portainer (1.1.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
mode | storage
views | 7
resources | 1

</details>

**Comment by tomaae** [comment]
sensor selection is on second page in options

**Comment by zsgodor** [comment]
I can't see the second page, how can i switch second page?
I see only this page in option.
![Képernyőfotó 2021-01-15 - 20 07 20](https://user-images.githubusercontent.com/64435192/104809704-69471b00-57ef-11eb-9bc0-3ade0e821746.png)

**Comment by asifkassam** [comment]
Ethernet sensors also removed on upgrade to 1.60 for me - not seeing them under options second page and they are unavailable

![image](https://user-images.githubusercontent.com/67918736/104810169-ad401d00-57fb-11eb-9955-bb88e634f530.png)
![image](https://user-images.githubusercontent.com/67918736/104810283-1a53b280-57fc-11eb-8dbb-12eb424fb499.png)

**Comment by zsgodor** [comment]
I understand, thank you. 👍

**Comment by tomaae** [comment]
> 
> 
> Ethernet sensors also removed on upgrade to 1.60 for me - not seeing them under options second page and they are unavailable
> 
Port traffic sensors

**Comment by asifkassam** [comment]
thanks
