### ISSUE TITLE
[Feature] Remove included librouteros library

### ISSUE THREAD

**Issue by tjorim** [tomaae/homeassistant-mikrotik_router#9]
**Is your feature request related to a problem? Please describe.**
Not really a problem, HA release 0.105 will include librouteros version 3.0.0.

**Describe the solution you'd like**
Remove the included librouteros library. Mostly revert commits related to https://github.com/tomaae/homeassistant-mikrotik_router/issues/2.

**Comment by tomaae** [comment]
yes, I plan to do that. but I will wait a while to give people time to upgrade

**Comment by tjorim** [comment]
Sure, just creating the issue as a reminder and track progress.
