### ISSUE TITLE
[Bug] Unable to find Mikrotik Router

### ISSUE THREAD

**Issue by ranrinc** [tomaae/homeassistant-mikrotik_router#90]
## Describe the issue
Clean Install my old HA Core on my synology and install them one by one. Running the latest 1.10.0 HACS and 2021.1.3. After adding mikrotik router into HACS and restart, base on my portainer (docker) I can see that Mikrotik Router detected. 

However, when I run it through Integrations nothing appear on it. It show only the main mikrotik integration module. 

## How to reproduce the issue
Go to HACS
add the Integration module 1.6.0
Restart HA
Detected on portainer logs
Go to Integrations
Search Mikrotik Router
No where to be found

## Expected behavior
Find the Integration to be added

## Screenshots
![Screen Shot 2021-01-16 at 6 12 50 PM](https://user-images.githubusercontent.com/15801696/104810346-7e8b6c00-5826-11eb-8ab4-d77d896248f7.png)

## Software versions
 - Home Assistant version: 2021.1.3
 - Mikrotik Router integration version: v1.6.0
 - Mikrotik Hardware: 962UiGS-5HacT2HnT
 - RouterOS version: 6.45.5

**Comment by tomaae** [comment]
You will have to check your logs. Something failed during the installation. I seen HACS do this with integration few times before.

**Comment by sergey732002** [comment]
I also couldn't find "mikrotik router" in the browser on the computer (with the browser cache cleared), but I was able to find it from the phone. 
![image](https://user-images.githubusercontent.com/63905778/104897671-b5c65e00-5989-11eb-9920-7c051d4bbff8.png)
![image0 (4)](https://user-images.githubusercontent.com/63905778/104898221-62a0db00-598a-11eb-866e-8b4c1e8ac3c8.png)

**Comment by tomaae** [comment]
I had such issues reported few times already. However, this is not an integration issue. It has something to do with how HACS or HA handles it.
