### ISSUE TITLE
1.6: All entities are unavailable

### ISSUE THREAD

**Issue by kbalint** [tomaae/homeassistant-mikrotik_router#91]
After upgrading HACS to 1.10 and Mikrotik Router to 1.6, all previously working entities are 'unavailable'. The log is empty, the router is working as it was for the last 30+ days.
Could you please guide me with any checks / logging / debugging? Thanks.

![image](https://user-images.githubusercontent.com/4146263/105063208-c525d400-5a7b-11eb-8e95-7a11b3a345ba.png)

**Comment by tomaae** [comment]
You just need to enable which sensors you want in integration options. Only port switches and System sensors are enabled by default.

**Comment by tjorim** [comment]
Also, check the Home Assistant logs. It's possible the account you're using
for this integration has not enough access rights, causing it to error and
stop loading entities.

Op di 19 jan. 2021 18:05 schreef Tomaae <notifications@github.com>:

**Comment by kbalint** [comment]
hi, thanks for your reply. I've checked the logs, everything is working OK, the user has all required rights (used by another app too).

Where do I found any options for enabling sensors? Under settings > Integrations > Options I see this:

![image](https://user-images.githubusercontent.com/4146263/105078549-77669700-5a8e-11eb-8d63-7f461c8fafc9.png)

And with system options just this:

![image](https://user-images.githubusercontent.com/4146263/105078591-83525900-5a8e-11eb-831d-689969aeed4f.png)

**Comment by kbalint** [comment]
OK, sorry - found it. I have never ever thought in my life that there's a second 'options' page after submitting the basic options.
Is this a requirement to have it this way? :)

**Comment by kbalint** [comment]
OK, I've found something in the logs:

`2021-01-19 20:02:14 ERROR (MainThread) [homeassistant.util.logging] Exception in update_controller when dispatching 'mikrotik_router-update-Mikrotik': ()


Traceback (most recent call last):


  File "/config/custom_components/mikrotik_router/sensor.py", line 210, in update_controller


    update_items(


  File "/config/custom_components/mikrotik_router/sensor.py", line 274, in update_items


    mikrotik_controller.data[SENSOR_TYPES[sensor][ATTR_PATH]][


KeyError: 'temperature'

`

All of the entities first came up, then everything went to 'unavailable'.

**Comment by tomaae** [comment]
Can you give me full debugs?

**Comment by kbalint** [comment]
Okay, 
I've found some things: 
1) my hass group on the router did not have the 'policy' setting checked.
2) I have created DEBUG flagged logs (I can send you privately).
3) According to the logs, I've modified sensors.py to have a try: except: where it had an exception.
4) after several restarts, some things started working. I've created an 'auto-generated' lovelace page, to compare it with my hand made one. There I have all entries as duplicate, for example:

![image](https://user-images.githubusercontent.com/4146263/105159542-7d508c80-5b0f-11eb-9875-e534b403e088.png)

these entites are named **switch.mikrotik_nat_tcp_22222** and **switch.mikrotik_nat_tcp_22222_2** accordingly.
So for some reason, the 'original' entities does not work anymore, all had been renamed to _2.

How could I reset everything to have it auto-rediscovered (and hopefully re-named to the previous name)? Thank you.

**Comment by tomaae** [comment]
1. Ah yeah, missing policy will crash environment query and everything after wont run. Someone already had that.
3. Adding that is not a good idea, it will cause issue elsewhere. It should be fine now since you added correct access right.
4. Arent those from before update to 1.6? You can reset it by removing your router from integration and readding it.
5. Something else could be crashing, check the log. Just restore everything to default, including change you did to code and do debugs again.

**Comment by kbalint** [comment]
Hi. On the weekend I've removed and reinstalled the component. The duplicates are gone, but the previously working **sensors** are missing still, only ether[1...5], pppoe and wlan[1..3] are populated. However **device_tracker** has all the standalone devices. I see no errors in the logfile. What can I debug further? Thanks.

**Comment by tomaae** [comment]
have you enabled sensors you are looking for in integration options?
if so, what are you missing?

**Comment by kbalint** [comment]
![image](https://user-images.githubusercontent.com/4146263/105688590-16114e80-5efa-11eb-9f91-be9ff88145b7.png)

Are there any more settings?

_"For example, I have my Raspberry named RASPI. There's a device_tracker.raspi_2, but no sensor.raspi_2_wan_rx and sensor.raspi_2_wan_tx (neither the original sensor.raspi_wan_rx, sensor.raspi_wan_tx)."_

I want all my rx/tx sensors back for all my devices. In my understanding this component had these sensors. I use UPnP also, but that has different naming conventions.

**Comment by kbalint** [comment]
ok, restarted the stack a millionth time, and here's an error, right after populating all SCRIPTS:

> 2021-01-25 11:06:52 DEBUG (MainThread) [custom_components.mikrotik_router.switch] New switch Mikrotik (script mikrotik-cloud-backup)
> 2021-01-25 11:06:52 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform mikrotik_router
>   File "/config/custom_components/mikrotik_router/sensor.py", line 531, in device_info
> 2021-01-25 11:06:52 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mikrotik_router platform for sensor
>   File "/config/custom_components/mikrotik_router/sensor.py", line 531, in device_info
>

**Comment by kbalint** [comment]
I've added debug here line 531:

```
@property
    def device_info(self) -> Dict[str, Any]:
        """Return a description for device registry."""
        info = {
            "connections": {(CONNECTION_NETWORK_MAC, self._data["mac-address"])},
            "default_name": self._data["host-name"],
        }
        _LOGGER.debug('itt')
        _LOGGER.debug(self._data)

        if self._data["manufacturer"] != "":
            info["manufacturer"] = self._data["manufacturer"]

        return info
```

> 2021-01-25 11:24:47 DEBUG (MainThread) [custom_components.mikrotik_router.sensor] itt
> 2021-01-25 11:24:47 DEBUG (MainThread) [custom_components.mikrotik_router.sensor] {'address': '192.168.1.xxx', 'mac-address': 'xx:yy:zz:hh:ee:ff', 'host-name': 'ubuntu', 'tx-rx-attr': 'Kbps', 'available': True, 'local_accounting': False, 'wan-tx': 0.0, 'wan-rx': 0.0}
> 

none of the entities has a 'manufacturer' attribute. 
I don't know how python handles json, but i guess there should be a null check here instead of a string empty check?

**Comment by tomaae** [comment]
ah yes, try installing master. that accounting issue is already fixed.

**Comment by Pavel-Vovk** [comment]
I've encountered the same issue

![image](https://user-images.githubusercontent.com/20834458/106220473-40a62480-61e4-11eb-9e56-d0be5fe86e3d.png)
Now I Can solve it ? 
where I need to enable old functionality?

**Comment by tomaae** [comment]
Did you checked everything in this issue and applied it?

**Comment by Pavel-Vovk** [comment]
> ![image](https://user-images.githubusercontent.com/4146263/105688590-16114e80-5efa-11eb-9f91-be9ff88145b7.png)
> 
> Are there any more settings?
> 
> _"For example, I have my Raspberry named RASPI. There's a device_tracker.raspi_2, but no sensor.raspi_2_wan_rx and sensor.raspi_2_wan_tx (neither the original sensor.raspi_wan_rx, sensor.raspi_wan_tx)."_
> 
> I want all my rx/tx sensors back for all my devices. In my understanding this component had these sensors. I use UPnP also, but that has different naming conventions.
I'll try to find these settings... but not I've restored the old version. where all sensors were available. 
Maybe on weekend, I'll try to configure out how I can resolve it? 
![image](https://user-images.githubusercontent.com/20834458/106222965-3a667700-61e9-11eb-9aa6-8214c680a235.png)
Where I'll need to find this new configuration?  On 1 or on 2. Sorry - I'm from Ukraine and in my home Ukrainian language more useful for my family.
Do you have some scenarios of how I could resolve it?

**Comment by tomaae** [comment]
Its in options, same as with all integrations. Not sure how its called in your language, but most likely the second option at bottom of integration window.
![image](https://user-images.githubusercontent.com/23486452/106224904-67645b00-61e4-11eb-9bc1-750c766032e6.png)

You can just install master, if you are affected by same issue. Its related only to accounting, so if you dont use accounting, it does not matter.

**Comment by Pavel-Vovk** [comment]
Ok. I'll try at the weekend. The Installation process is:
1. Download the master branch (pull)
2. Copy files from /custom_components/mikrotik_router to HA_config
3. Restart the HA
Do I need some other else?
