### ISSUE TITLE
[Feature] Switches for firewall filter rules

### ISSUE THREAD

**Issue by hellcry37** [tomaae/homeassistant-mikrotik_router#92]
## Is your feature request related to a problem? Please describe.

This integration can do a lot of things, but, I could not find a way to simple turn of / on filter rules. I see NAT switches in Home Assistant, I see Mangle switches but nothing for filters.

## Describe the solution you'd like

Please add switches for filters (actual firewall rules) exactly how you did for nat and mangle.

## Describe alternatives you've considered

None I am not so advanced.

**Comment by tomaae** [comment]
Not sure this can even be done without running into conflicts all the time.
Why do you want to control individual filters?

**Comment by hellcry37** [comment]
I have one that disable youtube, one for facebook, I want to be able to switch them on / off from within home assistant, is that possible? I mean is hard to always login to router to enable / disable them, especially if I am not home.

**Comment by hellcry37** [comment]
those are the ones i am talking about:
/ip firewall filter
add action=drop chain=forward comment="Block Youtube" disabled=yes layer7-protocol=Block-Youtube src-address=192.168.1.0/24
add action=drop chain=forward comment="Block Facebook" layer7-protocol=Block-Facebook src-address=192.168.1.0/2

**Comment by ebendl** [comment]
Agreed, this would be very useful. I currently have 2 scripts that I can call that enable or disable a specific rule (in my case, to block Whatsapp during family time) but it would be much better having a single switch.

**Comment by tomaae** [comment]
It is already planned, so it will be implemented.

**Comment by hellcry37** [comment]
I am very, very, glad you decide to implement it, I'll take this opportunity to just say thank you very much!

**Comment by tomaae** [comment]
Added, will be available in new version very soon.
