### ISSUE TITLE
[Bug] Devices that no longer exist are not removed (device tracker)

### ISSUE THREAD

**Issue by clau-bucur** [tomaae/homeassistant-mikrotik_router#95]
## Describe the issue

When a new DHCP client connects a new Home Assistant device is created by the integration.
However if I remove any traces of that DHCP lease, the device remains in HA and cannot be removed by any means, other than removing the integration and adding it again.

## Expected behavior

Devices that are no longer existing in Mikrotik should be removed, or should be allowed to be removed by the user.
Currently there is no "Delete" option on the device page.

Also if "device tracker" is enabled in the integration, and a device_tracker entity is created once a DHCP client is connected with some generic name, later if the name is changed in Mikrotik the entity name does not change to reflect the change.

For example I connect for the first time a Shelly Dimmer2 which registers with DHCP with name "shellydimmer2_e8db84d4a215". The integration will create an tracker entity "device_tracker.shellydimmer2_e8db84d4a215".
If I provide a DHCP comment for that Shelly device with text "Shelly Living", would be nice if the integration renamed the entity to "device_tracker.shelly_living".

In order to get the expected result one would need to delete the Mikrotik integration and add it again.

## Software versions

 - Home Assistant version: HA v2021.2 
 - Mikrotik Router integration version: 1.6 
 - Mikrotik Hardware: RB3011UiAS 
 - RouterOS version: v6.48

**Comment by clau-bucur** [comment]
Thanks for answering. The thing is that even after restarts the device cannot be removed. Or at least I haven't found a way.
I have here this device which is not available in MT for some weeks now:
![image](https://user-images.githubusercontent.com/47672949/107046937-e43c9980-67cf-11eb-88b5-0d102d3f36d0.png)

**Comment by clau-bucur** [comment]
Indeed the entity looks like it's restored but HA does not let go of it to allow me to delete it:
![image](https://user-images.githubusercontent.com/47672949/107047077-15b56500-67d0-11eb-85aa-97e74d35cd1f.png)

**Comment by tomaae** [comment]
I'm not able to find anything on this unfortunately.
I have reached out to HA developers directly, hopefully we can get some info, one way or another.

**Comment by clau-bucur** [comment]
I see. Ok, let's see what do they say.

**Comment by tomaae** [comment]
Reply from Frenck:
```
You should be able to remove those entities.
Condition is that they are no longer hold/provided by the integration
```
Can you try?

**Comment by clau-bucur** [comment]
That's the thing, I have no way to remove them from the Devices page in HA.
Could be because the "device is hold/provided by the integration" ?

**Comment by antonwantstosleep** [comment]
Take a look at [core Tasmota integration](https://github.com/home-assistant/core/blob/dev/homeassistant/components/tasmota/__init__.py). There are some functions to handle device removal. And there is a button to remove device (and it works no matter if it is held by the integration or not).

![Tasmota](https://user-images.githubusercontent.com/42086444/132633082-f7ac35fe-2003-4fbe-9674-3c0ce412d39b.png)

I can press "Remove" button at the device page and all the entities are deleted too.
Then I can update (ex. hostname or relay name) in Tasmota device, reboot it and the integration will find and create that device (and all it`s entities) again but with a new name.

Very useful.

**Comment by tomaae** [comment]
Difficult to say since I cant read it, but isnt that removal of integration instance?
Integration instances can be removed this way. But not specific tracker sensors from one integration instance.

**Comment by clau-bucur** [comment]
![image](https://user-images.githubusercontent.com/47672949/132849345-850e5afd-4ad5-48fa-be08-7739f8c8b842.png)
It belongs to the device page, not to integration instance removal.

**Comment by tomaae** [comment]
yea, but with tasoma, every device is separate integration instance. isnt it? if I understand it right, its like esphome.
in integration page, does it show like this?
![image](https://user-images.githubusercontent.com/23486452/132891994-1c30714a-6173-417c-8271-dddc5c81b661.png)

or like this?
![image](https://user-images.githubusercontent.com/23486452/132892026-40a044e1-7365-45f6-b1cc-8d130322f426.png)

**Comment by clau-bucur** [comment]
Second option:
![image](https://user-images.githubusercontent.com/47672949/132918935-1dab9d17-2413-428d-be20-8172c7155c0d.png)
So it's not a separate integration for each device.

**Comment by tomaae** [comment]
Interesting. I will have a look at it.

**Comment by clau-bucur** [comment]
Here's a component that just added this feature: https://github.com/custom-components/ble_monitor/releases/tag/5.3.0
`Improves deletion of devices. The UI has now the option to delete a device from the device options menu. The device is now also deleted from the registry, no manual deletion of sensor entities is required any longer.`

Or at least that's what I understand from this message, I have not checked the code change.

**Comment by tomaae** [comment]
That looks like removal of devices, not individual trackers.
Looking at tasmota integration. It seems that it works like I said before. For some reason it is just not listing separate devices correctly.

**Comment by skynetua** [comment]
@tomaae could you please add option to not report to HA device trackers with source 'arp' at all? I have a lot of stale devices from my ISP.

**Comment by tomaae** [comment]
> @tomaae could you please add option to not report to HA device trackers with source 'arp' at all? I have a lot of stale devices from my ISP.

can you give me examples from routeros?
also please open new issue for it, we dont want to mix it with this.

**Comment by tomaae** [comment]
I was not able to find anything regarding tracker removal. unifi certainly does not have this feature from what I can see.
Not sure if we can force HA to remove such entry using UI.
If you can find an integration where individual entities can be removed like that, I will gladly take a look.

**Comment by tomaae** [comment]
![image](https://user-images.githubusercontent.com/23486452/152618918-94dd5269-5bf5-40c7-ae65-43de084fa8e1.png)
Works in master now. It got fixed as a side product of me reworking all entities.
I dont recommend using master until next release. There are breaking changes and few more will happen before release.
