### ISSUE TITLE
[Bug] No 'version' key in the manifest file for custom integration 'mikrotik_router'

### ISSUE THREAD

**Issue by mrtnbr** [tomaae/homeassistant-mikrotik_router#98]
## Describe the issue

When starting home assistant with the integration, the following message is shown:

> 2021-02-15 21:19:59 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'mikrotik_router'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'mikrotik_router'

It does not show in home assistant 2021.2.3, but it shows up in 2021.3.0.dev0

## How to reproduce the issue

Run the integration on 2021.3.0.dev0

## Expected behavior

No message in log

## Software versions

 - Home Assistant version: 2021.3.0.dev0 
 - Mikrotik Router integration version: 1.6 
 - Mikrotik Hardware: RB960PGS (and cAP AC) 
 - RouterOS version: v7.1beta4 

## Additional context

Using home assistant dev in visual studio code

**Comment by tomaae** [comment]
thanks for an advanced notice, fixed
