### ISSUE TITLE
Can't install in Home Assistant

### ISSUE THREAD

**Issue by mikesellt** [tomaae/homeassistant-mikrotik_router#99]
I installed the "Mikrotik Router" integration in HACS per the instructions.  I created a username on my router.  The next step in the instructions says to install the integration in the main Home Assistant integrations section, and be sure not to confuse it with the official "Mikrotik" integration.  I can't find the "Mikrotik Router" integration in the list.  I can only see the official "Mikrotik" integration.  I double-checked HACS, and I see the integration is installed.  Am I missing something, or is this a bug with the latest HA version?

**Comment by tomaae** [comment]
Assuming you restarted you HA after installation, I can only suggest to remove and install it again.
I know this rarely happens with HACS for any integration, but I dont know the cause.

**Comment by mikesellt** [comment]
> Assuming you restarted you HA after installation, I can only suggest to remove and install it again.
> I know this rarely happens with HACS for any integration, but I dont know the cause.

Thanks for your quick reply!  I restarted HA a couple of times and just uninstalled/reinstalled the integration via HACS as well as removed any other Mikrotik-related configuration or integrations.  It appears the files were added to the custom_components folder properly.  I will see if I can get some logs.  Thanks again for the reply.

**Comment by tomaae** [comment]
Yes, check it and let me know if you figure out something new.

**Comment by mikesellt** [comment]
> Yes, check it and let me know if you figure out something new.

Thanks.  Sorry for wasting your time.  I was able to install it after restarting again but also clearing my browser cache.  It may be helpful to add clearing the cache to the installation instructions, but I'm not sure if any others have had this same issue.  Thanks again for your help.

**Comment by tomaae** [comment]
It could have been issue with a cache itself, I doubt that list is supposed to be cached.
Maybe chrome? That browser is known to ignore settings and cache aggressively even parts that are set not to be cached.
